### ISSUE TITLE
Support for variable block size 

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#100]
From the JUCE documentation:
> The number of samples in these buffers is NOT guaranteed to be the same for every
        callback, and may be more or less than the estimated value given to prepareToPlay().
        Your code must be able to cope with variable-sized blocks, or you're going to get
        clicks and crashes!

That's not managed by the plugin and I guess that's why there are clicks or audio glitches when looping in Reaper (see this [thread](https://forum.pdpatchrepo.info/topic/11285/crackling-asio-on-pd-vanilla-0-48-test-2-on-64-bit-windows/7)).

**Comment by pierreguillot** [comment]
After more tests on Reaper, it seems really necessary because sometimes the size of the block can really be any value. For the moment, the plugin can't crash even if the number of samples varies because the current version avoid to process when such cases happend but the perform method can lost some samples. 

A good solution seems a bit complicated to implement and implies a minimum 64 samples of latency (pd block size) that can be compensated using the latency option of the plugin. So I guess it will also be the time to add a better support for a dynamic  latency that could depends on the sample rate or whatever (see the suggestion by Alfonso #62). So the real latency of the plugin will be user-latency+pd-block-size.

**Comment by alfonso73** [comment]
Hi,
@pierreguillot will we still be able to deal with block~ size of 1 sample?
This is very important for designing custom filters and generally speaking with any process involving some sort of feedback in the audio path.

**Comment by pierreguillot** [comment]
Yes of course. It manages the audio signals between the DAW and the plugin but Pd internal audio management is unchanged.

**Comment by alfonso73** [comment]
great!
