### ISSUE TITLE
bendin output values incorrect

### ISSUE THREAD

**Issue by SeanArchibald** [pierreguillot/Camomile#104]
The output from bendin is not as expected.
    - Run the [Test.zip](https://github.com/pierreguillot/Camomile/files/1852198/Test.zip) project as a plugin in your DAW
    - Move your keyboard pitch wheel up and down, this will show the current, min and max values received from the bendin object
    - Expected results are: Min=0, Max=16384. With the pitch wheel at rest, the current value should be 8192.
    - Actual results are: Min=8192, Max=16256. With pitch wheel at rest, current value is 16256

![screenshot_20180327_143131](https://user-images.githubusercontent.com/11957541/37971292-78bc876e-31cd-11e8-9b81-38873bf75ebd.png)

Have I made a mistake with how I'm using bendin here, or is it a bug that others can reproduce? Thanks!

**My environment**
    - **OS**: Ubuntu 16.04
    - **DAW**: Bitwig 2.2.2
    - **Plugin**: VST2 v1.0.3
    - **Keyboard**: M-Audio Keystation 88

**Comment by pierreguillot** [comment]
You're right, libpd adds 8192 to the pitch bend value. I fixed it b4cd19c :) Thanks! 
I think the maximum value is a side effect of this offset. 
And are you sure that the maximum should be 16384 and not 16383? 
16383 seems now consistent with libpd (so Pd) and Juce.

**Comment by SeanArchibald** [comment]
The max should be 16383 - you're right.

Very happy to see this will make it into 1.0.4. Looks like this will be a very good release Pierre!!
