### ISSUE TITLE
Linux 64 bit v1.0.4 midi noteout issue?

### ISSUE THREAD

**Issue by danballance** [pierreguillot/Camomile#107]
Linux Ubuntu 16.04. 
Bitwig Studio DAW using Jack.
v1.0.4 VST2.

I've created [MidiExample.zip](https://github.com/pierreguillot/Camomile/files/1881928/MidiExample.zip) a really simple plugin that demonstrates the issue for me.

If I use the FX .so from 1.0.3 and feed the plugin a whole note every bar then a single note is generated for each bar.

If I swap the .so file out for the 1.0.4 version nothing plays until bar 12 when I get a single note and then a long gap of many bars again before a single note plays once again.

Are you able to reproduce this at all? Thanks in advance.

**Comment by pierreguillot** [comment]
I think (I hope) I fixed it! It would be great if you could test it. 
Do you know how to compile?

**Comment by danballance** [comment]
That's brilliant news! I should have time to take a look at this later today. I've not compiled this project before, but I am relatively used to the process. Shouldn't hopefully present a problem.

**Comment by danballance** [comment]
Okay so I've put a some time into getting this to compile but I have hit an issue that I don't seem able to solve.

```
> make -C Instrument/Builds/LinuxMakefile TARGET_ARCH=-m64 CONFIG=Release
make: Entering directory '/home/dan/Code/cpp/Camomile.github/Instrument/Builds/LinuxMakefile'
Linking Camomile - Shared Code
Linking Camomile - VST
/usr/bin/ld: cannot find -lpd-multi
collect2: error: ld returned 1 exit status
Makefile:127: recipe for target '../../../Plugins/Camomile.so' failed
make: *** [../../../Plugins/Camomile.so] Error 1
```
I'm not having any luck working out where I can build pd-multi from? I've searched my system and it doesn't seem to exist - even if I run `make -C Dependencies/LibPd/build/makefile all`.

I've run through the Linux build instructions [here](https://github.com/pierreguillot/Camomile/wiki/How-to-compile-the-plugins#linux).

**Comment by danballance** [comment]
That's working great for me now. Thanks for the help and fast response. I'll close the ticket.
