### ISSUE TITLE
Add latency compensation for block bypass

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#108]
It seems that it should done manually in the `processBlockBypass()` method of the processor.

**Comment by pierreguillot** [comment]
Perhaps the plugin should send a notification to the patch and let it manage with a `[block~]` object. This way, the plugin can still receive the other events...

**Comment by alfonso73** [comment]
Hi Pierre, what this feature is intended for?

**Comment by pierreguillot** [comment]
Plugins have a bypass option or a bypass parameter (VST3). For the moment, when a plugin is bypassed, the DSP method of Pd is avoid and the incoming signals are unchanged. But if the patch implies latency, bypassing the plugin will creates artifacts such as pre-echoes or time-shifting. Moreover, one could want to cross-fade the signals to avoid glitches and crackles for examples.

The solution I'm working on is to add an option to deactivate the automatic bypass and let the plugin creator the possibility to manage it in the patch when receiving the notification (bypass 1 or 0). This way, the latency could be preserved and to avoid crackles, he could apply a ramp on the signal and use the object `[block~]`.

**Comment by pierreguillot** [comment]
Here are several way to use this feature: **Important:** Use the option `autobypass false`.

- To preserve latency and to avoid time-shifting (when using delays, FFT, etc.):

<p align="center">
<img width="404" alt="screen shot 2018-06-02 at 11 57 50 am" src="https://user-images.githubusercontent.com/1409918/40873196-33e2b2ee-665c-11e8-86a8-ef90f6b4d49a.png">
</p>

- To apply a cross fade between the wet and the dry signals:

<p align="center">
<img width="434" alt="screen shot 2018-06-02 at 11 34 18 am" src="https://user-images.githubusercontent.com/1409918/40873029-35dcb91c-6659-11e8-8686-56c12783dd85.png">
</p>
   
**Note:** You combine the two mechanisms.

- To avoid unnecessary computation:
  **Important:** This mechanism, must be used in a subpatch or abstraction where the transformation of the original signal is performed. The two previous mechanisms to switch between the wet and dry signals must still be active.

<p align="center">
<img width="250" alt="screen shot 2018-06-02 at 11 35 28 am" src="https://user-images.githubusercontent.com/1409918/40873068-d6c36d76-6659-11e8-9229-ba7a62f22880.png">
</p>

**Comment by pierreguillot** [comment]
Close - see [bypass](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#bypass)
