### ISSUE TITLE
Multichannel and side-chain

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#110]
The setting of multichannel plugins and/or side-chain plugins is a bit confusing. It would be great to think an improvement of the audio buses management.

**Comment by pierreguillot** [comment]
I try something on a dev branch. I explain:

In the properties file, now I want to use `buses` instead of `bus`. It will let you to create buses layouts for side-chain processing or multichannel processing. The syntax is `buses [bus1_ninputs bus1_noutputs] [bus2_ninputs bus2_noutputs] etc.]`. I guess more than 2 buses is very rare... The 2nd buse is used for side-chaining. And if you want multichannel possibilities you use only 1 bus per buses layout.

If you want to create a standard main bus the syntax is (1)
```
buses [2 2];
```
If you want to use a side-chain, you can do something like (3)
```
buses [2 2] [1 0];
```
If you want to be add alternative possible buses you can add for example (2)
```
buses [2 2];
buses [4 4];
buses [6 6];
buses [8 8];
buses [10 10];
buses [12 12];
```

In the patch, you receive via the object `[receive bus]` a list with the index of the bus, the type (input/output), the number of channels, the description.

I tested it on Reaper that has as far I know the best multichannel support (otherwise if someone know a better DAW that is free or with a free trial) with a VST3 (VST2 is not so good for multichannel processing). 

(1) gives
bus: `[0 input 2 stereo(`
bus: `[0 output 2 stereo(`

(2) gives
bus: `[0 input 2 stereo(`
bus: `[0 output 2 stereo(`
bus: `[1 input 1 discrete(`

(3) gives depending on your configuration
bus: `[0 input 2 stereo(`
bus: `[0 output 2 stereo(`
or
bus: `[0 input 4 1st order ambisonics(`
bus: `[0 output 4 1st order ambisonics(`
or
bus: `[0 input 6 5.1 surround(`
bus: `[0 output 6 5.1 surround(`
or
bus: `[0 input 8 7.1 surround(`
bus: `[0 output 8 7.1 surround(`

PS: VST3 uses canonical names that's why 6 channels is 5.1 surround.

**Comment by pierreguillot** [comment]
@alfonso73 @Lucarda @elsueno 
If you have time to check that. Does it sound good to you?
Thanks!

**Comment by alfonso73** [comment]
Sounds great to me!

**Comment by Lucarda** [comment]
Sounds great to me too. : )

**Comment by pierreguillot** [comment]
Thanks a lot!

**Comment by pierreguillot** [comment]
I will keep the functionality as "experimental" and the compatibility with the previous `bus`appraoch.

**Comment by alfonso73** [comment]
Ok. As soon as you have a version i'll start some patch for myself to learn
all the present Camomile feature. Including sidechain and multiple in/outs.
I guess it will be some sort of sample based drum machine (to test arrays)
accepting MIDI and audio in as triggering and modulation sources  (to test
sidechain)  and obviously some  individual outputs for every drum kit
piece. And a very simple internal step sequencer or step driven effect to
check vst time info stuff.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
It a simple syntax question but finally, I think it would be better to use `iolayout` for a buses layout (instead of `buses`). And now the plugin simply expects a set of pairs of numbers. So you can write something like `iolayout 2 2 | 2 0;` for a main bus with 2 input-output channels and a side-chain with 2 input channels. 

Doing the same with the "old" `bus` syntax gives:
```
bus 2 2;
bus 2 0;
```
So the result is now the same with:
```
iolayout 2 2 | 2 0;
```
And you can also do 
```
iolayout 2 2;
iolayout 2 0;
```
if you want two distinct configurations (no side-chain - only two distinct configurations for the main bus).

The old syntax with `bus` is preserved and this new syntax with `iolayout` will be marked **experimental** as I'm still not sure that this is the best approach.

**Comment by alfonso73** [comment]
That's great. I wonder if the VST3 format allows name for channels... if
yes would be great from a Daw user perspective.

Il sab 12 mag 2018, 14:36 Pierre Guillot <notifications@github.com> ha
scritto:

**Comment by pierreguillot** [comment]
> That's great. I wonder if the VST3 format allows name for channels...

Yes, that would be great ! Perhaps something like. But I'm not sure. 
```
iolayout 2 2 -name Main | 2 0 -name Side-Chaine;
```
I close this issue for v1.0.5. Feel free to create a new specific one for the naming and I'll add it to the project v1.0.6.

**Comment by alfonso73** [comment]
Cool! With multibus (1.0.6) and externals (1.0.7?) Camomile will be a
perfect tool for advanced sound design in a Daw enviroment!

Il sab 12 mag 2018, 14:43 Pierre Guillot <notifications@github.com> ha
scritto:
