### ISSUE TITLE
Camomile.so and CamomileFX.so are blacklisted by Ardour

### ISSUE THREAD

**Issue by bapch** [pierreguillot/Camomile#116]
Ardour 5.12
Ubuntu 18.04 64bits
Camomile 1.05

It is impossible to insert the Camomile plugin in a track, Ardour won't show it in the plugin list and will blacklist it :
$ cat .cache/ardour5/vst64_blacklist.txt 
/home/me/vst/Camomile.so
/home/me/vst/CamomileFX.so

As i was upgrading from an old version of Camomile, i've tried the method suggested here : https://community.ardour.org/node/15338

$ LD_LIBRARY_PATH=/opt/Ardour-5.12.0/lib/ /opt/Ardour-5.12.0/lib/ardour-vst-scanner -f /home/me/vst/Camomile.so
[ERROR]: Could not open existing LXVST plugin: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: g_output_stream_write_all_async
[WARNING]: Cannot get LinuxVST information from '/home/me/vst/Camomile.so': load failed.c

Carla 1.2.4 seems to load Camomile, but the GUI window is black and void.

**Comment by pierreguillot** [comment]
Thanks for the report! I removed libwebkit, can you compile the plugin (the branch dev/v1.0.6) and test it or do you want me to send you a pre-compiled version? 

PS: normally you shouldn't use Camomile.so and/or CamomileFx.so directly. You should use them  to generate the plugins (see the documentation).

**Comment by bapch** [comment]
I could use a pre-compiled version :) I've now set up the Almond Organ
plugin as per the wiki.
Thanks !

Le mer. 30 mai 2018 à 23:11, Pierre Guillot <notifications@github.com> a
écrit :

**Comment by pierreguillot** [comment]
Here is the [pre-release v1.0.6-beta1](https://github.com/pierreguillot/Camomile/releases/tag/v1.0.6-beta1).

**Comment by bapch** [comment]
I've been able to load AlmondOrgan, Bulgroz and Castafiore with the 1.0.6-beta1 you provided, so i guess it's solved :)

**Comment by pierreguillot** [comment]
Great! Can you tell me if the GUI problem with Carla is fixed?

**Comment by bapch** [comment]
So it appears that my bug report concerning Carla was incomplete. The plugin GUI actually shows up, but outside of its window and behind all other windows, which is why i didn't see it it the first place :
![capture d ecran de 2018-05-31 14-45-37](https://user-images.githubusercontent.com/10079348/40783055-92e18102-64e1-11e8-95fc-0dc0a5402c45.png)
The plugin window has "always on top" ticked. I have to untick it to be able to move the plugin GUI.

I can't move the GUI itself until i untick "always on top"

**Comment by pierreguillot** [comment]
Can you try the last beta release of Carla (v2-beta6 - 1.9.6)? On my side, with Carla v2-beta6 the plugin GUI is functional but I have to open it twice... If the problem persists, feel free to create a new specific issue. But perhaps this is due to Carla and not the plugin...

**Comment by bapch** [comment]
Unfortunately, both Carla binary and compiled version crash here, so i can't try.

**Comment by pierreguillot** [comment]
Alright so I close this issue for now.
