### ISSUE TITLE
High CPU Usage on large parameter count (Bitwig/VST)

### ISSUE THREAD

**Issue by seegwen** [pierreguillot/Camomile#121]
1. **High CPU Usage on large parameter count (Bitwig/VST)**. 
    > As I increase the number of parameters in the txt file, the CPU usage of my daw (Bitwig) goes nuts. At 128 parameters, it is at 80%.

2. **Environment**
    - **OS**: Mac OS El Capitan
    - **DAW**: Bitwig studio 2.3.4
    - **Plugin**: VST2 1.0.5
    - **Audio Rate**: 44100

3. **Is it expected behaviour ?**

**Comment by pierreguillot** [comment]
Indeed, it's high. Can you send the files to create the plugin? What do you do with the parameters? Perhaps you use one parameter (or more) for something that is very CPU intensive. 
From the [documentation](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#parameters):
> At each DSP tick, the plugin sends the current values of all parameters. 

so
>  to avoid repeated and unnecessary calculations, most uses require filtering the redundant values with the object [change].

Also, instead of using parameters if you don't need the value to be automatable or if you want to save/recall complex values, you can use extra data of the [programs](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#programs).

Let me know if it helps.
Cheers

**Comment by pierreguillot** [comment]
I tried on a Mac 10.13 with Reaper 64: the CPU of a VST2 plugin with 128 parameters  is around 2% (with the Debug binary, I guess the Release binary is more optimized). 

So the cause could be the one I explained before - you do something very CPU intensive in your patch with the parameters - or Bitwig doesn't manage well large count of parameters - in this case, you should try with other plugins and perhaps contact them.

**Comment by seegwen** [comment]
Hi Pierre,

Thx for your answer. Actually I really can't seem to find what I'm doing wrong computation-wise.
I'd like to send you the plugin, but I'd like to send it privately, maybe something will seem obvious to you. I'm sending it to your email address.

This patch receives CCs, and presents an GUI to control the DSI Evolver (HW synth) and works around a limitation of Bitwig by transforming the CCs and sending them to Pd patch by using netsend/netreceive. The Pd patch then transforms the received values to pure Sysex and out to the midi interface. It works really great, except for this high CPU usage that I don't understand the cause of.

I sent the patch to your (g) email adress.

**Comment by pierreguillot** [comment]
I will send you a suggestion for your patch on your email but as it can be interesting other people I try to reply in a generic way here. Perhaps that should even be in the documentation, in a section "How to manage with large number of parameters?".

### Analyse the patch
First of all, one good practice is to use a module in Pd that fakes the parameters' changes at each DSP tick. This way, you can more easily see if the patch will be CPU intensive or not. You can use an abstraction as this [param.fake.multi](https://github.com/pierreguillot/Camomile/files/2192023/param.fake.multi.pd.zip) patch where the first argument defined the number of parameters:

<img width="235" alt="param.fake.multi" src="https://user-images.githubusercontent.com/1409918/42683066-901d46f0-868c-11e8-8613-e694bad08595.png">

### The cause of the problem
So for each parameter you use an abstraction pretty similar to the [param.get](https://github.com/pierreguillot/Camomile/files/2191972/param.get.pd.zip) abstraction given with the examples:

<img width="124" alt="param.get" src="https://user-images.githubusercontent.com/1409918/42682429-dfacda66-868a-11e8-8950-41cb22fdd677.png">


This abstraction works for only one parameter but it receive all the parameters' messages and route the right value using the index given the first argument `[route $1]` (and then it sends the value to the `[outlet]` object or to a `[send]` object if a symbol is given for the second argument). So the "first part" of the abstraction (`[receive param] -> [route $1]`) will be triggered at each param message (that is receive at each DSP tick - every 64 samples). And if there are several abstractions, this will trigger the first part for all the abstraction at each DSP tick. And if there are a lot of these abstractions (corresponding to a large number of parameters), this can become pretty CPU intensive!

### Solution of the problem

This is one solution that should reduce the use of the CPU when a large number of parameter is used. It surely can be even more improved and it's surely not adapted to all approaches and needs but in this particular case it reduced by half the use of the CPU.

The idea is to reduce the number of times that the `[receive]` objects and the `[change]` objects are triggered by reducing the management of the parameters to one abstraction [param.get.multi](https://github.com/pierreguillot/Camomile/files/2192145/param.get.multi.pd.zip):

<img width="704" alt="param.get.multi" src="https://user-images.githubusercontent.com/1409918/42684996-13b17716-8692-11e8-9eff-42bb37d46507.png">

Let me know if it helps and if you suggestion to improve the abstraction.

**Comment by pierreguillot** [comment]
In fact, on my machine, it reduces the use of the CPU way more than the half! The patch that you sent me uses around ~13.2% of the CPU and now it's around ~2.2%!

**Comment by alfonso73** [comment]
@pierreguillot that's a brilliant solution! the only thing i don't understand is why you initialized the parameters array with a -999999999999...

**Comment by pierreguillot** [comment]
Fixed!
