### ISSUE TITLE
README does not mention LV2 support

### ISSUE THREAD

**Issue by falkTX** [pierreguillot/Camomile#125]
Basically the title.
Latest official release has LV2 support, you should brag about it :)

**Comment by pierreguillot** [comment]
I just add lv2 in the key words but LV2 support is already mentioned in the README in the [presentation section](https://github.com/pierreguillot/Camomile/blob/master/README.md#presentation) and the [credits section](https://github.com/pierreguillot/Camomile/blob/master/README.md#credits). 
Do you think I should change the line just below the [title](https://github.com/pierreguillot/Camomile/blob/master/README.md#camomile)? 
I guess I should rewrite the presentation too...

**Comment by falkTX** [comment]
seems all fine now, sorry for delay on checking this.
and thanks!
