### ISSUE TITLE
Improve dynamic patching support

### ISSUE THREAD

**Issue by seegwen** [pierreguillot/Camomile#128]
My use case is as follows:
I use a number box to update a plugin's parameter
This parameter is a list defined in the plugin's txt (1-4/1-3/1-2/...)
I want to display the values of the list according to the selected number from the number box.
What I usually do within Pd is put a cnv object right in front of the number box.

With this layout, the mouse events are captured not by the cnv object but by the number box underneath, and whenever I update the label of the cnv, it shows correctly. In Camomile, the mouse events are correctly passed to the number box underneath, that's definitely what I intend.
But in Camomile, if I update the cnv's label, nothing is displayed until I update the plugin's gui via
[;
camomile gui redraw;(
but then, the mouse focus is lost, that is, I can only change the value of the number box once, and then I have to click again on the number box/cnv to change the value again.

So my request is: is it possible to update a cnv's label without needing to redraw the gui ?
Same thing for the other objects's labels, though I don't have a use case for them.

**Comment by pierreguillot** [comment]
For the moment, if you use `[gui redraw(` the GUIs are deleted and recreated. But, indeed, it would be great to only redraw the GUIs without the delete/creation part that loose the focus. And perhaps we could also use facultative coordinates to define which part of the interface to redraw.

**Comment by korakios** [comment]
Glad I saw it. I though I was doing something wrong. I put a metro object to update the gui every 1 sec but it interrupts the slider movement. 
Is there any workaround? Labels are handy because I can feed them with symbols and floats, plus they can be resized etc....

**Comment by pierreguillot** [comment]
This is fixed on dev/v1.0.7.
