### ISSUE TITLE
Canvas colors won't change

### ISSUE THREAD

**Issue by insignificantother** [pierreguillot/Camomile#132]
Hey there,

I'm trying to create a simple keyboard display as part of the interface that lets users know the midi note they are pressing and what the range of the instrument is. Each note corresponds to a canvas that changes color temporarily when the corresponding key is pressed. It looks as if the canvases won't take messages in the plugin environment.

Also thanks for you wonderful work here.

**Comment by ezequielabregu** [comment]
Hi. Maybe... you have to use  [gui redraw(  message when some key is pressed.

**Comment by pierreguillot** [comment]
Closed due to inactivity, feel free to reopen the issue if necessary.

**Comment by J-Ginkgo** [comment]
Hi,
I would like to reopen it, as I have the same problem and it doesn't work. Also not with gui redraw. I want to resemblance a keyboard where the keys change colours when pressing the midi note. This is how I do it.
![unbenannt](https://user-images.githubusercontent.com/44024742/49283274-a0340880-f491-11e8-88fd-e2a2305509bc.jpg)

Its an abstraction. The canvas appears on the plugins canvas. 
In the plugin it appears just white, without any colour.

Do you have any suggestions?

**Comment by insignificantother** [comment]
I was trying to do something similar to what you're trying to do with the keyboard. I just ended up placing the canvases on the main patch and just using a subpatch or abstraction for the routing. I can send you the patch so you can look at it if you want.

**Comment by J-Ginkgo** [comment]
Yes thats the solution I came up with as well. So no need for the patch, thank you :) I just thought I should write it here because maybe it should be possible and it's a bug. Even though it's fine to work around.

**Comment by pierreguillot** [comment]
I working on it, this will be related to this issue https://github.com/pierreguillot/Camomile/issues/128 so I close this one.
