### ISSUE TITLE
midiin and midiout don't work

### ISSUE THREAD

**Issue by nofrets** [pierreguillot/Camomile#134]
thanks for a great tool. 

tested on:
macos 10.12.6, 2.8 GHz Intel Core i7
waveform 9
vst and vst3
44100 Hz 256 samples

created 2 patches to test via PdStalFx
-test1.pd is simple `midiin=midiout`
-test2.pd tests `notein=noteout`, `midiin`, and sysex message to `midiout`

loaded the patch into PdStalFx in a waveform track and played notes:
test1.pd:
-`midiin` does not register bangs. no `midiout`.
test2.pd:
-`notein` works
-`midiin` doesn't work again
-sysex note on message `[144, 60, 100(` to midout results in an empty note message.

here are the pd files. Tried to share project file but pdStalFx only does absolute file references. 

[tests_pd.zip](https://github.com/pierreguillot/Camomile/files/2349725/tests_pd.zip)

Thanks again for your time and effort!

**Comment by pierreguillot** [comment]
I’ll have a look ASAP

**Comment by pierreguillot** [comment]
I fixed it. Can you test it and tell me if it's good for you too ?
[CamomileMacOS.zip v1.0.7-beta1](https://github.com/pierreguillot/Camomile/files/2364503/CamomileMacOS.zip)

**Comment by nofrets** [comment]
Thanks so much for the quick work.

`midiin` seems to work now, but it is difficult to tell for sure as `midiout` still has issues for me.

`midiout` sends a note-on and note-off, but only note 127 with a velocity of 1 every time.

sysex messages seem to have no effect.

Thanks again!

**Comment by pierreguillot** [comment]
Thanks for your feedback. I'll try to check that this week and fix it this week-end.

**Comment by pierreguillot** [comment]
I think I fixed the midiout, can you test this beta version? 
[CamomileMacOS.zip v1.0.7-beta2](https://github.com/pierreguillot/Camomile/files/2386924/CamomileMacOS.zip)
I never used `[sysex]` I'll have to do further investigation. If you can give me a hint or if you have any idea idea of what going on it would be much appreciated :)
Cheers

**Comment by nofrets** [comment]
I tested using PdStal.vst and this patch:

[test.pd.zip](https://github.com/pierreguillot/Camomile/files/2402181/test.pd.zip)

I attached two instances of the PdStal vst with this patch loaded in waveform. The Camomile console prints messages from `[midiin]` and `[sysexin]`.

`[midiin]` and `[midiout]` seem to work great.

I did some [sysex](https://www.midi.org/specifications-old/item/table-4-universal-system-exclusive-messages) [retuning](http://www.microtonal-synthesis.com/MIDItuning.html) tests and found it to be semi-functional. Some messages work, but it seems that others are being truncated.

-note-on `[144, 56, 100 (` and note-off `[128, 56, 0(`  messages work.

-longer messages like realtime MTS `[240, 127, 127, 8, 2, 0, 1, 56, 56, 121, 40(` get truncated to `240, 127, 127, 0` when I look at the console messages in the second instance of the vst wrapper:

<img width="89" alt="screen shot 2018-09-20 at 9 36 12 am" src="https://user-images.githubusercontent.com/42974685/45833103-a8fda680-bcb8-11e8-9bb2-73017d5736a6.png">

I think I read about this happening somewhere in the pd-vanilla forums from back in the day but I couldn't find it.

I hope this helps and thanks again for your time!

**Comment by pierreguillot** [comment]
Thanks for the documentation. After further investigation, I understood that SysEx messages must start with F0 (240) and end with F7 (247). So your list should ends with 247: `[240 127 127 8 2 0 1 56 56 121 40 247(` (and commas are optional). 

Using this syntax, the plugin well receives a SysEx message (I send the message from Pd to my DAW - Reaper - using a virtual MIDI buse).

The problem was to output sysex messages via the plugin using the `[midiout]` object. Now, when the plugin receives MIDI bytes from the patch, it checks the SysEx start and end bytes and it creates a SysEx message if the bytes match. Perhaps, I should implement a more generic approach but I think it works so I'll keep this like that for the moment. 


Can you test with this beta release and tell me if everything's working?
[CamomileMacOS - v1.0.7-beta4](https://github.com/pierreguillot/Camomile/files/2407667/CamomileMacOS.zip)

Thanks a lot for your help!

**Comment by nofrets** [comment]
Great thanks for pointing out my typo. I copied the code from a different patch and clearly it was me doing the truncating!

I haven't tested extensively but so far the PdStal.vst works great, no complaints.

This is great for those wanting to slap together quick vst plugins and share them with others without the barrier of expensive proprietary software or technical knowledge, bravo.

I'm looking forward to future developments (like externals :)

Thanks again for your hard work!
