### ISSUE TITLE
expr and expr~ objects not working on Windows 

### ISSUE THREAD

**Issue by LouFanhGit** [pierreguillot/Camomile#139]
I am working on Windows 10 and Cubase 9.5 64bit, trying to create a 64bit VST Plugin from a PD patch I made. Sample rate = 44.1kHz, blocksize 64 (512 in subpatch). Camomile version 1.0.6, PD version 0.48.1

Problem description: when creating expr~ objects in a PD patch that is run by Camomile, a syntax error is being thrown. Apparently expr~ is an external (which I was not aware of and I was unable to find proof for) which would explain Camomile not being able to parse it. In case these assumptions are true, is there any possibility to do audio-rate higher maths?

Background: I have written a FFT spectral morphing patch in PD which heavily relies on the use of expr~ modules (for cartesian to polar conversion as well as the actual crossfading of the time-frequency bins). Although I could probably rephrase most of it in terms of PD Vanilla audio math objects, though a remaining problem is the atan2 function which does not have an audio equivalent in PD Vanilla and is extremely important for the cartesian to polar coordinate conversion.

(Disclaimer: I am new to GitHub and its architecture and do not know if this is the right place to put these questions. If this is infact not the right place, I apologise.)

**Comment by pierreguillot** [comment]
The [expr~] object is not a native object however it's distributed with Pd Vanilla and Camomile as an extra object. I just tested to use it by copying some of the examples from the help file and it works well. I can do more tests on Windows machine later but perhaps there is another problem? What is the syntax error being thrown? Can you share your patch or the subset of your patch that generates the problem? 

And feel free to ask question here.

**Comment by pierreguillot** [comment]
@LouFanhGit ?

**Comment by porres** [comment]
> The [expr~] object is not a native object 

it's actually native now, not an extra external anymore

**Comment by AndreasNiegl** [comment]
Hi I'm having a similar problem and just wanted to ask if this is confirmed to be a persistent bug & yet unfixed.
This is the error i'm getting: "expr synthax error: an open bracket not matched"
(specifically I'm using the fexpr~ object)

I am using reaper as my DAW on Windows.

I'd really love to use fexpr~ for advanced filter effects. :3

Otherwise I'm super impressed by this project! Thank you!

**Comment by pierreguillot** [comment]
Yes, this is still unfixed.

**Comment by pierreguillot** [comment]
This is fixed on dev/v1.0.7. It will be released soon, in the meantime, you should be able to test it using the artefacts on [Appveyor](https://ci.appveyor.com/project/pierreguillot/camomile/builds/34598526).
