### ISSUE TITLE
 Camomile Windows 10  tutorial and design help

### ISSUE THREAD

**Issue by AlecMcCutcheon** [pierreguillot/Camomile#143]
been wanting to make a plugin that randomly changes a noise gate's sensitivity with a way of changing the speed in which it does so, been playing around with Spiritboxs and am trying to use something like adobe auditions to filter it, I was told that Pure Data would be a Great little software to make this in and while, I kind of made it, its only a .pd and I have no idea how to make it into a Plugin been trying to read over the Camomile Doc's but there just seems to be a lack of tutorials for Windows 10 operating systems and it seems to me like all the information is extremely abstract or maybe I'm just really dumb either way I really know nothing about programming  and would love it if somebody could simplify the process, another thing I can't figure out is the text documents and all of the other files that are in the folders of the example plugins, how do you make all the extra files from just a .pd, again though sorry to burden everybody who actually knows what they're doing lol. it would be sweet if somebody could make a video tutorial In Windows OS, starting from a Pure data project .pd file and going, step by step into making it into a plugin

**Comment by pierreguillot** [comment]
I close this issue due to lack of activity.
