### ISSUE TITLE
plugin not work on linux in reaper 

### ISSUE THREAD

**Issue by artofmus** [pierreguillot/Camomile#146]
Hello! I download the archive from the release page, unpacked it into a folder with vst plugins,  Camomile opens but writes "Plugin not valid" in console write : "camomile can't find the configuration file "/home/art/VST/Camomile/Camomile.txt" 
what could be the problem? Thanks.

**Comment by pierreguillot** [comment]
Hello,
This is not an issue, you should read this: https://github.com/pierreguillot/Camomile/wiki/How-to-generate-plugins
And here are similar questions:
https://github.com/pierreguillot/Camomile/issues/129
https://github.com/pierreguillot/Camomile/issues/81

**Comment by artofmus** [comment]
Thanks!

**Comment by quique333** [comment]
Hello. Ive just downloaded the archive and generated the vast with the terminal command. The plugin was created but I got an error when I open in reaper "no graphical user interface available". can you please help. Thanks

**Comment by pierreguillot** [comment]
Hello,
Please give further information. Which plugin? What are the messages in the console? Etc.

**Comment by quique333** [comment]
Hello. this is the plugin i created. just a simple oscilator in pd.

[oscil.vst3.zip](https://github.com/pierreguillot/Camomile/files/3282825/oscil.vst3.zip)

thanks

**Comment by pierreguillot** [comment]
If you want to show GUI objects, you have to enable the graph-on-parent like for the examples. I didn't finalize this part of the documentation yet but there is already information about the GUI on the Wiki and on other issues. And you can read this paper for a general presentation: http://lac.linuxaudio.org/2018/pdf/44-paper.pdf  
Anyway, I think you are on MacOS, not on Linux, please use another issue.
