### ISSUE TITLE
some clarification sorry(

### ISSUE THREAD

**Issue by artofmus** [pierreguillot/Camomile#147]
Correctly, I understand that now i can not edit patches in daw? i can only compile patches made in PD?

**Comment by pierreguillot** [comment]
No it never was possible to edit the patch directly from the DAW. Perhaps someday I hope :) But there is the [autoreload](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#dynamic-Reload) option that enables the automatic reloading of the patch each time you change it. And there is also the PdStal example that can be used to prototype the plugin: https://vimeo.com/album/4639971/video/279991885.
