### ISSUE TITLE
Problem compiling Camomile on OSX   Could NOT find Threads (missing: Threads_FOUND)

### ISSUE THREAD

**Issue by theslyprofessor** [pierreguillot/Camomile#148]
I'm trying to compile LibPD and I am receiving a CMake error message. I have scourged the net for solutions dealing with this problem on Mac, but have found none that are from the past 10 years. I am receiving this error on both my MacBook Pro and my Mac tower desktop. :

I type:

`cmake .. -GXcode`

I get:

```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.13/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:317 (find_package)

```

Thanks for the help!

**Comment by pierreguillot** [comment]
Yes, the last version of XCode is not compatible anymore. You should use the dev branch: https://github.com/pierreguillot/Camomile/tree/dev/v1.0.7

**Comment by pierreguillot** [comment]
Close due to lack of activity.
