### ISSUE TITLE
MIDI only plugin bug in Cubase 9.5

### ISSUE THREAD

**Issue by brightmind3** [pierreguillot/Camomile#149]
When using MIDI only instrument plugin (VST2 - v1.0.6) in Cubase 9.5 64 bit on Windows 10 and I change the audio buffer size in any way (sample rate is 48 kHz) I get a high pitched noise with very high level from the plugin that clips the output. I need to remove the plugin or close Cubase to stop it.

This happens with two different patches both of witch get MIDI notes in, map their velocity to a CC message value, and output both the notes and the CC messages.

If I set midionly to 'false' the problem is solved.

**Comment by pierreguillot** [comment]
Hello, if the problem happens only with MIDI plugins only as internally the MIDI doesn't interfere with audio perhaps there is something wrong with the way the MIDI notes are managed?  When the buffer size or the sample rate changes, you should receive a "dsp" message (with the value 1 or 0) and you can use it to clear and/or reset the MIDI objects, the generators phases and the buffer. Can you try it? And if the problem persists, can you share a patch?

**Comment by pierreguillot** [comment]
The VST plugin has been removed (because it is not supported anymore by Steinberg). The VST3 plugins require at least 1 audio channel even for MIDI only plugins otherwise you don't receive the sample rate and the sample advancement, it seems that there is no other solution for that. Anyway, I guess this problem is not relevant anymore.

**Comment by Drugo23** [comment]
I think It would be useful to mention that in the wiki section - how to create plugins. Thanks

**Comment by pierreguillot** [comment]
It seems that you really don't want to create a discussion :( but feel free to do add this in the wiki...
