### ISSUE TITLE
Can't send MIDI CC messages out with VST3 plugin

### ISSUE THREAD

**Issue by brightmind3** [pierreguillot/Camomile#150]
I've created two different patches both of witch get MIDI notes in, map their velocity to a CC message value, and output both the notes and the CC messages. However, when using the VST3 - v1.0.6 plugin the CC messages are not being send out. Tested in Reaper 5 64 bit and Cubase 9.5 64 bit on Windows 7 and 10. The same patches work when using the VST2 - v1.0.6 plugin.

**Comment by Spacechild1** [comment]
outgoing CC messages have been added to the VST3 SDK, but maybe JUCE doesn't implement it yet?

**Comment by pierreguillot** [comment]
Alright, we should if there something about it on the Juce project. If so, we’ll only to update Juce. That’s not a big issue I did that recently to test the unity support ;)

**Comment by pierreguillot** [comment]
I tested it with Juce 6 and it works. It will be included in the next release and it's already available on dev/v1.0.7.
