### ISSUE TITLE
UI Element label positions change when plugin is loaded

### ISSUE THREAD

**Issue by barnabywalters** [pierreguillot/Camomile#151]
Mac OS 10.14.1
Pd v0.48.1, v0.49.0
DAW: Logic Pro X, also happens in Audacity
Plugin format: AudioUnit
Camomile v1.0.6

When I load a plugin created with Camomile in a DAW (Logic Pro X, Audacity), the labels of Puredata’s GUI elements (e.g. Number field, Canvas, Toggle) are offset differently to how they are when the UI patch is opened in Puredata.

For example, I have to offset the labels for the header canvas and the the UI elements in the “Transposition” section like this in Puredata:

<img width="523" alt="Screenshot 2019-05-16 at 10 07 04" src="https://user-images.githubusercontent.com/968350/57837701-9b56dd00-77c3-11e9-8bb5-7ddf3cfbf503.png">

…so that they end up in the right place in Logic:

<img width="548" alt="Screenshot 2019-05-16 at 10 06 35" src="https://user-images.githubusercontent.com/968350/57837722-a3af1800-77c3-11e9-881c-25c04baf6ad4.png">

**Comment by pierreguillot** [comment]
Yes, I noticed. I started to fix it but this part is a bit tricky...

**Comment by korakios** [comment]
I had to change the Margin of the canvas to "1" and labels are now shown correctly.
But I have no clue why (I don't even know what 'Margin' is used for)

**Comment by pierreguillot** [comment]
Perhaps this could help:
<img width="337" alt="Capture d’écran 2019-06-18 à 18 43 16" src="https://user-images.githubusercontent.com/1409918/59702860-f9c70f00-91f8-11e9-9b10-134b0414a9ae.png">

**Comment by korakios** [comment]
Although I understand the schematic,I think I should find some patches to see how margin interacts with the objects :)

**Comment by pierreguillot** [comment]
This should be fixed on dev/v1.0.7
