### ISSUE TITLE
Plugins are filed under Manufacturer “Pierre Guillot” in Logic Pro X

### ISSUE THREAD

**Issue by barnabywalters** [pierreguillot/Camomile#152]
Mac OS 10.14.1
Pd v0.48.1, v0.49.0
DAW: Logic Pro X
Plugin format: AudioUnit
Camomile v1.0.6

Logic Pro X organises plugins according to Type then Manufacturer, and for plugins generated by Camomile, the manufacturer is always “Pierre Guillot”. Of course I’m happy to give credit to @pierreguillot for their amazing work on this project, but it would be really useful to be able to change this!

<img width="779" alt="Screenshot 2019-05-15 at 21 41 50" src="https://user-images.githubusercontent.com/968350/57838166-7a42bc00-77c4-11e9-815f-fb9519db099c.png">

I already looked in the plist file inside the AudioUnit .component bundle and tried changing some of the keys, but couldn’t find anything which changed the Manufacturer setting.

**Comment by pierreguillot** [comment]
We can add a "manufacturer" entry for this.

**Comment by barnabywalters** [comment]
That would be great!

**Comment by pierreguillot** [comment]
I'm working on it. It seems to work fine! I will send you a beta version soon to test it.
