### ISSUE TITLE
Parameter editing view doesn’t work in Logic Pro X

### ISSUE THREAD

**Issue by barnabywalters** [pierreguillot/Camomile#153]
Mac OS 10.14.1
Pd v0.48.1, v0.49.0
DAW: Logic Pro X
Plugin format: AudioUnit
Camomile v1.0.6

This is not a major issue, as a custom Puredata interface is usually going to be the best way to control any given plugin, but: in Logic Pro X, when switching the plugin “Editor” to Parameter view, parameters are listed correctly, but their values are empty.

This parameter configuration:

````
param -name Voices -min 2 -max 4 -default 4 -nsteps 3;
param -name Dry -label dB -min 0 -max 100 -default 100;
param -name Wet -label dB -min 0 -max 100 -default 100;
param -name MIDI Channel -min 1 -max 16 -nsteps 16 -default 1;
param -name Determine Pitch -list From MIDI/Set -default 0;
param -name Set Pitch -min 60 -max 71 -default 60 -nsteps 12;
param -name Temperament -list 12TET/5 limit/7 limit/pythagorean/quarter comma meantone -default 0;
param -name Transpose Semitones -min -24 -max 24 -default 0 -nsteps 49;
param -name Transpose Octaves -min -2 -max 2 -default 0 -nsteps 5;
````

…results in the following UI:

<img width="407" alt="Screenshot 2019-05-16 at 10 24 41" src="https://user-images.githubusercontent.com/968350/57838599-4caa4280-77c5-11e9-97be-b6ad5c5692e1.png">

When I click the boxes, some offer drop down menus with usually the wrong number of empty options.

**Comment by pierreguillot** [comment]
I don't have Logic so I can't test it... can you try in Reaper for example ? This way I  can be sure there's no problem with the plugin in general but with the Logic compatibility. Perhaps I made a mistake with the AU...

**Comment by barnabywalters** [comment]
It looks like it’s a Logic compatibility issue rather than an issue with the AudioUnit, as the barebones UI works in both Audacity and Reaper.

I’m no C++ developer, but let me know if there’s anything I can do to help debug this.

<img width="618" alt="Screenshot 2019-05-16 at 20 18 20" src="https://user-images.githubusercontent.com/968350/57877337-de42a000-7817-11e9-9563-0c6015f5d218.png">
<img width="550" alt="Screenshot 2019-05-16 at 20 15 23" src="https://user-images.githubusercontent.com/968350/57877345-e39fea80-7817-11e9-9484-9270186803e5.png">

**Comment by pierreguillot** [comment]
I found the problem. This is fixed and will be integrated in the next release!
