### ISSUE TITLE
Netsend not working

### ISSUE THREAD

**Issue by korakios** [pierreguillot/Camomile#154]
On a PD patch using netsend prints
`socket: Unknown error (10093)`

It's happening when I try to connect to local network, or locahost. On PD any port is opened fine and works.
I hope it's a configuration mistake. I used the following parameters:

```
type effect;
midiin true;
midiout true;
midionly false;
playhead true;
compatibility 1.0.6;
```
Win10, Reaper 5.979, PureData 0.49. 64bits

Any tips?

**Comment by korakios** [comment]
If it’s a configuration issue ,could someone point me to the right direction?
I could provide more if needed, unless it’s camomile restriction and will wait for an update :)

**Comment by korakios** [comment]
Should I close the issue ?

**Comment by pierreguillot** [comment]
I didn’t have the time to test yet and I have no idea why it is happening. If is it solved, feel free to close the issue. If not, please keep it opened.

**Comment by eliottparis** [comment]
Just to provide some additional information here that could be helpful for further investigations on this:

From the [Winsock Error Descriptions](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2):

> WSANOTINITIALISED (10093) Successful WSASTARTUP not yet performed
>
> Either the application has not called `WSAStartup` or `WSAStartup` failed. The application may be accessing a socket that the current active task does not own (that is, trying to share a socket between tasks), or `WSACleanup` has been called too many times.

maybe also related to this [Pd issue](https://lists.puredata.info/pipermail/pd-dev/2018-08/021634.html).

**Comment by pierreguillot** [comment]
Pd has been updated on the dev branch, so perhaps the problem is fixed on this branch?
Here is the 64bit binary for Windows [CamomileWindows64.zip](https://ci.appveyor.com/api/buildjobs/tptnolyrwfntfr25/artifacts/CamomileWindows64.zip) (note that this is a dev version).
@korakios can you test it and tell us if the problem is solved?

**Comment by korakios** [comment]
Currently I don’t have my laptop with me ,but will test it as soon as possible .
I can test it on Linux too if you wish

**Comment by korakios** [comment]
Unfortunately it doesn't work. I get
`Camomile 1.0.6 for Pd 0.50.2
camomile compatibility not defined.
netreceive: bad host or port? Either the application has not called WSAStartup, or WSAStartup failed.  (10093)
netsend: bad host or port? Either the application has not called WSAStartup, or WSAStartup failed.  (10093)
`
on reaper 6.12

I used the CamomileFx.vst3 (didn't find a vst2 dll on the linked zip). Is there a flag that I miss? I copied/pasted and used

code zUrt;
type effect;
midiin true;
midiout true;
midionly false;
playhead true;
compatibility 1.0.6;

**Comment by Lucarda** [comment]
My 2 cents:

Looks that `WSAStartup` is not used in **libpd**. So none of the net objects could work with **libpd** on Windows.

**Comment by Lucarda** [comment]
Also whenever using/starting the Windows sockets with `WSAStartup`, the project has to link with compiler flag: `-lws2_32`

**Comment by korakios** [comment]
At least on Linux it works ok (just tested it)

**Comment by pierreguillot** [comment]
@Lucarda Thank you! I will try to see how to implement it.
@korakios So the problem is Windows only. Thanks!

**Comment by pierreguillot** [comment]
I did a [fix](https://github.com/pierreguillot/Camomile/tree/dev/fix-netsend) but I can't test on Windows can you try it? [CamomileWindows64.zip](https://ci.appveyor.com/api/buildjobs/i1gh71id2d2ekg7k/artifacts/CamomileWindows64.zip)

**Comment by Lucarda** [comment]
@pierreguillot it works Ok for me on VSThost.
I couldn't test on Ableton because in the test pkg there are only VST3 binaries. I think Live9 does not support VST3?

**Comment by Lucarda** [comment]
![net-camomile](https://user-images.githubusercontent.com/25239522/86488529-aeb26800-bd37-11ea-8cfc-e33695fcd107.png)

**Comment by Lucarda** [comment]
>  I think Live9 does not support VST3?

It does not support VST3:
https://help.ableton.com/hc/en-us/articles/209769405-Supported-Plug-in-formats

**Comment by pierreguillot** [comment]
@Lucarda Thank you!
I managed to test on Windows with Reaper and it worked. I will merge the change in v1.0.7 and close the issue :)

**Comment by Lucarda** [comment]
:)

**Comment by korakios** [comment]
Thank you :)
