### ISSUE TITLE
Logic X refusing to validate Camomile as an Audio Unit.

### ISSUE THREAD

**Issue by AM0984** [pierreguillot/Camomile#155]
Logic X refusing to validate Camomile as an Audio Unit. Plugin manager fails the validation and Logic crashes if I try to force it.
      
OS - Mojave 10.14
DAW - Logic X 10.4 64 Bit        
Plugin - AU v1.0.6

**Comment by pierreguillot** [comment]
Did you read the [wiki](https://github.com/pierreguillot/Camomile/wiki/How-to-generate-plugins)? And can you give further information? What plugin? What configuration?

**Comment by pierreguillot** [comment]
Close due to lack of activity.
