### ISSUE TITLE
camomile plugin generator script error

### ISSUE THREAD

**Issue by theslyprofessor** [pierreguillot/Camomile#156]
When I run the camomile plugin generator script, I get these errors, when running camomile 1.06 and 1.07 on OS X High Sierra:

Camomile.vst is not available
./camomile: line 320: [: too many arguments
Camomile.vst3 is not available
./camomile: line 271: [: too many arguments
Camomile.component is not available
./camomile: line 190: [: too many arguments
CamomileLV2.dylib is not available
./camomile: line 365: [: too many arguments
CamomileFx.vst is not available
./camomile: line 320: [: too many arguments
CamomileFx.vst3 is not available
./camomile: line 271: [: too many arguments
CamomileFx.component is not available
./camomile: line 190: [: too many arguments
CamomileLV2.dylib is not available
./camomile: line 365: [: too many arguments
CamomileFx.vst is not available
./camomile: line 320: [: too many arguments
CamomileFx.vst3 is not available
./camomile: line 271: [: too many arguments
CamomileFx.component is not available
./camomile: line 190: [: too many arguments
CamomileLV2.dylib is not available
./camomile: line 365: [: too many arguments
Camomile.vst is not available
./camomile: line 320: [: too many arguments
Camomile.vst3 is not available
./camomile: line 271: [: too many arguments
Camomile.component is not available
./camomile: line 190: [: too many arguments
CamomileLV2.dylib is not available
./camomile: line 365: [: too many arguments
CamomileFx.vst is not available
./camomile: line 320: [: too many arguments
CamomileFx.vst3 is not available
./camomile: line 271: [: too many arguments
CamomileFx.component is not available
./camomile: line 190: [: too many arguments
CamomileLV2.dylib is not available
nakul:Plugins nakultiruviluamala$

**Comment by pierreguillot** [comment]
What did you download ? What did you do to run the script ? Can you give further information ?

**Comment by pierreguillot** [comment]
I think you downloaded the code project not the distribution from the download page so I close the issue but feel free to reopen it if this is another problem.

**Comment by theslyprofessor** [comment]
Hi, sorry for taking a while to respond to this. I downloaded the latest stable release from the download page (https://github.com/pierreguillot/Camomile/releases/tag/v1.0.6) and I am receiving this error still: 

nakul:Camomile nakultiruviluamala$ ./camomile
Camomile - Plugin Generator
./camomile: line 365: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
Camomile.vst is not available
./camomile: line 320: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
Camomile.vst3 is not available
./camomile: line 271: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
Camomile.component is not available
./camomile: line 190: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileLV2.dylib is not available
./camomile: line 365: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.vst is not available
./camomile: line 320: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.vst3 is not available
./camomile: line 271: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.component is not available
./camomile: line 190: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileLV2.dylib is not available
./camomile: line 365: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.vst is not available
./camomile: line 320: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.vst3 is not available
./camomile: line 271: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.component is not available
./camomile: line 190: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileLV2.dylib is not available
./camomile: line 365: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
Camomile.vst is not available
./camomile: line 320: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
Camomile.vst3 is not available
./camomile: line 271: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
Camomile.component is not available
./camomile: line 190: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileLV2.dylib is not available
./camomile: line 365: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.vst is not available
./camomile: line 320: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.vst3 is not available
./camomile: line 271: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileFx.component is not available
./camomile: line 190: [: /Users/nakultiruviluamala/Library/Mobile: binary operator expected
CamomileLV2.dylib is not available

**Comment by theslyprofessor** [comment]
I figured it out. It doesn't like compiling on iCloud because there is a space in the path (Mobile Documents). When I put it in my local folder it generated the plug-ins just fine.

**Comment by pierreguillot** [comment]
Ok. This is related to https://github.com/pierreguillot/Camomile/issues/136.
