### ISSUE TITLE
lv2_file_generator not being built and moved to Plugins

### ISSUE THREAD

**Issue by muziker** [pierreguillot/Camomile#158]
The lv2_file_generator isn't being built and shifted to the Plugins directory. Hence building the example plugins generates an error about not finding *ttl files.
         
2. **Describe your environment**
 It's a linux !

3. **Describe the problem or the feature request**
to solve, the user must cd into the LV2 directory and locate the lv2_file_generator makefile and make it directly

**Comment by pierreguillot** [comment]
Indeed, lv2_file_generator must be compiled separately. See the Travis CI: https://github.com/pierreguillot/Camomile/blob/master/.travis.yml#L27

The Readme instruction must be updated

**Comment by patricksebastien** [comment]
Did that but when trying to compile the plugins (example), I get:
`generating ttl PdStalFx in ./builds/PdStalFx.lv2/PdStalFx.so
Writing manifest.ttl... done!
Writing PdStalFx.ttl... done!
can't load methods lv2_generate_ttl`

My goal is to run a pd patch (VST) inside Bitwig on linux.

**Comment by theotherjenkutler** [comment]
I'm having the same problem in OSX 10.11.6. I compiled the lv2_file_generator separately and now I'm getting this error:

./camomile: line 177: 12334 Segmentation fault: 11  $ThisPath/lv2_file_generator $plugin_output_dir/$plugin_name.lv2/$plugin_name.$AppleLV2Extension $plugin_name > /dev/null
mv: rename /Volumes/NO_NAME/Camomile/Plugins/manifest.ttl to ./builds/earth.lv2/manifest.ttl: No such file or directory
mv: rename /Volumes/NO_NAME/Camomile/Plugins/earth.ttl to ./builds/earth.lv2/earth.ttl: No such file or directory

**Comment by muziker** [comment]
Hey, i posted the solution together with the request  ...

**Describe the problem or the feature request**
to solve, the user must cd into the LV2 directory and locate the lv2_file_generator makefile and make it directly
