### ISSUE TITLE
AlmondOrgan lv2 doesn't resize screen properly, cannot see all the controls

### ISSUE THREAD

**Issue by muziker** [pierreguillot/Camomile#159]
1. **Please provide an explicit title to the issue**. 
      Having built the example AlmondOrgan LV2, insert it as a plugin into Carla, the AlmondOrgan screen ui opens, but it is non resizable and the view port is too small. So all the controls cannot be seen
   
2. **Describe your environment**
   it's linux !

**Comment by pierreguillot** [comment]
Do you have the same problem with Ardour and/or Reaper? I don't remember having this problem with these DAW. I'll try on Carla 2.0.0 on macOS today and if there's no problem I'll try on Linux later when I'll have a Linux machine. If you could test on your side, it would be great.

**Comment by muziker** [comment]
In ardour the gui is sized correctly. On carla, not so much.

**Comment by muziker** [comment]
Also, i've a two monitor setup with different resolutions. When i double click the plugin icon in a mixing strip on ardour, it appears as one resolution. Subsequent clicks on the plugin icon, and the resolution changes. Also for some reason, there isn't any audio from the plugin. Yesterday, i redid the entire camomile build, and there was a message, after i ran ./camomile -f <file> -o <file>, and it says "can't load methods lv2_generate_ttl".

**Comment by muziker** [comment]
In ardour, in a channel strip, there usually is a midi input connector symbol right at the top of a plugin button. In almondorgan's case, there isn't any. In other's like the calf organ, a little red connector and a line thread can be seen.

**Comment by pierreguillot** [comment]
Ok, I'll have to investigate these problems. In the meantime, if there is a linux carla/ardour guru in the area that could help for this it would be great.

**Comment by pierreguillot** [comment]
I tried with Carla on Mac but I can load only one type of plugin per session and I don't have audio... Anyway, the screen size is ok for me. Can you share a screenshot? And I have midi connectors I think.

**Comment by pierreguillot** [comment]
I did more tests and indeed, the default GUI of plugin generated by Carla doesn't show all the parameters. I tested with other plugins and that the same for all. I guess this a problem with Carla and not Camomile. You should contact their devs directly.
