### ISSUE TITLE
LV2 plugin does not receive midi inputs

### ISSUE THREAD

**Issue by muziker** [pierreguillot/Camomile#160]
1. **Please provide an explicit title to the issue**. 
      AlmondOrgan.lv2 does not receive Midi inputs in Ardour
         .
2. **Describe your environment**
    It's linux! specifically a 64bit one      
 
In the midi strip, adding the almondorgan.lv2 version, the plugin does not seem to be connected to the ardour's midi control in. To see this, open up the mixer and look at the channel strip. There is a connector line in working plugins that shows ardour's selected midi input is connected to the plugin. This isn't there.

**Comment by pierreguillot** [comment]
I downloaded Ardour on my Mac but this version doesn’t support LV2. I’ll try on a Linux computer but I’m not a LV2 expert. It’s possible that I made a mistake or I forgot something...

**Comment by trebmuh** [comment]
Confirming that the LV2 version of AlmondOrgan and MiniMock doesn't have MIDI input. That makes them unusable.

See the screenshot in Catia, using jalv 1.6.0 for launching them:

![pasdentréemidi](https://user-images.githubusercontent.com/8705846/85633611-db9cb600-b679-11ea-9b6e-64222ed2c80b.png)

**Comment by pierreguillot** [comment]
This should be fixed on the branch dev/v1.0.7.
