### ISSUE TITLE
pdstalfx - graph on parent

### ISSUE THREAD

**Issue by patricksebastien** [pierreguillot/Camomile#161]
I am loading pdstalfx in bitwig on linux (this open a tons of possibilities!), it works (basic fx patch), but I have this message: `no graph-on-parent`

My patch have a basic graph-on-parent with a number box connected. Here's a screenshot:
![pdstalfx](https://user-images.githubusercontent.com/441764/68037023-3d4c8200-fc9d-11e9-94ee-9a847e46ebc3.png)

I don't mind if it's not working, it is already fantastic.

Thanks

**Comment by pierreguillot** [comment]
Are you sure you saved the patch test.pd with the graph-on-parent option on and then you clicked on the reload button (not the force reload button in the console but the bang button between the load and close buttons in the main window)?

**Comment by devtobo** [comment]
All good my bad, it works

**Comment by patricksebastien** [comment]
My bad, it works!
