### ISSUE TITLE
i386 Depreciated on macOS 10.14.6

### ISSUE THREAD

**Issue by megrimm** [pierreguillot/Camomile#163]
2. **Describe your environment**

macbook pro 2016 macOS (10.14.6)

3. **Describe the problem or the feature request**

Seems i386 is depreciated on current macOS (10.14.6). Received build errors until I removed from xcworkspace.

also had to change CMakeLists.txt at line 13 to "set(CMAKE_OSX_ARCHITECTURES "x86_64")"

**Comment by pierreguillot** [comment]
You can use the [dev/v1.0.7](https://github.com/pierreguillot/Camomile/tree/dev/v1.0.7) branch to compile for macOS that doesn't support 32bit.

**Comment by pierreguillot** [comment]
Is it ok? Can I close this issue?

**Comment by megrimm** [comment]
Yes sorry. You can close issue. Thanks!
