### ISSUE TITLE
Duplicate VST ID

### ISSUE THREAD

**Issue by rcrath** [pierreguillot/Camomile#167]
2. **Describe your environment**
    - Windows 10 
    - Plogue Bidule, 64bits
    - Camomile & Camomile FX VST2 64 bit v. 1.06
    - 44100 Hz - 64 samples 
          
 The VST ID for both camomile and camomileFX is Kpq9.  While most VST hosts ignore this information, it is part of the VST2 specification, so the Host I use, Plogue Bidule, will not load one or the other plugin because of the duplicate ID.    Could you plz update the VST ID for one or the other and release it (I have a terrible time compiling anything on windows)

Thank you!

**Comment by korakios** [comment]
I though you can easily change the ID ,manually on the text filed

**Comment by pierreguillot** [comment]
Indeed, this is documented [here](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#all-plugin-properties). I guess that a specific section in the documentation would be better, as the wiki is collaborative so feel free to edit it if you want.

**Comment by rcrath** [comment]
Ok, that works for me. I test tons of plugins and neglected to RTM. Got the process now.  Plz close. If I have time, I'll work on the wiki. Thanks for the plugin.
