### ISSUE TITLE
compiling new vst3 with JUCE ERRORS (just 7)

### ISSUE THREAD

**Issue by greitzlechner** [pierreguillot/Camomile#168]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libpd-multi-static.lib'	Camomile_VST3	D:\AUDIOMATERIAL\PD\CamomileNEW\Instrument\Builds\VisualStudio2015\LINK	1	
Error (active)	E0312	no suitable user-defined conversion from "const juce::Array<juce::AudioProcessorParameter *, juce::DummyCriticalSection, 0>" to "const juce::OwnedArray<juce::AudioProcessorParameter, juce::DummyCriticalSection>" exists	Camomile_SharedCode	D:\AUDIOMATERIAL\PD\CamomileNEW\Source\PluginProcessor.cpp	278	
Error (active)	E0312	no suitable user-defined conversion from "const juce::Array<juce::AudioProcessorParameter *, juce::DummyCriticalSection, 0>" to "const juce::OwnedArray<juce::AudioProcessorParameter, juce::DummyCriticalSection>" exists	Camomile_SharedCode	D:\AUDIOMATERIAL\PD\CamomileNEW\Source\PluginProcessor.cpp	585	
Error (active)	E0312	no suitable user-defined conversion from "const juce::Array<juce::AudioProcessorParameter *, juce::DummyCriticalSection, 0>" to "const juce::OwnedArray<juce::AudioProcessorParameter, juce::DummyCriticalSection>" exists	Camomile_SharedCode	D:\AUDIOMATERIAL\PD\CamomileNEW\Source\PluginProcessor.cpp	610	
Error	C2440	'initializing': cannot convert from 'const juce::Array<juce::AudioProcessorParameter *,juce::DummyCriticalSection,0>' to 'const juce::OwnedArray<juce::AudioProcessorParameter,juce::DummyCriticalSection> &'	Camomile_SharedCode	D:\AUDIOMATERIAL\PD\CamomileNEW\Source\PluginProcessor.cpp	278	
Error	C2664	'void CamomileAudioParameter::saveStateInformation(juce::XmlElement &,const juce::OwnedArray<juce::AudioProcessorParameter,juce::DummyCriticalSection> &)': cannot convert argument 2 from 'const juce::Array<juce::AudioProcessorParameter *,juce::DummyCriticalSection,0>' to 'const juce::OwnedArray<juce::AudioProcessorParameter,juce::DummyCriticalSection> &'	Camomile_SharedCode	D:\AUDIOMATERIAL\PD\CamomileNEW\Source\PluginProcessor.cpp	585	
Error	C2664	'void CamomileAudioParameter::loadStateInformation(const juce::XmlElement &,const juce::OwnedArray<juce::AudioProcessorParameter,juce::DummyCriticalSection> &)': cannot convert argument 2 from 'const juce::Array<juce::AudioProcessorParameter *,juce::DummyCriticalSection,0>' to 'const juce::OwnedArray<juce::AudioProcessorParameter,juce::DummyCriticalSection> &'	Camomile_SharedCode	D:\AUDIOMATERIAL\PD\CamomileNEW\Source\PluginProcessor.cpp	610	

>>>>all the other errors i was able to resolve. any suggestions?

**Comment by pierreguillot** [comment]
Did you follow the Readme instruction? And please describe the steps to compile.

**Comment by greitzlechner** [comment]
i havent found any readme instructions yet to compile a new vst3.. can you point me to a link?

steps to compile:
1. i haven opened the "Camomile.jucer" file in JUCE
2. in the project settings / plugin formats i have only enabled "VST3"
3. under exporters/visual studio 2015 i have added the libd_wrapper to Header Search Path
4. under Modules/juce_audio_plugin_client i have disabled JUCE_VST3_CAN_REPLACE_VST2
5. saved and opened the project with visual studio
6. retargeted solution like it is suggested
7. build solution

thanks for your help :-)

**Comment by pierreguillot** [comment]
> i havent found any readme instructions yet to compile a new vst3.. can you point me to a link?

https://github.com/pierreguillot/Camomile#compilation

**Comment by greitzlechner** [comment]
thank you. in your instructions you write:
Windows
Important: libpd requires the static pthread library for windows with multithread static runtime library (MT).
i have downloaded it. so how do i add it to libpd ?

**Comment by pierreguillot** [comment]
In Dependencies\LibPdBuild\pthread.lib and/or Dependencies\LibPdBuild\VisualStudio2015\pthread.lib I think...
