### ISSUE TITLE
Can't view presets in Ableton

### ISSUE THREAD

**Issue by theslyprofessor** [pierreguillot/Camomile#170]
In Logic, presets are viewable here:
![image](https://user-images.githubusercontent.com/20659937/77887867-2bf1ac80-7220-11ea-884a-3105c06c74e3.png)

In Ableton, no ability to view presets is available:
![image](https://user-images.githubusercontent.com/20659937/77887956-59d6f100-7220-11ea-82df-d4cfb7e88cdc.png)

As per Ableton's documentation:
If the developer of the plugin doesn't integrate a browser in the plug-in custom window there is no possibility to access these presets.

**Comment by Lucarda** [comment]
On Ableton9 I get the presets on the GUI. See pic:

![ableton1](https://user-images.githubusercontent.com/25239522/77890982-a9301800-7246-11ea-9909-83c1851aa1c1.png)

**Comment by pierreguillot** [comment]
I guess this is more related to Ableton than Camomile. And you can use a radio button in the patch to create a preset interface in the main window.
