### ISSUE TITLE
savestate data makes plugin crash

### ISSUE THREAD

**Issue by jyg** [pierreguillot/Camomile#171]
When creating a plugin patch for camomille with pd > 0.49 ,
if this patch contains an abstraction with savestate object, if state of this abstraction has been saved within the main patch, (i.e. there are lines beginning with `#A saved` in the main patch), the corresponding camomille plugin crashes when loaded.

Workaround : open the plugin patch with pd 0.48, save it in order to eliminate all `#A saved` lines.
The plugin won't crash again.

Tested on Linux Lubuntu 18.04.4  with Reaper 6.09
Using savestate-example.pd of savestate-help.pd (pd > 0.49) as an abstraction inside plugin's main patch

**Comment by pierreguillot** [comment]
This should be fixed on the dev/v1.0.7 branch where Pd is up-to-date. I will test it and merge it into master.

**Comment by jyg** [comment]
Thanks. I compiled dev/v1.0.7 branch and it works now. `Savestate` object is defined and `#A saved` data are correctly retrieved.
