### ISSUE TITLE
Feature request : z order for drawing guis, inverted z order for mouse interaction

### ISSUE THREAD

**Issue by jyg** [pierreguillot/Camomile#172]
In puredata tcl-tk , in case of overlapped gui widgets,  the last created gui object is painted on top of previous guis, but it's the first created (the hidden one) that captures mouse events.
Although this seems a bit unlogical, it enables to create custom guis with specific behaviours 
(example : a demultiplicated slider - see below).
Would it be possible to enable this inverted z-order for mouse interactions in camomille, (maybe with a specific flag in configuration file), or is this mecanism internally  handled by JUCE and cannot be changed ?

#N canvas 0 50 739 300 12;
#X floatatom 205 96 5 0 0 0 - nb-rcv nb-snd;
#X floatatom 206 115 5 0 0 0 - nb-rcv nb-snd;
#X floatatom 206 135 5 0 0 0 - nb-rcv nb-snd;
#X obj 306 103 r nb-snd;
#X msg 263 201 set \$1;
#X obj 263 226 s nb-rcv;
#X obj 303 133 t f f f;
#X obj 337 164 -;
#X obj 337 189 * 0.2;
#X obj 337 214 +;
#X obj 337 239 t f f;
#X obj 337 264 clip 0 127;
#X obj 203 99 vsl 40 50 0 127 0 0 empty empty empty 0 -9 0 10 -262144
-1 -1 903 1;
#X obj 36 102 vsl 40 50 0 127 0 0 empty empty empty 0 -9 0 10 -262144
-1 -1 600 1;
#X text 33 82 normal slider;
#X text 184 42 demultiplicated slider, f 15;
#X text 391 187 demultiplication factor;
#X connect 3 0 6 0;
#X connect 4 0 5 0;
#X connect 6 0 4 0;
#X connect 6 1 7 1;
#X connect 6 2 7 0;
#X connect 7 0 8 0;
#X connect 8 0 9 0;
#X connect 9 0 10 0;
#X connect 10 0 11 0;
#X connect 10 1 9 1;
#X connect 11 0 12 0;

**Comment by pierreguillot** [comment]
Indeed, this should be done the same way.
Thank you!

**Comment by jyg** [comment]
Thanks. I cloned  the dev/v1.0.7 branch but I may have missed something, because I only get  LV2 plugin, no vst / vst3 .so files.

**Comment by jyg** [comment]
I fear that z-order, being implemented in JUCE, must be structurally the same for drawing AND mouse-interactions, and that this cannot be changed.

**Comment by pierreguillot** [comment]
Indeed, you're right. The solution would be to reimplement the mouse mechanism of JUCE... I'll investigate the problem.

**Comment by jyg** [comment]
I thing this would be too much efforts for a very specific case of use. A more convenient enhancement (off topic) would be the possibility to repaint cnvs (GuiPanel)  after being moved, vis_resized or with label changed.
Investigating in the code, I cannot figure how do you force repainting for others guis (sliders, numbers, etc...) when they are programmatically changed (receiving a float on their inlet).
