### ISSUE TITLE
Enhancement : updating labels and guis when dynamically changed

### ISSUE THREAD

**Issue by jyg** [pierreguillot/Camomile#173]
I digged into your code (v1.0.7) and did some modifs in order to  repaint labels and guis when dynamically changed.
I had to change some  code in  pd sources, by adding a flag "-dirty" in some  files (g_my_canvas.c  etc..)   and in some of your camomile files (PluginEditor.cpp, PluginEditorObject.cpp, etc...)
I'll try to do a pull request as soon as possible, when I understand how to include subrepos modifications on github. 
[demo here](https://forum.pdpatchrepo.info/topic/12824/camomile-with-editable-labels-guis-and-xy-slider)

**Comment by pierreguillot** [comment]
I think there should be a way to do this that avoids changing Pd and libpd code. For example, this could be managed directly by the user with the 'repaint' message followed by the coordinates of the area to repaint.
