### ISSUE TITLE
Compile plugins to single file

### ISSUE THREAD

**Issue by Nintorac** [pierreguillot/Camomile#176]
Is it possible to compile plugins to a single file for distribution? 

I would like to distribute a plugin to end users. Specifically I have written an ML model that can generate syx messages. The model takes as input 8 parameters that then generate a full DX7 patch. Currently I have written a website to [generate cartridges](https://www.thisdx7cartdoesnotexist.com/) but being able to control the patch in real time is much more fun.

I think I would need to do the following steps:

- write a pd external to receive the 8 parameters and generate the syx file
- create the front end in pd and compile into single file `vst`, `lv2`, `au` etc.
- distribute single file without requiring users to know anything about PD

Is this a valid use case for Camomile and if so do you have any pointers or pitfalls?

**Comment by pierreguillot** [comment]
Hello,
- If you write a Pd external, you will have to compile a specific version of Camomile directly with the external - see https://github.com/pierreguillot/Camomile/issues/138 for further information. If you can use vanilla objects it will be simpler.
-  Depending on the OS and the format, the plugins are dynamic libraries or bundles. On macOS, the Pd patchs will be embedded in the bundles (*.vst, *.vst3, *.component, etc.), on Windows you can share a folder (or the vst3 bundle) containing the Pd patches next to the plugin dll.
- Whatever the OS, the user can directly use the plugin without knowing anything about Pd.

**Comment by Nintorac** [comment]
Ok, awesome. Thanks for the tips!
