### ISSUE TITLE
Possible background images copyright issue

### ISSUE THREAD

**Issue by trebmuh** [pierreguillot/Camomile#177]
Bonjour Pierre.

I'm currently packaging camomile for LibraZiK-3 and found out that some images (Spip.png, Bulgroz.png, and Castafiore.png) are likely to still be under copyright. For LZK, I'm replacing them by colorfull background so that isn't a big issue for me, but still, you might want to be aware of it.

Note that I'm understanding that this is probably a wink (un clin d'oeil quoi) to some comic books you like, so, without any will to stole something from their authors (which seems to be indicated by the fact you gad nicely wrote the credits on the images) and probably you think of those as a "short quote" but... well... unfortunately, sometime, the rights owners aren't very nice with those stuff.

Note that maybe you did get an authorization to use from the rights owners but I didn't see that anywhere so I'll assume it's not there for now (that would be awesome!).

I'm very sorry to bring this sort of bad feelings/news here if it looks so, be sure it's not intended! I simply though that this can be a blocker for distribution of Camomile and so that might be a good idea to discuss it.

Nice piece of software by the way! Thank you!

**Comment by trebmuh** [comment]
By the, Camomile entered LZK-3 now.
See https://mastodon.xyz/@LibraZiK/104401394392623886

**Comment by pierreguillot** [comment]
This is the FAQ of the Dupuis edition https://www.dupuis.com/catalogue/FR/statique/faq.html. I contacted the editions a while ago but I never get any answer (I think they really don't care...). If someday I received a warning from the editions I will remove the images but until then...

**Comment by trebmuh** [comment]
OK, sounds good and nice enough.
What about putting a line in the [README](https://github.com/pierreguillot/Camomile#credits)?

**Comment by pierreguillot** [comment]
done on dev/v1.0.7
