### ISSUE TITLE
Failed to build 32bits binaries on Linux

### ISSUE THREAD

**Issue by trebmuh** [pierreguillot/Camomile#178]
It is currently impossible to make a 32 bits binary since the [Makefile](https://github.com/pierreguillot/Camomile/blob/master/Makefile) hardcode a 64bit flag.

It works after replacing -m64 by -m32 (tested on a LibraZiK-3 / Debian Buster).

It'd be great if the build system could auto-recognize if the build-host is a 64 bit or a 32 bit one, then build the 64/32 binary accordingly.

**Comment by pierreguillot** [comment]
The makefile is generated using the projucer, you should use the projucer projects to generate a new targets.

**Comment by pierreguillot** [comment]
@trebmuh Is there really a need of a 32bit Linux target on this repository or is it okay if you create one locally?

**Comment by trebmuh** [comment]
@pierreguillot : the change is such trivial that it'd be great if the project could cater for old-ish computer.

**Comment by pierreguillot** [comment]
Ok, if the branch [i386-support](https://github.com/pierreguillot/Camomile/tree/dev/i386-support) works for you I can merge it to dev/v1.0.7.

**Comment by pierreguillot** [comment]
@trebmuh Did you try it?

**Comment by pierreguillot** [comment]
I changed it on dev/imp-compilation, you can do use `TARGET_ARCH` (for example: `make TARGET_ARCH=-m32 CONFIG=Debug`). I will merge it to dev/v1.0.7.
