### ISSUE TITLE
OSX Catalina - build fails

### ISSUE THREAD

**Issue by edwar64896** [pierreguillot/Camomile#187]
Following build instructions from wiki, build fails on osx catalina due the ongoing presence of i386 target across project targets.

**Comment by pierreguillot** [comment]
I guess you tried to compile the master branch, you should use dev/v1.0.7. Please read this, https://github.com/pierreguillot/Camomile/blob/master/.github/CONTRIBUTING.md. I guess this also related to https://github.com/pierreguillot/Camomile/issues/169 and https://github.com/pierreguillot/Camomile/issues/163. I close this issue but feel free to reopen it if this is another problem.
