### ISSUE TITLE
LV2 plugin parameters normalized to 0-1

### ISSUE THREAD

**Issue by GModal** [pierreguillot/Camomile#188]
**Describe your environment**
Debian Buster, kernel 4.19.0

Same behavior observed in Camomile 1.0.6, and in the new .7 Beta8 (Thanks for the continued work!!!)

**Describe the problem or the feature request**
All the LV2 plugins parameters are normalized to 0-1 range. This isn't the case for the VST plugins (not tested in Beta8), those plugins display the correct ranges. It's not the norm for other LV2 plugins.

Proportionally the LV2 parameters all function correctly, but they don't equate to the values in the GUI. So the min, max and default values are all normalized in a "functional" way.

**Comment by pierreguillot** [comment]
Thanks for report. I have to check the LV2 specification. What DAW do you use?

**Comment by GModal** [comment]
I've been using Camomile plugins mostly in Carla. They work very well, despite the normalization.

I have noticed that the plugins will crash Ardour if any parameters are changed in the "edit with generic controls" window. Otherwise, changing params in the GUI work OK.

**Comment by pierreguillot** [comment]
All is fixed on the branch dev/v1.0.7:
- Fix LV2 parameters crash on Ardour
- Add parameter range support for LV2
- Add parameter label support for LV2

**Comment by GModal** [comment]
Fix works well, Pierre. Thanks!!!
