### ISSUE TITLE
Compilation Linux

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#19]
from Oscar:

Hi Pierre:
I work with GNU/Linux for 32 bits.

First

make
Compiling LookAndFeel.cpp
In file included from ../../Source/../JuceLibraryCode/JuceHeader.h:17:0,
                 from ../../Source/LookAndFeel.hpp:28,
                 from ../../Source/LookAndFeel.cpp:25:
../../Source/../JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.h:4:82: fatal error: ../../../ThirdParty/Juce/modules/juce_audio_basics/juce_audio_basics.h: No existe el archivo o el directorio
 #include "../../../ThirdParty/Juce/modules/juce_audio_basics/juce_audio_basics.h"
                                                                                  ^
compilation terminated.
make: *** [build/intermediate/Debug/LookAndFeel_40552bdf.o] Error 1

then i copy files from JuiceLibraryCode ro ThirdParty/Juce and type make

/usr/include/c++/4.8/exception:35:37: error: expected declaration before end of line
 #pragma GCC visibility push(default)
                                     ^
make: *** [build/intermediate/Debug/LookAndFeel_40552bdf.o] Error 1

Thre are two terminal screenshots attached to this message

Thanks

![screenshot - 030416 - 09_51_16](https://cloud.githubusercontent.com/assets/1409918/14232724/b67b555c-f9b3-11e5-9157-cfa01c6ac984.png)
![screenshot - 030416 - 10_02_48](https://cloud.githubusercontent.com/assets/1409918/14232725/b67ebc06-f9b3-11e5-96b7-e0f64a72f69d.png)

**Comment by pierreguillot** [comment]
You don't have to copy any file. JuceLibraryCode must stay in the JuceLibraryCode. I think you only forget to pull the sub modules (this is the only way to do it because the sources of Pure Data change a lot and so the makefile). 
So you have to do something like that:
``git clone --recursive https://github.com/pierreguillot/Camomile.git``
``cd Camomile``
or 
``git clone https://github.com/pierreguillot/Camomile.git ``
``cd Camomile``
``git submodule update --init --recursive``

then, follow the instruction here:
https://github.com/pierreguillot/Camomile/wiki/Compilation

**Comment by oscarsantis** [comment]
Hi:
I've followed instructions and everything runs well until...

Compiling juce_VST_Wrapper.cpp
../../ThirdParty/Juce/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:69:51: fatal error: public.sdk/source/vst2.x/audioeffectx.h: No existe el archivo o el directorio
 #include <public.sdk/source/vst2.x/audioeffectx.h>
                                                   ^
compilation terminated.
make: *** [build/intermediate/Release/juce_VST_Wrapper_d073fbff.o] Error 1

Best 

![screenshot - 030416 - 13 30 57](https://cloud.githubusercontent.com/assets/18247189/14233508/11cd3276-f9a1-11e5-8400-3bf4c91ce88e.png)

**Comment by pierreguillot** [comment]
You must download the VST SDK here: [VST SDK](http://www.steinberg.net/en/company/developers.html. )
And put the content a the folder in ThirdParty/Vst so you'll have something like ThirdParty/Vst/base, ThirdParty/Vst/bin, etc.
I can't publish this SDK for license issues.

**Comment by oscarsantis** [comment]
Solved.
I did it
Thanks a lot
