### ISSUE TITLE
Linux VST3 issues

### ISSUE THREAD

**Issue by GModal** [pierreguillot/Camomile#191]
2. **Describe your environment**
Debian Buster, stable
Carla 2.2.0-RC1
Camomile 1.0.7 Beta14

3. **Describe the problem or the feature request**

When the camomile script is invoked, two folders are created in /Build/"ProjName".vst3 --

*  /"ProjName".vst3
	* /CamomileFx.vst 
		* /Contents 
			* /x86_64-linux 
			{
			CamomileFx.so file only
			}
	* /Contents
		* /x86_64-linux
		{
		CamomileFx.so file (not renamed)
		project files (.pd, .txt, etc.)
		}

--#1) In folder with project files (/"ProjName".vst3/Contents/x86_64-linux/), "CamomileFx.so" not renamed to "ProjName".so. The plugin works when the library is renamed manually...with the exceptions noted below (#3).

--#2) The /"ProjName".vst3/CamomileFx.vst folder is redundant. It also seems override plugin registry for some applications. For that folder the "ProjName" is replace with "Camomile", and that doesn't instantiate a plugin correctly (no project files).

--#3) Each vst3 plugin registers a list of extra MIDI CC parameters (192 total). I don't know if this is behavior is unique to Carla, or to the plugin. The number of vst3 hosts is currently limited for Linux, so it's difficult to test. Pic below --

![vst3_params](https://user-images.githubusercontent.com/67518669/90516927-b20c8200-e132-11ea-9f95-9bf643b17820.png)

**Comment by pierreguillot** [comment]
First: Please, can you create several issues if there are several issues and can you use a name more explicit for the issues?
Short answers: 
1. Indeed, this should be fixed.
2. Did you use the pre-compiled binaries? And how did you invoke the script? 
3. This should be related to this: https://forum.juce.com/t/what-is-the-intention-of-macro-juce-vst3-emulate-midi-cc-with-parameters/17858. This must be investigated.

**Comment by GModal** [comment]
Sorry about that -- I'll be glad to open separate issues, if you want to close/delete this one...

**Comment by pierreguillot** [comment]
Yes, can you do it please?

**Comment by pierreguillot** [comment]
Yes, can you do it please?
