### ISSUE TITLE
dinamically load libpd into camomile

### ISSUE THREAD

**Issue by porres** [pierreguillot/Camomile#200]
this would be useful for people who compile libpd with externals, and then you can just replace it without the need to create a fork and a parallel project like "camomile extended"

**Comment by pierreguillot** [comment]
I guess this this related to https://github.com/pierreguillot/Camomile/issues/138 and perhaps to https://github.com/pierreguillot/Camomile/issues/157. In this case, please use these issues and close this one to avoid too much noise.

**Comment by porres** [comment]
I can't say if they're related or not, but if you say so, you can close and I'll trust you and will understand you have this noted ;)
