### ISSUE TITLE
Linux LV2: [openpanel( not functioning in Ardour

### ISSUE THREAD

**Issue by GModal** [pierreguillot/Camomile#203]
2. **Describe your environment**
Debian Buster, stable
Carla 2.2.0-RC1
Ardour 5.12.0
Qtractor 0.9.5
Camomile 1.0.7 

3. **Describe the problem or the feature request**
The [openpanel( dialog doesn't instantiate from the LV2 plugin in Ardour. I don't believe VST3 is implemented in Ardour.

**Comment by pierreguillot** [comment]
Can you check that the audio is "really" running? The audio callback of the plugin should be called to receive/send messages between the plugin and the pd patch.

**Comment by GModal** [comment]
> Can you check that the audio is "really" running? The audio callback of the plugin should be called to receive/send messages between the plugin and the pd patch.

Not sure I understand the question -- the plugin (pd) audio works normally, and responds to parameter changes. But the dialog doesn't open when used in Ardour. It doesn't effect any audio. I don't get any error msgs in Ardour or in the Camomile plugin console.

Of course [openpanel( isn't triggered by any defined parameters, it's just a [bang] in the gui.

**Comment by pierreguillot** [comment]
It seems that the native file browser window is not supported by Ardour (i didn't try other DAWs, did you?) on Linux with LV2 plugins... so I replace it with the juce one. Can you test this version: [CamomileLinux64(1).zip](https://github.com/pierreguillot/Camomile/files/5194839/CamomileLinux64.1.zip)?

**Comment by GModal** [comment]
Yes, will do. I will let you know.

I'm sure I don't need to tell you there isn't a standard file dialog in Linux :-) ...gtk, kde, qt, etc., all have different dialogs (and tk for Pd). I'm guessing your standard is whatever is built into libpd(?). And Ardour uses a lot of custom dialog boxes, apparently. Not at all certain that has any bearing on this issue, though.

**Comment by GModal** [comment]
OK, [openpanel( does work now in Ardour. I am seeing an occasional xrun during file loading, but that's to be expected with the overhead.

Also tested it on Carla and Qtractor. It's working well -- also, with those hosts it seems to have fixed issue #197. Minimal xruns (when they happen, it's no doubt related to the overhead of file loading, cpu capacity, etc). I will do some tests with [switch~] and check on that.

**Comment by pierreguillot** [comment]
Great! Thank you! Juce allows to use the "native" dialog box of zenity and kde but for obscure reason, it doesn't seem to work in this case. I will merge the changes into dev/v1.0.8 and then I'll have a look at the xruns issue.

**Comment by GModal** [comment]
Thank you! Happy to do what I can -- Camomile is a great project!!
