### ISSUE TITLE
Unable to make parameter accessible as output in FL Patcher

### ISSUE THREAD

**Issue by GabbageFilms** [pierreguillot/Camomile#204]
2. **Describe your environment**
    - **OS**: Windows 10 64bit
    - **DAW**: FL Studio 20 - 64bit
    - **Plugin**: VST3 1.0.7         
         
3. **Describe the problem or the feature request**
I am trying to make a patch VST that converts MIDI note panning into a parameter that can be fed into a another VST via FL Studio's Patcher. The functionality is in Fruity Envelope Controller. It allows MIDI input and outputs a parameter controller value for the velocity channel, but not panning. Is there a way to do this in Camomile? I'm only able to access MIDI and audio as outputs currently. If it is not possible are you aware of any VST's that allow the conversion of MIDI channel data into a parameter controller output?
            
           
![image](https://user-images.githubusercontent.com/8847839/92296211-f182ee80-eee6-11ea-97ff-bb02cf65cded.png)

**Comment by pierreguillot** [comment]
I don't think that a VST plugin could generate the parameters of another plugins. This should be something really specific to FL studio. But if FL studio allows that perhaps you can control another plugin using MIDI CC or Open sound control?
