### ISSUE TITLE
Question: safe to use one [route( obj to receive param?

### ISSUE THREAD

**Issue by GModal** [pierreguillot/Camomile#206]
2. **Describe your environment**
All
          

3. **Describe the problem or the feature request**

Pierre, is it safe to use one [route( obj to handle multiple parameters?

Like this:

![getAllParams](https://user-images.githubusercontent.com/67518669/92309897-50904400-ef77-11ea-94d4-b9f0b89553c5.png)

Thx!

**Comment by pierreguillot** [comment]
Yes, I don't see any problem with that. It should be more efficient ;)

**Comment by GModal** [comment]
Great, thanks! It does reduce the cpu load...
