### ISSUE TITLE
File open causes freeze of plugin and host on Linux (Tracktion)

### ISSUE THREAD

**Issue by unknownError** [pierreguillot/Camomile#21]
Hi, I compiled the plugin on ubuntu 16.04 moved the .so file from the build folder to my ~/.vst folder and tried Tracktion to load the plugin. Plugin scans and loading is fine (gui shows up), but doesn't respond any more to user input after clicking file open. Other menu items are not affected.

edit: same happens in renoise.
edit2: also Tried the v0.0.8 branch with same result.

**Comment by pierreguillot** [comment]
Hi, have you tried with the pre-compiled files (only available in 64-bit)? Otherwise I'll need more information. Are you in 64-bit or 32-bit ? The plugin crashes (so you should have a crash report) or it freezes indefinitely ? Have you tried on another ubuntu version ? I think 16.04 is still a beta.
The plugin freezes after clicking or after selecting a file ?

**Comment by unknownError** [comment]
I now also tried the 0.0.7 beta precompiled 64 bit versions with the same result. actually I noticed that only the gui part of Tracktion seems to be affected, I still got the hiss-sound of the Tracktion demo after the freeze happens. 

I'll try on an other system of ubuntu 16.04 later - I updated this system from an older version of ubuntu and maybe it's related to that.

I made a screencast for details: https://youtu.be/DvKWN4mJjEQ

**Comment by pierreguillot** [comment]
Normally, you the plug-in should display a file chooser. So there must be a problem between Juce (the API that manage the GUI) et your version of Ubuntu. I'll try check that. 
Thanks

**Comment by pierreguillot** [comment]
I can't test it but you can. In the file: /ThirdParty/Juce/modules/juce_gui_basics/filebrowser/juce_FileChooser.cpp
at line 103, you can try to replace "#elif JUCE_MAC || JUCE_LINUX" by "#elif JUCE_MAC"
Perhaps the problem comes from the native file Browser.

**Comment by unknownError** [comment]
yep - that did the trick :) I could not test on an other 16.04 system, but will find that out soon.

**Comment by pierreguillot** [comment]
This seems to be a known bug, but the JUCE team can't reproduce it. I'll try with Ubuntu 16.04 when I'll be able.

**Comment by pierrep** [comment]
Hi, I'm having the same problem. Ubuntu 16.04, with version 0.0.7
Is the only solution to recompile with that fix you suggested?

**Comment by pierreguillot** [comment]
The next release won't have this problem (because the file will be open directly)

**Comment by pierrep** [comment]
Great, thanks!
