### ISSUE TITLE
Request for complete Cmake build

### ISSUE THREAD

**Issue by chikashimiyama** [pierreguillot/Camomile#212]
First of all, thank you @pierreguillot for the fantastic project. I wrote a Pd book in Japanese in 2013 and I'm working as an audio plugin developer now. so your project connected my current and past in a very interesting way. 

When the issue https://github.com/pierreguillot/Camomile/issues/138 is solved, Caomile may become a killer software for audio plugin developers because product owners can experiment and prototype DSP chain in Pd patch without bothering devs and they can even ship the alpha version of the product to get user feedback by just wrapping their pd patch in VST with Camomile.

But for this kind of workflow and to integrate Camomile in build pipelines CI/CD more efficiently, a complete CMake-based build system would be really helpful. As far as I understand, Camomile uses juce6 ( whose most important feature is Cmake support ) but still employs projucer for file/build management. Is there any reason behind that? or do you plan to migrate to Cmake in the near feature?

**Comment by pierreguillot** [comment]
Hi,
Thanks for your feedback! I just update to juce 6 a few weeks ago and I didn't check the CMake integration yet. What would be the benefit? Do you know if there is any limitation or bug? As the CI/CD works perfectly (using Travis and Appveyor), I don't want to move to something else that would break the setup. But if there is no major issue, I've no problem to move to CMake build system (as it is already used for libpd). I will have a look at it but feel free to create a PR if you want :)

**Comment by chikashimiyama** [comment]
We migrated all our product line projects to Cmake/juce6 one month ago and so far we are very happy with that, since we can build everything with CLion and could ditch XCode from our workflow entirely, and dependency management of Modern CMake is simply awesome compared to Projucer. I also cloned camomile project and change that to CMake project and it worked perfectly though I only tried Mac/VST3 combination. Since our goal is to test several combinations of our DSP algorithm wrapped in Pd objects in DAW session, we need to build our externals with camomile itself due to #138 ... so Cmake is here also very helpful because I can invoke some scripts in the build process of CMake so that we can automate the process you showed in the video of #138

One thing we have never tested is Linux LV2 path, we have no idea about that because we don't support LV2.

About the PR, unfortunately, I don't have time due to the newborn crying next to me but I can ask my colleagues if they can help.

**Comment by alfonso73** [comment]
Hi Chikashi, could you please make a little CMake tutorial for compiling
Camomile with custom externals/libraries, if you have any spare time?
thanks!
a.

www.elgallorojorecords.bandcamp.com/
<https://elgallorojorecords.bandcamp.com/>
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
FYI, I started a branch dev/cmake-support.

**Comment by xunil-cloud** [comment]
Hi, I just saw the new branch dev/cmake-support. I have modified `CMakeLists.txt` a little bit trying to make it work on Linux. It seems that the work is still in progress, Right?. Would you like to accept the pull request?

**Comment by pierreguillot** [comment]
Hi, the branch is still a WIP, the CI doesn't work, the Windows' built doesn't work either, the LV2 support is not done yet, the commit historic is a mess, etc. So I'm not sure I'll be able to merge your branch but feel free to create a PR and/or to show me to the fixes, that would help me to finish this feature sooner :) Thank you

**Comment by xunil-cloud** [comment]
Thanks for your reply, see #217.

**Comment by pierreguillot** [comment]
@xunil-cloud The Linux build seems okay now. Thank you very much!
The most important things to do are to
- [ ] Fix the windows build (compiling pthread static library using CMake)
- [ ] Add LV2 support (but the dynamic library doesn't seem to be supported by Juce using CMake...)

**Comment by pierreguillot** [comment]
The Windows built is okay now and doesn't require to install any dependency!

**Comment by pierreguillot** [comment]
I managed to compile LV2 plugins using CMake 😓 . I still need to clean and test everything but I see the end of this.

**Comment by pierreguillot** [comment]
This is done and merged into the branch dev/v1.0.8
