### ISSUE TITLE
Compiling Camomile in Windows

### ISSUE THREAD

**Issue by emviveros** [pierreguillot/Camomile#215]
Hello again!

I won´t be able to compile Camomile using the instructions in README.md.

I'm stuck in step:

```
cmake -G "Visual Studio 14 2015 Win64" -DPD_MULTI=ON -DPD_UTILS=OFF -DMSVC_STATIC_RUNTIME=ON -DMSVC_PTHREAD_LIB="pthread.lib" ../..
```

I have the error:
```
-- Selecting Windows SDK version  to target Windows 10.0.19041.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.23107.0
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 11/10/2020 17:19:46.
    Project "C:\Users\Esteban\src\Camomile\Dependencies\LibPd\build\msvc\CMakeFiles\3.17.3\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Users\Esteban\src\Camomile\Dependencies\LibPd\build\msvc\CMakeFiles\3.17.3\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\Esteban\src\Camomile\Dependencies\LibPd\build\msvc\CMakeFiles\3.17.3\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\Esteban\src\Camomile\Dependencies\LibPd\build\msvc\CMakeFiles\3.17.3\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Users\Esteban\src\Camomile\Dependencies\LibPd\build\msvc\CMakeFiles\3.17.3\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:08.63

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Users/Esteban/src/Camomile/Dependencies/LibPd/build/msvc/CMakeFiles/CMakeOutput.log".
```

[CMakeOutput.log](https://github.com/pierreguillot/Camomile/files/5362939/CMakeOutput.log)

I'm using a Windows 10 Home machine x64. 

Thanks any advance!

**Comment by pierreguillot** [comment]
Can you give further information ? What did you do (not only the last command you used) ? What version of Visual Studio is installed ? etc.  And did you look for the **error MSB4019** on internet, it seems to be related with VS version.

**Comment by emviveros** [comment]
Ok Thanks.. I'm need more patience with windows stuff.. I swear I will have!

Yes it's a matter with VS version

I have installed in the windows machine VS 2017 and the [Ms build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159)

VS2017 was installed before. And I thought the build Tools 2015 could work.

There's a way to avoid install complete VS2015 to use already installed VS2017?

**Comment by pierreguillot** [comment]
You can change the exporter for libpd using the -G option on CMake and if you open the Camomile Visual Studio project with a newer of VS, a dialogue window asks you if you want to update the project, then click yes.

**Comment by pierreguillot** [comment]
Did it work with VS 14 - 2015?

**Comment by Lucarda** [comment]
@pierreguillot does the command:

`cmake -G "Visual Studio 14 2015 Win64" -DPD_MULTI=ON -DPD_UTILS=OFF -DMSVC_STATIC_RUNTIME=ON -DMSVC_PTHREAD_LIB="pthread.lib" ../..`

should end with `../../../LibPdBuild` instead of `../..` ?

`../../../LibPdBuild/CMakeLists.txt` is newer and contains `s_net.c` along other files that are not in `../../CMakeLists.txt`

@emviveros I also couldn't make "Ms build Tools 2015" to work :(

**Comment by pierreguillot** [comment]
@Lucarda No but the previous line on the Readme in bad, you should be located in LibPdBuild, then the command seems okay.
 
If it's simpler, you can use the appraoch from [appveyor.yml](https://github.com/pierreguillot/Camomile/blob/master/appveyor.yml):
- cd \Dependencies\LibPdBuild\VisualStudio2015
- cmake -G"Visual Studio 2015"
- msbuild libpd.sln /t:libpdstatic /nologo /verbosity:quiet /p:Configuration=Release /p:Platform=x64

Depending on the target, you can replace `Release` with `Debug`, `x64` with `Win32`. You can also defiine the path to pthread using `-DMSVC_PTHREAD_LIB="path/to/pthread.lib"`. See the options of the [CMakeList.txt](https://github.com/pierreguillot/Camomile/blob/master/Dependencies/LibPdBuild/CMakeLists.txt) for further information.  

If you need, you can select another [cmake-generators](see https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators) such as VS2017. But the Camomile pre-generated VS solutions are made for VS2015 so when you open a solution (for example [Effect/Builds/VisualStudio2015/CamomileFx.sln](https://github.com/pierreguillot/Camomile/blob/master/Effect/Builds/VisualStudio2015/CamomileFx.sln) with a newer version of VS, the IDE asks you if you want to update the solution. Do it and then you can compile using the command line and/or via the IDE.  

And don't forget to install the pthread library and the corresponding header files!

**Comment by Lucarda** [comment]
@pierreguillot thanks. I'm compiling with MinGW only for experimentation. This post is rather a documentation of what I get.

First I compile libpd with MinGW64:

```
mkdir Dependencies/LibPd/build && mkdir Dependencies/LibPd/build/msvc && cd Dependencies/LibPd/build/msvc

cmake -G "MSYS Makefiles" -DPD_MULTI=ON -DPD_UTILS=OFF  ../../../LibPdBuild

make libpdstatic
```

and I get:

![libpdststic](https://user-images.githubusercontent.com/25239522/96771004-80749900-13b7-11eb-8b9d-bcd4c1e2375e.png)


Then I open the CamomileFx.jucer with projucer and I create a Code::blocks(windows) exporter. Here I add paths and flags and export.

Then I open the project with codeblocks and select to build the vst3 with shared:release option.

It finishes compiling with warnings (I have to recheck this) but the resulting dll have the first 3 functions missing and the plugin does not load.

Here are the good vst3 functions (the first 3 and the rest)

![vstorig](https://user-images.githubusercontent.com/25239522/96771073-941fff80-13b7-11eb-8290-19cb05882af8.png)


And here the functions from my compiled dll

![dll](https://user-images.githubusercontent.com/25239522/96771090-98e4b380-13b7-11eb-93a4-0c75403655eb.png)


It seems in this posts MinGW and vst3 are not friends

https://forum.juce.com/t/vst3-plugin-with-code-blocks-windows/27034

https://github.com/steinbergmedia/vst3sdk/issues/8

**Comment by Lucarda** [comment]
@pierreguillot  I must add that is just me doing experimental tests. I guess that installing VS will just work.

:)

Anyway it seems the trouble is around here:

https://github.com/juce-framework/JUCE/blob/78f9985e59bca8194942d63ee8beabc35241c36e/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp#L3003

https://github.com/juce-framework/JUCE/blob/78f9985e59bca8194942d63ee8beabc35241c36e/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp#L889

somehow the function does not get exported with MinGW.

I added JUCE_WINDOWS=1 but didn't worked. 

If these functions get exported it is still unknown if libpdstatic is working.

:)

**Comment by Lucarda** [comment]
@emviveros I have used the https://github.com/pierreguillot/Camomile/blob/master/appveyor.yml aproach with success. 

I installed the following on a win10 clean machine:

- **git-portable**: https://github.com/git-for-windows/git/releases/download/v2.29.2.windows.1/PortableGit-2.29.2-64-bit.7z.exe
 
  - Extract to a folder and run **git-bash.exe**

- **CMake**: https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-win64-x64.msi

  - Install with default settings

- **Visual Studio Community 2015** : https://visualstudio.microsoft.com/downloads/
 
  - with 8.1 sdk

![sdk8 1](https://user-images.githubusercontent.com/25239522/97841237-2b445b80-1cc4-11eb-871e-9f148d1f0189.png)


### gitbash

`git clone -q https://github.com/GerHobbelt/pthread-win32.git`

`cd /pthread-win32`

```
sed -i 's/4820;4668;4255;/4820;4668;4255;4711;4100;4312;4127;4296;4456;4619;4310;4311;/' pthread_lib.2015.vcxproj
sed -i 's/MultiThreadedDLL/MultiThreaded/' pthread_lib.2015.vcxproj
sed -i 's/MultiThreadedDebugDLL/MultiThreadedDebug/' pthread_lib.2015.vcxproj
```
### cmd

Compile pthread-win32

cd /d %pthread-win32FOLDER%

```
"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" pthread.2015.sln /t:pthread_lib /nologo /verbosity:quiet /p:Configuration=Release /p:Platform=x64 /p:OutDir=lib/
```

### gitbash


```
cd ../
git clone --recursive https://github.com/pierreguillot/Camomile.git
```


Copy pthread-win32 headers and library in pure-data directory

```
cp ./pthread-win32/pthread.h ./Camomile/Dependencies/LibPd/pure-data/src/pthread.h
cp ./pthread-win32/sched.h ./Camomile/Dependencies/LibPd/pure-data/src/sched.h
cp ./pthread-win32/semaphore.h ./Camomile/Dependencies/LibPd/pure-data/src/semaphore.h
cp ./pthread-win32/lib/pthread_lib.lib ./Camomile/Dependencies/LibPdBuild/VisualStudio2015/pthread.lib
cp ./pthread-win32/lib/pthread_lib.lib ./Camomile/Dependencies/LibPdBuild/pthread.lib
```

### cmd

Compile libpd

cd /d %CamomileFOLDER%\Dependencies\LibPdBuild\VisualStudio2015

`"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 14 2015 Win64" ..`

````
"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" libpd.sln /t:libpdstatic /nologo /verbosity:quiet /p:Configuration=Release /p:Platform=x64
````

Compile Camomile Effect

cd /d %CamomileFOLDER%\Effect\Builds\VisualStudio2015\

````
"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" CamomileFx.sln /nologo /p:Configuration=Release /p:Platform=x64
````

optionally use this command to clean (i think it also deletes the .vst3 file so copy it somewhere before cleaning):
````
"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" CamomileFx.sln /t:clean /p:Configuration=Release /p:Platform=x64
````

Compile Camomile Instrument

cd /d %CamomileFOLDER%\Instrument\Builds\VisualStudio2015\

````
"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" Camomile.sln /nologo /p:Configuration=Release /p:Platform=x64
````

**Comment by pierreguillot** [comment]
So it seems that the issue can be closed, isn't it? BTW, if #212 is done it should be easier in the future (even if I don't think I will ensure the maintenance for other compilers than MVC because I prefer to focus on improvement and bug fixes of the plugins).

**Comment by Lucarda** [comment]
> So it seems that the issue can be closed, isn't it?

It seems so.

@emviveros ?

**Comment by emviveros** [comment]
Sorry... These 2 weeks I have no time to eat.. I can test it next week! Close issue seems ok!

**Comment by emviveros** [comment]
Today I compiled Camomile in Windows. Thanks @Lucarda !! The infos in your tutorial are sufficient to proceed ahead to compile Camomile with externals on Windows.

Cheers

**Comment by alfonso73** [comment]
That's great. Do you think guys that i can try to compile with VS 2019
(which i have already installed?). I have a MSYS2 environment to which i
use to build pd libs with pd lib builder. Probably is another good way to
go?

**Comment by alfonso73** [comment]
Ohh i see above that Mingw and VST3 are not friends..
