### ISSUE TITLE
alternative ways with libname prefix to load binaries from externals in camomile

### ISSUE THREAD

**Issue by porres** [pierreguillot/Camomile#226]
Hi. We've been running int some conflicts and issues by trying to ship camomile in a way that works for both Pd-Vanilla and Camomile. I wonder if there could be any way to support prefixes ("else/objectname") in camomile, or at leas "./". I understand this might be just too much of a hassle, inconvenient and denied, but I had to ask :)

**Comment by pierreguillot** [comment]
This is related to the way Pd manages object classes. There is nothing I can do. You should ask the question on the Pd repository. 

PS: why don't you create an alias name to your objects? 

PPS: please, use the discussion section for this kind of question ;)
