### ISSUE TITLE
Min and max values of GUI are not updated with gui message

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#229]
From the discussion by @drugo23:
> Hi everybody,
> I need to dynamically change the range of the sliders and rescale the same values within that range without closing and reopening the plugin GUI in my DAW (it actually works if I do that). I have tried [gui redraw( --- [send camomile] and it works when I have to dynamically change labels but not in this case, anybody have a solution for this? Basically to dinamically update the GUI.

This could be managed by patching using simple math objects but it would be better to fix that in Camomile directly by updating the minimum and maximum values of the GUI with the message `[gui redraw(`.

**Comment by Drugo23** [comment]
Hi, at the end I kept the sliders range the same and just rescaled their values, but would be nice to actually rescale the ranges  and display the values within the new ranges. I have also noticed that midionly is not working with vst3 plugin, I have built a midi-seq but if I put midionly -true in the .txt file the plugin doesn’t work.

**Comment by pierreguillot** [comment]
This is fixed on dev/v1.0.8 and there is a [beta version](https://github.com/pierreguillot/Camomile/releases). 
Please, create a new discussion if you a question not related to this issue.
