### ISSUE TITLE
Midionly not working on VST3 plugins

### ISSUE THREAD

**Issue by Drugo23** [pierreguillot/Camomile#231]
Hi, 
I am not able to open the plugin I made if I put midionly true in the .txt file. Midionly is working if I use a .dll file instead of vst3 to generate the plugin. I’m on Win 10 and I have tested it on Ableton and Cubase.

**Comment by pierreguillot** [comment]
This is a duplicate. You can find the answer https://github.com/pierreguillot/Camomile/issues/149#issuecomment-672680330. 
Is there any reason to create an issue and not a discussion? This might be useful for other users.

**Comment by pierreguillot** [comment]
I updated the [wiki](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#midi-only)
