### ISSUE TITLE
Midi-in Latency Compensation

### ISSUE THREAD

**Issue by Drugo23** [pierreguillot/Camomile#236]
Hi, I am not sure this is a camomile related issue or an issue at all..

I am using a camomile plugin with the pd~ object to open patches inside Ableton, I'm on Windows 10. 

I have made a short midi clip in ableton, I just looped a C3 midi note that I use as a clock. I am receiving this note with the notein object but I am always getting it behind or off the beat, so I use the track delay compensation [https://help.ableton.com/hc/en-us/articles/209072409-Delay-Compensation-FAQ]  to compensate the latency.

If I set the right delay time, the midi note is perfectly in sync with the ableton metronome. The funny thing is that whenever I change the BPM in my DAW I have to adjust the delay time to put it back in sync, for example at 40bpm the right track delay time is 160ms at 120bpm is 35ms and so on. 

The question is, once I have found the ms to compensate the latency, why do I need to change them in relation to the BPM value? Aren't they supposed to be the same for any BPM value?

**Comment by pierreguillot** [comment]
Hi,

> I am not sure this is a camomile related issue or an issue at all..

In this case, I suggest you create a  new [discussion](https://github.com/pierreguillot/Camomile/discussions). This way, you avoid to congest the issues section. 

About you issue:
Without more information, it will be difficult to help you. Can you provide further information about what you do and how you do it, a patch, the sampel rate, and so on - everything that might be related to your problem? And I suggest you to read this [part](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#latency) of the documentation, this might be related.

**Comment by pierreguillot** [comment]
I close this issue due to lack of activity.
