### ISSUE TITLE
lv2 how to

### ISSUE THREAD

**Issue by sone** [pierreguillot/Camomile#237]
Hi, I would like to ask how to install the lv2 version or how to get .lv2 folders like the existing Camomile.vst3 and CamomileFx.vst3 folders?
Do I have to execute lv2_file_generator and if so, how to use it?
Best regards

**Comment by GModal** [comment]
Hi -- most of this is covered in the docs. So, assuming you're on Linux, 'cause you're asking about LV2, _and_ assuming you've got the executable unarchived somewhere:

- cd to the Camomile folder (camo source is in the "Camomile/Examples" folder -- use the provided examples or make your own)
- in the shell, execute the camomile script: **./camomile** --this will build all the examples.
- the compiled plugins will be in the Camomile/builds folder
- Copy any *.lv2 subfolders there to your local LV2 folder (`/.lv2)

**Comment by sone** [comment]
Thank you very much, this is working.
I looks like I've misunderstood what is possible because I've thought there is a lv2 version of camomile like there is a vst3 version.
Thus I've thought it's possible to open the camomile "pd-host" plugin in a lv2 host to use plugins written in pd.

**Comment by pierreguillot** [comment]
> Thus I've thought it's possible to open the camomile "pd-host" plugin in a lv2 host to use plugins written in pd.

You can create and generate your own LV2 plugins with Pd patches. I suggest you follow the same approach as for the examples. And you'll find a lot of information on the wiki. Please, read it carefully. If you need further information, feel free to ask (the discussion area might be more appropriate).

**Comment by sone** [comment]
Ok, it's clear now. I thought I have to copy Camomile.vst3 and CamomileLV2.so to the plugin folders but this is just wrong. Sorry.
