### ISSUE TITLE
TTL errors when building EP-MK1

### ISSUE THREAD

**Issue by pave-unpaved** [pierreguillot/Camomile#247]
**TTL errors are reported when attempting to build the [EP-MK1](https://github.com/MikeMorenoDSP/EP-MK1) plugin**

The errors were found on Arch Linux 64 bit, fully up do date.
I use Ardour, but since there are errors in the build, no plugins are produced. All formats produce this error on master, and on dev/v1.0.8, compiled with both `make CONFIG=Release` and just `make`
All example plugins build with no errors.

Steps to reproduce: 
1. download the latest version of EP-MK1 from [here](https://github.com/MikeMorenoDSP/EP-MK1/releases/tag/v2.4)
2. `git clone` the latest version of camomile
3. when running `./camomile -f [file path to ep-mk1]`, the following error is thrown, and all plugins produced are non-functional.
```
Camomile - Plugin Generator
./builds/EP-MK1.vst3
generating ttl EP-MK1 in ./builds/EP-MK1.lv2/EP-MK1.so
can't load method lv2_generate_ttl
error: ./builds/EP-MK1.lv2/EP-MK1.so: undefined symbol: lv2_generate_ttlmv: cannot stat '/home/USER/Camomile/Plugins/manifest.ttl': No such file or directory
mv: cannot stat '/home/USER/Camomile/Plugins/EP-MK1.ttl': No such file or directory
./builds/EP-MK1.lv2
```

**Comment by pierreguillot** [comment]
At first sight, it seems that the problem is related to the plugin EP-MK1, and not Camomile. Perhaps you should create an issue on the corresponding repository and/or try to contact @MikeMorenoDSP?

**Comment by xunil-cloud** [comment]
I have just tested it. For me, to get rid of such error, I need to delete `EP-MK1.so` inside the path that you provided for `-f` option.

**Comment by xunil-cloud** [comment]
Since the `$plugin_input_dir` contains `EP-MK1.so` (which is an VST2 plugin), `EP-MK1.so` inside `$plugin_output_dir` would be overrided.
https://github.com/pierreguillot/Camomile/blob/f624d7015879a228651654d3115c22c56e025a8a/Plugins/camomile#L265
https://github.com/pierreguillot/Camomile/blob/f624d7015879a228651654d3115c22c56e025a8a/Plugins/camomile#L266
