### ISSUE TITLE
feature request: support Data Structures and better support for GOP

### ISSUE THREAD

**Issue by porres** [pierreguillot/Camomile#254]
Hi, I see that GOP abstractions don't work really well, I got some GOP GUI abstractions in ELSE and they don't look ok.

Moreover, I see that camomile does not support Data structures, at least yet. I wonder if there's a reason never to support them or if it's something on the horizon for the foreseeable future. I also have some GOP abstractions in ELSE based on data structures and it'd be great to have tem.

cheers

**Comment by pierreguillot** [comment]
Hi,

Can you give further information about the GOP issue?

The data structure is another subject, I think I already answered to that question perhaps in a discussion or in another issue... but to give a quick answer, no data structure support is not in the todo list. This can be discussed in a discussion.

**Comment by porres** [comment]
> Can you give further information about the GOP issue?

it seems there's some offset when displaying it in the camomile's interface

see the original abstractions here
<img width="512" alt="Screen Shot 2021-04-26 at 14 01 31" src="https://user-images.githubusercontent.com/5360142/116123001-d5f86e00-a698-11eb-83ea-2716463d08e1.png">

and how they're displayed
<img width="438" alt="Screen Shot 2021-04-26 at 14 06 40" src="https://user-images.githubusercontent.com/5360142/116123062-e7417a80-a698-11eb-81cd-d36b72a1b861.png">


I don't understand why one of them (the one on the left) wasn't displayed, I have to investigate

**Comment by pierreguillot** [comment]
Which Camomile version do you use? Can you share the plugin? I guess you use VST3 or AU format with Live on MacOS.

**Comment by porres** [comment]
I'm using camomile 1.0.7, with support for the objects from ELSE. I modified bulgroz and was using an AU => [Bulgroz.component.zip](https://github.com/pierreguillot/Camomile/files/6379031/Bulgroz.component.zip)

**Comment by porres** [comment]
I have no idea why the multi slider doesn't display...

**Comment by pierreguillot** [comment]
The multislider is not part of Pd Vanilla. And it's a bit hard to test your patch as most of the objects are not vanilla. Please send a simple Camomile-vanilla compatible plugin otherwise even I try to change the code to fix the problem I can't load the objects and see if it changes something...

P.S. Avoid Bulgroz for the name, otherwise your example overwrites my plugin ;)

**Comment by pierreguillot** [comment]
Changing the name of the issue would be also useful. There are 2 subjects in one issue.

**Comment by pierreguillot** [comment]
I close the issue because due to lack of activity but feel free to reopen it if you can provide further information.
