### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by Dhrhciebcy** [pierreguillot/Camomile#269]
Hi, forgive me if I ask you this question by writing in the issues, but unfortunately I have not found any answer on the web.
Is there a way to automatically create the .txt file related to the plugin properties (for example, with a program or directly from Pure Data)? Or do you have to write it manually?
Thank you and sorry again
Andry

**Comment by pierreguillot** [comment]
Hi,

You have to write the text file manually. Is there a specific approach that you think is more appropriate?

P.S. Creating a [discussion](https://github.com/pierreguillot/Camomile/discussions) would be more adapted.

**Comment by Dhrhciebcy** [comment]
Hi @pierreguillot,
mine was more of a curiosity since I have created a program (currently only for Windows) that automates "the process of creating a plugin" using Camomile. I also added a section where to insert the manufacturer, if it's an effect and so on.
My idea was to try to automate the process of creating the .txt file through a Pure Data log for example, since this seems to be the most "nasty" thing :(

P. S. I did not know the discussions section, thanks for letting me know

![image](https://user-images.githubusercontent.com/22133554/123518026-73c1e680-d6a4-11eb-9be3-faea41e86ee1.png)

**Comment by pierreguillot** [comment]
Hi,

I'm 100% sure that many users will be interested in this program! When you have something that can be tested or if you can share the project, please create a discussion with the link and/or feel free to link it in the wiki! Thank you :)

**Comment by alex-esc** [comment]
@pierreguillot Hey! I have another question and I didn't wanted to clutter the issue page so I guess ill ask here :)

Can a plugin maker configure his vst to display the generic parameter sliders only?

In other words can you set a plugin to only show the image below and bypass the pure data interface altogether?

![](https://raw.githubusercontent.com/wiki/pierreguillot/Camomile/.images/Parameter-1.png)

Asking because I think that interface is prettier than my average pd patch 🤣

**Comment by pierreguillot** [comment]
> Hey! I have another question and I didn't wanted to clutter the issue page so I guess ill ask here :)

It might be better to create a new discussion.

> Can a plugin maker configure his vst to display the generic parameter sliders only?

No, but it should not be difficult to implement, feel free to create an issue ;)
