### ISSUE TITLE
Midi Noteoff issue

### ISSUE THREAD

**Issue by BalwynVic** [pierreguillot/Camomile#27]
Hi, I am really enjoying Camomile, thank you!
I have a Miditech midi keyboard that sends a note-off velocity of 100 (which is apparently not unusual). When using Camomile in Reaper I am getting a note-on event with a velocity of 100 instead of a note-off
I'm using Windows 10

**Comment by pierreguillot** [comment]
Hi,
I'm really not a MIDI expert so probably, I made a mistake. There is no noteoff object in PD so I thought that when a note event has a velocity value different from 0  it means that the event is note-in. But in fact it could be note-off ? What should I do ? What event should I send to PD ? 
Cheers

**Comment by BalwynVic** [comment]
I am also no expert, and am under the impression the new rule is a note on message with a velocity of 0 is the same as a note off message.
 I think the midi note message comprises (in decimal)
144(+ the channel) : note value : velocity for note on 
128(+ the channel) : note value : velocity for note off
if that helps. 
PD handles the [notein] from my keyboard as you said velocity > 0 = note on and 0 = note off
checking the output of [noteout] from PD, note off is a note on message with a velocity of 0 and records correctly in Reaper.
is that any help ?

**Comment by pierreguillot** [comment]
Ok, I see my mistake. For now, when the plugin receives an event "note on" or "note off", it sends an event "note in" to PD with the velocity. I just have to check if the event is "note on" to send an event "note in" with the velocity, otherwise if the event is "note off", the plugin should send "note in" with a zero velocity.

**Comment by riwid** [comment]
Any news on this bug? Would be really great if it was fixed. Then Camomile can be used as an advanced midi remapper, randomizer etc. 

For myself I want to be able to map midi notes and send them to an external Volca drum machine from Bitwigs default drum note container. I would be very happy it was possible.

**Comment by erwan35** [comment]
Hello,

I might have the same kind of problem.

As mentioned in #44 when a key is pressed, the note is not released. You can test the attached patch to try to reproduce the issue.

[synth-pd.txt](https://github.com/pierreguillot/Camomile/files/752925/synth-pd.txt)

Cheers
Erwan

**Comment by pierreguillot** [comment]
This should be solved with the new major version (coming soon)
