### ISSUE TITLE
List split has different output in Camomile from what is expected

### ISSUE THREAD

**Issue by werldc** [pierreguillot/Camomile#272]
Only tested in Windows 10, DAW:Reason 11, VST2 v.1.0.6 (due to later versions of Camomile not having VST2 support anymore).

Attaching print at each outlet from [list split] you can see that outlets does not do what it is supposed to.
-----------------------------------------------------
In Pure data (from reference files):
[1 2 3 4 5(
|
[list split 2]
|	| 	|
Outlet 1: first n elements of the incoming list. 
	Outlet 2: rest of the list.
		Outlet 3: whole list if incoming list shorter than n.
------------------------------------------------------
Observed in Camomile:
[1 2 3 4 5(
|
[list split 2]
|	| 	|
Outlet 1: bang. 
	Outlet 2: whole list.
		Outlet 3: ?
------------------------------------------------------

Separate question, is there a possibility of adding VST2 support again?

**Comment by pierreguillot** [comment]
Hello,
I tested in Reaper on Windows with Camomile 1.0.6 (VST2) & 1.0.7 (VST3) and both work well. Can you share your plugin?

**Comment by werldc** [comment]
Hi, 

My mistake, after another look there was no problem with [list split].

Was trying to get just the filename from the directory returned from [r openpanel].
But didn't catch that Camomile returns \ in directory instead of / like pd.
So list split works exactly as it should :)
