### ISSUE TITLE
[savestate] gives plugin error

### ISSUE THREAD

**Issue by porres** [pierreguillot/Camomile#277]
I have an abstraction with [savestate] and it includes lines beginning with **#A** in the file. Camomile complains and says '#A object not found'. The patch then doesn't behave as expected. We're using camomile 1.0.7 with support for ELSE externals, built and saved with Vanilla 0.51-4. Tested on macOS 10.14.6 and Live 11.

![IMAGE 2021-10-30 20:55:24](https://user-images.githubusercontent.com/5360142/139561503-8072a202-996a-478e-9207-3d39195b1f59.jpg)

**Comment by pierreguillot** [comment]
I tested with Camomile 1.0.7 and it works well. There could be a problem in your patch or you might have introduce a bug when compiling your own version of Camomile. I can't help you sorry.

**Comment by porres** [comment]
We didn't really change anything in our version, but I can try a full vanilla version with just regular camomile

**Comment by pierreguillot** [comment]
>  can try a full vanilla version with just regular camomile

Yes, that would be better. 

And providing your patch, the plugin text file, etc. would be helpful ;)
