### ISSUE TITLE
Metro object

### ISSUE THREAD

**Issue by XelaHcim** [pierreguillot/Camomile#29]
Hello,
It seems that the metro object doesn't respond correctly.
Here is a simple test with a [metro] applying a random frequency to an [osc~] object : it seems impossible to change its rate.

Tried with Renoise(x64) 3.1, Camomille 0.7 VST 32bit, Windows10 64bit
[metro-test.zip](https://github.com/pierreguillot/Camomile/files/269023/metro-test.zip)

**Comment by pierreguillot** [comment]
Hi,
For me it works, I think you forgot to use the object [change] after [r $0-metro_rate] and [r $0-metro_start]. So the [metro] receives the message "1" at every sample block, and it sends a "bang" at every block.
see here: https://github.com/pierreguillot/Camomile/wiki/Frequently%20Asked%20Questions 
(section "I receive messages even if the value of a parameter has not changed, why ?")

Cheers

**Comment by XelaHcim** [comment]
My bad : it's all working fine now.
Thanks for your amazing work!

**Comment by pierreguillot** [comment]
Thanks !
