### ISSUE TITLE
netreceive on Windows 7

### ISSUE THREAD

**Issue by oliverstotz** [pierreguillot/Camomile#30]
First: Congrats and thanx a bunch for this great work !

Some Issue i encountered: (Windows 7 64bit, Camomille 32bit, Ableton Live 8)

1.) is "netreceive" inside a camomile patch supposed to work ?

your example patch "camo.netsend.pd" that sends messages over netsend to a receiving PD patch works alright, but how about the other way round ? 
i had no luck when i tried it.

 the camomile console says :

"Camomile 0.0.7 for Pure Data 0.47.0
netreceive: failed to sett SO_BROADCAST"
Warning in patch camo.netsend_receive_test.pd: Connect parameter is duplicated !

i attached my patches in this post

[camo.netsend_receive_test.zip](https://github.com/pierreguillot/Camomile/files/279696/camo.netsend_receive_test.zip)

2.) is there any hope of 3rd party externals being supported soon ?

best

oliver

**Comment by pierreguillot** [comment]
1) Thanks, I'll try to see what happens.
2) Yes, there is already an issue #9 
Cheers

**Comment by oliverstotz** [comment]
thank you very much ! 
(P.S.: sorry for the confusing subject title. It's because I had some trouble with midi input as well when i was writing the post. but it turned out to be a mistake on my side. MIDI input is working ok ;-))

**Comment by pierreguillot** [comment]
I can't check it and as all the mechanism is changed in the next release I close it for the moment.
