### ISSUE TITLE
Number ID for parameters

### ISSUE THREAD

**Issue by alfonso73** [pierreguillot/Camomile#31]
Hi Pierre,
many many thanks for this great tool, at least i can incorporate my max-ish things in hosts different than Ableton Live!
The way parameter id is managed makes very difficult to design patches on the go.
Instead of order of creation could it be possible to incorporate an ID as for example
"1_gain_dB" where the first number is the ID, second string is parameter name and third string is the kind of unit used by the paramenter. I guess would be the easiest way to rearrange parameter order when a patch design change over time.
best!
a.

**Comment by pierreguillot** [comment]
Hi,
I thought about it. But I don't think that's the proper solution. There are already too many restriction with this approach. I think the best solution is to use a text that describes the plugin, it would be more dynamic (perhaps using the text object)...

**Comment by alfonso73** [comment]
Hi Pierre, yes I think that the approach you suggest is even better. A kind
of configuration text file. Nice!
best
a.
Il 18/giu/2016 10:12, "Pierre Guillot" <notifications@github.com> ha
scritto:

Hi,
I thought about it. But I don't think that's the proper solution. There are
already too many restriction with this approach. I think the best solution
is to use a text that describes the plugin, it would be more dynamic
(perhaps using the text object)...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pierreguillot/Camomile/issues/31#issuecomment-226928795>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADFK4uHj4AbYrOk2UoSY7kid2-8rc5zvks5qM6hjgaJpZM4I3JCL>
.

**Comment by pierreguillot** [comment]
This should be solved with the new major version that use messages.
