### ISSUE TITLE
Ableton loads multiple copies of the same plugin

### ISSUE THREAD

**Issue by MrcRmg** [pierreguillot/Camomile#318]
Hi everybody,

I have an issue with camomille, thank you in advance for some hints.
I work in Ableton 11 on windows 10 64bit.

 If I have just one camomille plugin inside my plugin directory , Ableton will load it and will work.

I have more plugins in the the plugin directory,  each one with his own directory and his properly named files
 
(Plugins/plugin1/plugin1.pd, plugin1.txt etc. etc.)
(Plugins/plugin2/plugin1.pd, plugin2.txt etc. etc.)

When I try to load let s say plugin2, in Ableton will show up again plugin1, so I end up having loade  more copies of plugin1 and no plugin 2.

Any hints?
Thank u in advance

Marco

**Comment by pierreguillot** [comment]
Hi Marco,

It might be related to the [plugin code](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#all-plugin-properties). Is the code unique for each plugin?

**Comment by MrcRmg** [comment]
I guess so, thank you so much!

> Message ID: ***@***.***>
>

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
