### ISSUE TITLE
Sample position from $0-playhead

### ISSUE THREAD

**Issue by alfonso73** [pierreguillot/Camomile#32]
Hi Pierre,
would be great to retrieve sample position from the playhead structure.
This is required for timing precision when dealing with audio buffers and the likes.
best
a.

**Comment by pierreguillot** [comment]
I think you can already do it. Have a look [here](https://github.com/pierreguillot/Camomile/wiki/How%20to%20create%20patches%20for%20the%20plugin#midi-events). Or is it something else ?

**Comment by alfonso73** [comment]
As far as I can see there's no sample position value but only bpm, ms, ppq
and time signature. As far as I remember the sample position is given by
the variable samplePos in the VstTimeInfo structure of VST SDK. I don't
know how this structure is presented in Juce.
Is an host play state retrievable?
Il 18/giu/2016 10:17, "Pierre Guillot" <notifications@github.com> ha
scritto:

**Comment by pierreguillot** [comment]
Yes, you're right. There is timeInSamples in Juce. All the available infos are described [here](https://www.juce.com/doc/structAudioPlayHead_1_1CurrentPositionInfo). Feel free to tell me if other ones are important.

**Comment by alfonso73** [comment]
Hi Pierre,
i think

int64 AudioPlayHead::CurrentPositionInfo::timeInSamples

double AudioPlayHead::CurrentPositionInfo::ppqPositionOfLastBarStart

bool AudioPlayHead::CurrentPositionInfo::isPlaying

bool AudioPlayHead::CurrentPositionInfo::isRecording

double AudioPlayHead::CurrentPositionInfo::ppqLoopStart

double AudioPlayHead::CurrentPositionInfo::ppqLoopEnd

bool AudioPlayHead::CurrentPositionInfo::isLooping

Everything of the above can be really useful for looping devices and other time related stuff.

a.

**Comment by pierreguillot** [comment]
Everything should be integrated in the next release
