### ISSUE TITLE
Xcode project file missing

### ISSUE THREAD

**Issue by grrrr** [pierreguillot/Camomile#33]
There seems to be a file missing for the Xcode project. When i try to open the Builds/MacOSX/Camomile.xcodeproj file the following error is shown in a pop-up window:

"Project /Users/thomas/Documents/dev/Camomile/Builds/MacOSX/Camomile.xcodeproj cannot be opened because it is missing its project.pbxproj file."

**Comment by pierreguillot** [comment]
The problem is already fixed on the dev branch v0.0.8. For the moment I suggest you to use the projucer from Juce and to regenerate the Xcode project with Camomile.jucer.

**Comment by pierreguillot** [comment]
The new branch solves this
