### ISSUE TITLE
Relative/absolute path

### ISSUE THREAD

**Issue by XelaHcim** [pierreguillot/Camomile#36]
Hi,
It seems that Camomille use absolute paths only to load pd~patches, which makes the files organization quite delicate as it's very relying on the file tree.
Would it be a good (and feasible!) idea to use also relative paths from the DAW project file to load patches?
In this way, we could move folders easily without modifying the relative path between patches and the project file.

To go further, we could imagine a "plugin maker" which would create a new totally independent and functional .dll with the patch algorithm already "in it" with no need to load it from elsewhere.
In fact, exactly like pluggo was used with maxmsp4.

Anyway, those suggestions are only ideas to make the file management or sharing more flexible/robust, and to have a more 'compact' use of this excellent application.
Hope that was clear enough, and sorry for my childish english.

Alex

**Comment by pierreguillot** [comment]
Hi,
We can't retrieve the path of the project within the plugin. Another option would be to let the user specify the path of the project and then it would be feasible to define the relative path of the patch.
The "plugin maker" would be the best solution. I already created an issue for it #24. It could also help to easily solve these issues #23 #26 & #31. I don't know the feasibility to generate an "all-in-one" .dll on Windows and Linux but I know it's possible on Mac because it uses a bundle instead of a simple .dll.

**Comment by XelaHcim** [comment]
Thank you for this clear reply.
I don't really know the software kind of restrictions, so I have a bad idea of those solutions feasibility.

In a first stage, I think it would be sufficient to add a dialog window to relocate the pd~ patch when camomille is unable to find it (modified location), and especially **reload parameters from the last occurrence**. 
Currently, those parameters are lost. An actual way to do that is to 'fix' those parameter values with static automations, which are not lost in case of removed patch.

I think your vision of a "meta-plugin" is the more efficient and elegant.
Do those 'consolidated' versions could be shared directly, in a compact way, with other persons?
The sharing experience would be really improved : a lot of people, who are not really into pd~ and those sort of things, could use more easily plugins made by the pure data community.

**Comment by pierreguillot** [comment]
The approach of the next release will include the patches with plugin so the relative/absolute path won't be an issue.
