### ISSUE TITLE
latest git build error

### ISSUE THREAD

**Issue by davephillips** [pierreguillot/Camomile#38]
Build fails with JUCE 4.2.4 on Fedora 21 x86_64 GCC 4.9.2.

Compiling InstanceProcessor.cpp
../../Source/InstanceProcessor.cpp: In function ‘juce::AudioProcessor* createPluginFilter()’:
../../Source/InstanceProcessor.cpp:467:28: error: cannot declare variable ‘lookAndFeel’ to be of abstract type ‘CamoLookAndFeel’
     static CamoLookAndFeel lookAndFeel;
                            ^
In file included from ../../Source/InstanceProcessor.cpp:9:0:
../../Source/LookAndFeel.hpp:35:7: note:   because the following virtual functions are pure within ‘CamoLookAndFeel’:
 class JUCE_API  CamoLookAndFeel  : public LookAndFeel
       ^
In file included from ../../../JUCE-code/modules/juce_gui_basics/juce_gui_basics.h:215:0,
                 from ../../../JUCE-code/modules/juce_audio_plugin_client/juce_audio_plugin_client.h:52,
                 from ../../Source/../JuceLibraryCode/JuceHeader.h:19,
                 from ../../Source/InstanceProcessor.hpp:11,
                 from ../../Source/InstanceProcessor.cpp:7:
../../../JUCE-code/modules/juce_gui_basics/menus/juce_PopupMenu.h:709:28: note: 	virtual juce::Component* juce::PopupMenu::LookAndFeelMethods::getParentComponentForMenuOptions(const juce::PopupMenu::Options&)
         virtual Component* getParentComponentForMenuOptions (const PopupMenu::Options& options) = 0;
                            ^
../../../JUCE-code/modules/juce_gui_basics/menus/juce_PopupMenu.h:711:22: note: 	virtual void juce::PopupMenu::LookAndFeelMethods::preparePopupMenuWindow(juce::Component&)
         virtual void preparePopupMenuWindow (Component& newWindow) = 0;
                      ^
Makefile:204: recipe for target 'build/intermediate/Debug/InstanceProcessor_bc7e525e.o' failed
make: *** [build/intermediate/Debug/InstanceProcessor_bc7e525e.o] Error 1

**Comment by pierreguillot** [comment]
Can you give me the branch/commit and what did you do to compile ?

**Comment by davephillips** [comment]
$ git branch
* master

branch is up-to-date with 'origin/master'

**Comment by pierreguillot** [comment]
The problem is in juce_PopupMenu.h. with 
`virtual void preparePopupMenuWindow (Component& newWindow) = 0;`
and 
`virtual Component* getParentComponentForMenuOptions (const PopupMenu::Options& options) = 0;`
At master/origin 3760a53, there is no such methods for PopupMenu in Juce, I think you try to compile with a different Juce version. Why the Juce's path starts with `../../../JUCE-code/...` ? Did you follow this [instruction](https://github.com/pierreguillot/Camomile/wiki/Compilation) ?

**Comment by davephillips** [comment]
Ah, thanks, I was creating my own makefile from the jucer file. I started over, from the instructions this time, everything built without error. I tested the plugin in Bitwig 1.3.13, it works fine so far. I think the issue can close, sorry for the noise.
