### ISSUE TITLE
Parameter not available to MIDI learn with Ableton

### ISSUE THREAD

**Issue by loicreboursiere** [pierreguillot/Camomile#40]
Hello Pierre, thanks for this awesome project !

Camomille works well with Live, but I can't seem to map plugin controls on a MIDI controller using the MIDI learn function from Ableton. Is it not implemented or am I missing something here ? 
Automations work fine though so parameters are transfered to Live, but not to MIDI learn.

I'm running Live 9.6.1 under Mac osx 10.10.5.

Loïc

**Comment by pierreguillot** [comment]
No, I don't think you missed something. I don't have Ableton and I'm really not a MIDI expert as I practically never use the MIDI so I surely missed something (for my personal knowledge, MIDI learn is the feature that automatically connect MIDI events to parameters, am I right ?). I don't see any method/function in the JUCE that enables this feature but as the main goal of this API is to create audio plugin, it sounds strange that they forget this functionality. I'll investigate deeper in the subject but I suspect Ableton of enabling this feature only for the synthesizer plugins. In this case, I already planned to create two versions of the plugin (effect & synthesizer) for the next release.

**Comment by loicreboursiere** [comment]
Yes, Midi Learn is the function that connect a parameter to a midi controller being moved. 
I've built and try the Gain plugin Juce example in the juce/Examples/PlugInSamples directory and its slider is recognized by Live so it can be MIDI mapped. 
I don't know if it helps.

**Comment by alfonso73** [comment]
that's very strange any VST parameter should be exposed as a MIDI learn automation target in Ableton..i go check now! any new work goin' on on the great Camomile? (external objects, etc..)

**Comment by alfonso73** [comment]
just tried with camo.am~...it just wotks fine

**Comment by loicreboursiere** [comment]
Weird, my usual routine (Cmd + M > click the parameter > move the controller) doesn't work for me, even with camo.am~.

**Comment by alfonso73** [comment]
just a question...but are you acting on the actual camomile gui or on the parameter  exposed in the live device area? the first won't work.

**Comment by loicreboursiere** [comment]
Ok ! My bad, second one worked perfectly ! 
Why can't the camomille parameters can't be exposed directly through its gui ?

**Comment by pierreguillot** [comment]
Thanks for these clarification! I'll try to figure out what the problem with the GUI. 
@alfonso73 For the moment, I'm too busy by other works to finish the next release but as soon as I can (I hope in January), I'll come back to this project.

**Comment by alfonso73** [comment]
great! thanks fpr the info!

**Comment by pierreguillot** [comment]
So we'll check that with the next release v0.1.0 (coming soon) for the moment I close the issue

**Comment by alfonso73** [comment]
Hi Pierre,
this is an Ableton Live way of working.
It won't permit to midi learn on the VST's UI but on a special Configure
panel that can be accessed by the Ableton VST "shell" so to speak.
So it's not a Camomile issue. For every VST loaded in Ableton Live things
work like this.
Just close the issue.
Best!
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone
