### ISSUE TITLE
OSX: AU and VST not showing as instrument

### ISSUE THREAD

**Issue by boonier** [pierreguillot/Camomile#41]
Tested in Renoise and it's not showing as a normal plugin instrument. Is that a known issue or normal behaviour?

Thanks

**Comment by pierreguillot** [comment]
Yes, I know. There will be two versions (fx & instrument) for the next release.

**Comment by boonier** [comment]
@pierreguillot Great! I since discovered that using the AU/VST alias function in Renoise you can actually control a device that accepts midi inputs - include notes. thanks

**Comment by damian0815** [comment]
Same problem in Cubase (OSX)

**Comment by damian0815** [comment]
(BTW thanks for making this! :)
