### ISSUE TITLE
Note off issue

### ISSUE THREAD

**Issue by erwan35** [pierreguillot/Camomile#44]
Dear Pierre,

First of all, thanks for this very cool piece of software :)

A very simple pd patch is attached to this bug report. I'm using Camomile-V0.0.7-beta.zip and especially the 64 bits .so for Linux (ubuntu + kxstudio).

Camomile is loading fine on [Carla](http://kxstudio.linuxaudio.org/Applications:Carla) but the problem is that camomile is not getting the note off.

Do you think that it might be related to issue [#27](https://github.com/pierreguillot/Camomile/issues/27) ?

Cheers
Erwan

[synth-pd.txt](https://github.com/pierreguillot/Camomile/files/752540/synth-pd.txt)

**Comment by pierreguillot** [comment]
Hi,
Yes I think this is the same problem. Can you comment #27 and close this one ? 
Thanks !
