### ISSUE TITLE
Numbers and symbols

### ISSUE THREAD

**Issue by JMC64** [pierreguillot/Camomile#46]
Hello Pierre, 
Many thanks for this nice plugin and the work done.
I am not sure the following are issues  :  symbol and numbers do not react in the GUI. 
I tried the following very simple patch (with [number2] is the same)  to intercept which note is played. In the following, not all connectors are showed : 
[notein]
|  
[Number]                                Properties of Number : send message $0-notevalue
|  
[noteout]

Gui object : 
------------------------------------|
                                                     |
[Number]                                     |   with properties : receive message : $0-notevalue , label : NoteNumber
------------------------------------|

1) the GUI [number] labelled NoteNumber does not show in the window
2) when using [number2] instead of [number], the item is there but there is no sign that it is being triggered whenever I am sure that the midi notes are passing thru the plugin in the DAW (reaper) .
3)  same thing happens with [symbol]. They  do not show in the GUI window.

Would you be so kind to help ?
Many thanks.

**Comment by pierreguillot** [comment]
Hi,
With the markdown syntax, I can't understand your patch. Can you join it?
Anyway, the GUI is not updated when the value is changed from the DAW ([FAQ](https://github.com/pierreguillot/Camomile/wiki/Frequently%20Asked%20Questions), #22, [Create patches](https://github.com/pierreguillot/Camomile/wiki/How%20to%20create%20patches%20for%20the%20plugin)) but you can use the print object to print the messages in the console.

**Comment by JMC64** [comment]
[testmidisimple.zip](https://github.com/pierreguillot/Camomile/files/819349/testmidisimple.zip)

Hello Pierre,
Here is the file. 
Somehow, if what comes from the DaW can not be shown in the GUi then I understand better.
But number and symbol don't show.
I tried to comment the source. hope this helps.
Thank you for your help.

**Comment by pierreguillot** [comment]
Yes, number and symbol was not implemented because there is already nbx (number2) and because symbol can't be used as a parameter. Anyway I'm refactoring everything perhaps I'll dissociate the GUI from the parameter and this GUI will make sense but for now they are useless.
