### ISSUE TITLE
Trouble with [loadbang]

### ISSUE THREAD

**Issue by gilbertohasnofb** [pierreguillot/Camomile#49]
I am having some troubles with [loadbang]. I wanted to use it to send initial messages to the sliders to set the initial positions. It works fine in Pd, but all my sliders start at `0.0` in Camomile.

**Comment by pierreguillot** [comment]
In the [FAQ](Frequently-Asked-Questions), there is a section about the loadbang perhaps this is your issue.

**Comment by gilbertohasnofb** [comment]
@pierreguillot Thanks for the reply, Pierre. I have seen that section in the FAQ, but I am not sure if it's related or not. According to the FAQ, __[loadbang]__ works the first time a patch is opened but for me it doesn't work at all. This is my patch:

![screenshot from 2017-04-16 15 52 08](https://cloud.githubusercontent.com/assets/5700795/25071641/eedd8036-22bc-11e7-9097-f70942582ac5.png)

And here is how it looks as soon as I open it in the DAW (notice how the sliders are both at `0.0` instead of `0.5`):

![screenshot from 2017-04-16 14 38 06](https://cloud.githubusercontent.com/assets/5700795/25071644/03792374-22bd-11e7-8285-1ad1a6055b4d.png)

**Comment by pierreguillot** [comment]
$0 in a message works in Purr Data (or Pd-l2ork) but not in Pd vanilla you need to put it in an object like that 
<img width="100" alt="cpt" src="https://cloud.githubusercontent.com/assets/1409918/25072419/15529362-22ce-11e7-8ffb-175e43e08e4e.png">

**Comment by pierreguillot** [comment]
Anyway it seems that the plugin still have an issue with the initialization...

**Comment by gilbertohasnofb** [comment]
I completely forgot that vanilla doesn't accept `$0` inside a message, my bad! I have modified my test patch but there is still an issue, though a different one this time: those sliders (which are receiving `$0-wetR` and `$0-dryR`) are now starting at `1.0` even though the __[loadbang]__ sends a value of `0.5`.

![screenshot from 2017-04-16 19 48 27](https://cloud.githubusercontent.com/assets/5700795/25073050/1b333768-22de-11e7-906f-17d69798bae7.png)

![screenshot from 2017-04-16 19 49 02](https://cloud.githubusercontent.com/assets/5700795/25073049/1b32f06e-22de-11e7-90ec-af05468587c3.png)

**Comment by pierreguillot** [comment]
Yes I noticed ! It seems that if the initialization value is not 0, the value is set automatically to the maximum, I must have made a mistake somewhere... Anyway, I have to improve the parameters management for the next release.

**Comment by gilbertohasnofb** [comment]
:+1: Great, thanks for all the feedback, Pierre! I look forward to the next release.

**Comment by pierreguillot** [comment]
It should fixed in the next major version (coming soon)
