### ISSUE TITLE
Change object

### ISSUE THREAD

**Issue by Paulinho-E** [pierreguillot/Camomile#53]
Bonjour, 
Un grand merci pour les immenses possibilités qu'ouvre votre plugin.

I use Windows 7 64bits and Reaper 32 and 64bits. I have been trying to control a [metro] with a toggle (and a slider for speed) for quite a while, then I understood I needed a [change] object after the toggle : otherwise the metro is restarted continuously and it gets impossible to control its speed. Maybe this necessity could be made a little clearer in your FAQ and tutorial. You mention it in the FAQ, but the implications were not obvious (to me at least!). 
Also the number-1 box and bang object are invisible in the GUI with my machine, is this normal?

Bravo encore et merci!

**Comment by pierreguillot** [comment]
Merci !
Yes, I know that the update of the parameters is not obvious even if it's logic. I wanted to update the wiki pages but I don't have time. Anyway, anybody can edit the wiki pages so feel free do it if you want. You can tag me if you want me to review. And whatever you do I can rollback to a previous state so feel free to test :)
For the last problem can you create another issue and attach a patch (and a screenshot)?

**Comment by pierreguillot** [comment]
Sorry number-1 and bang are not supported yet. You can use numbox instead of number-1 . And the communication between the DAW and Pd works on parameters, a bang can't be a parameter so it would be unusable. If you want to generate bang, you can use a toggle with the [change] object.
