### ISSUE TITLE
Minor issue with purr-data

### ISSUE THREAD

**Issue by elsueno** [pierreguillot/Camomile#55]
Purr-data allows spaces in labels.
When camomile is used in ableton the associated patch of a camomile plugin instance will not be loaded when the project is reopened.
Thats probably nothing that needs fixing but should be mentioned in the wiki in the section "How to create patches for the plugin".

cheers!

**Comment by pierreguillot** [comment]
I already mentioned the fact that the spaces are not allowed in the label section. And it would be a never ending job if I want to specify the incompatibilities of each distribution of Pd with vanilla. I guess it's more the job of their developers.
