### ISSUE TITLE
Playhead in vst

### ISSUE THREAD

**Issue by marcoctn** [pierreguillot/Camomile#56]
hi, I'm on 0.0.7 and can't get the r $0-playhead to work, I'm probably missing something but can't find any more info than the img you posted on the wiki page.
Do you have by any chance a patch where "r $0-playhead" is implemented to share?
thanks a lot. Camomile is amazing.

**Comment by pierreguillot** [comment]
The patch **camo.cornetto**. Don't forget, you can use the `[print]`object and check the console in the plugin to debug. Thanks and keep me informed.

**Comment by marcoctn** [comment]
Thanks!!

I really live camomile. Are you still developing it?

Sent from my iPhone

On 3 Jul 2017, at 07:42, Pierre Guillot <notifications@github.com<mailto:notifications@github.com>> wrote:


The patch camo.cornetto. Don't forget, you can use the [print]object and check the console in the plugin to debug. Thanks and keep me informed.

**Comment by pierreguillot** [comment]
I would love to but I can't right now, I really hope soon. Nevertheless I made some tests lately with the new version of Pd and I published small tutorial videos so I'm still working on it :)
