### ISSUE TITLE
No window when trying to open a file (Linux)

### ISSUE THREAD

**Issue by korakios** [pierreguillot/Camomile#57]
Hi,
I tried camomile on both Ardour and Carla host but when clicking to open a file nothing is shown.
I am using AVLinux which has xfce and thunar .
On windows camomile let me choose the file .

If more info is needed please let me know.

**Comment by trebmuh** [comment]
Kind of same here. Tried with Qtractor. When I launch Camomile, the GUI shows up but when I click File -> Open, then I've got a total freeze of the Camomile GUI + host.
Debian stretch up-to-date. Qtractor 0.8.4.

**Comment by pierreguillot** [comment]
Perhaps this is related to #21 ?

**Comment by pierreguillot** [comment]
I assume this is the same problem. I'll check that with the next release.
