### ISSUE TITLE
Linux support ?

### ISSUE THREAD

**Issue by b2renger** [pierreguillot/Camomile#6]
How about it ?

this project looks awesome and I see that a windows version is planned but I would really love to see a linux version too.

**Comment by pierreguillot** [comment]
My mistake, in fact this is already planned and before the Windows version !

**Comment by b2renger** [comment]
Awesome I'd love to help when it's ready !

**Comment by pierreguillot** [comment]
It's ready (64bit). I tested with Ardour but I use a virtual machine so I didn't go far away... If you can give feedbacks, this would be really helpful !

**Comment by b2renger** [comment]
Yes :) I've seen it and tested it works fine in ardour 4 on ubuntu 14.04 !

I will go further later on and give you some feedback with great pleasure.
