### ISSUE TITLE
Plugin Information

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#61]
So I'm working on a new major release. It means that there will be a lot of changes ! The plugin will be used as some kind of a meta plugin to create other plugins with specific names (and all the plugins/patches will have their own configurations, their own presets, etc.). Another big change is that the parameters are no more determined depending on the GUI (graphical user interface). You'll still be able to change their values with the GUI if you want but their creation won't depend on it. It's not ready for the moment (I working very hard on it) but I would like to have some of your idea and feedback mostly on this subject:

To improve the improve the plugin support by most of the DAW, I need a way to describe the plugin functionalities:
- The parameters
- The orignal programs (presets)
- The channels configurations supported
- The options 
   - MIDI in support  (mostly for optimization)
   - MIDI out support  (mostly for optimization)
   - Playhead (mostly for optimization)
   - MIDI only (no audio)
- The unique ID of the plugin (see #45)

For the moment, my choice has been to use this syntax to  describe the plugin functionalities:
```
param 1 -name Frequency -label Hz -min 0 -max 22050 -default 220;
param 2 -name Volume -label dB -min 0 -max 100 -default 0;
param 3 -name Mute -list Off/On -default On;
param 4 -name Dummy -nsteps 5 -default On -auto false -meta false;
program 1 John;
program 2 Hammond 321 12;
channels -inputs 1/2/8/12 -outputs 1/2;
options -midiin true -midiout true -playhead true -midionly false;
uniqueid zert;
```
Note: What is important about parameters is the index (#31), everything else is facultative and what is important about program are the index and the name (the following information are the values of the parameters for this program but the patch will receive a notification that a program has been loaded and will be able to change internally the parameters values).

The first advantage is that it's compatible with the Pd object [text]. Finally I guess it will be in a text file next to the main patch (.nfo ?). What do you think of it? Any comment is welcomed ! @coderofsalvation @alfonso73 @XelaHcim or any other ;)

**Comment by alfonso73** [comment]
Hi great news!
It seems a pretty good approach!
A few sparse ideas open to discussions.

1. Specify a step size for parameters (like 1 or 0.1 0r 0.0001 etc.)
2. Specify paramteres with discrete values (for menu, enums, buttons etc..think about a multimode filter with LPF/HPF/BPF i.e.)
3. Specify wich grade of resolution is needed for the playhead (i.e. if samplePos is needed or not, if it's not needed by a specific plugin i guess we can spare some cpu...)
4. Communicate to the host the plugin latency (in case of use of FFT stuff or any latency relevant process)
5. Be able to save the preset in standard .fxp/.fxb VST form via the various DAW gui (could be a simple link to the text object?)

a.

**Comment by pierreguillot** [comment]
Thanks 
1. Already done: Step size depends on the number of steps `-nsteps` and the minimum `-min` and maximum `-max`. If you the number of steps is 2 and the range 1, the step size is 0.5 for example.
2. Already done: There are two "kinds" of parameters, classical numeric parameters and enum/list parameters that you can create with the option `-list` for example `-list Off/On` or `-list LPF/HPF/BPF`.
3. For the moment there is only a global playhead support option. I don't really know the CPU gain, I have never compare. I think an option for each play head information would be pretty boring to setup. Do you think we can imagine some kind of sets of information ? I never really used play head information so I don't know if it's relevant. Something like `-playheadstate` for `isPlaying`, `isRecording` and `isLooping`for example...
4. Great !  An option like `-latency 3000` in ms seems good?
5. The program should act like default presets but with your DAW, you should be able to save new presets. In this case, the plugin write the value of each parameter in the xml format but the files are managed by the DAW.

**Comment by alfonso73** [comment]
1. Great!
2. Great!
3. Time in samples is very important for time critical process. Nut for a
simple midi sequecer ppq info should be enough. I'd say lets try two
different sets of time info somethinh like -timeInfo -hiResTimeInfo.
4. I guess that shoud be a real time thing. If a process that use
overampling is implemented, if the user can change the oversampling factor
the plugin latency would change.
Juce includes this two methods
https://juce.com/doc/classAudioProcessor#abae54a8c1bcfd88bcba9d42b752e006d
and
https://juce.com/doc/classAudioProcessor#ac902e27eb0950adac57bb69680b6e709
that i guess can be useful.
5. Great!

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
3. Can you tell what should be in each option? To have something more dynamic and informative than the previous version (that sends the information via a list), the plugin send now the information separately. So in the patch, you have to do something like `[receive playhead] -> [route isLooping]`. But I think that the CamelCase (`isLooping`, `isPlaying` etc.) is not very adapted. Perhaps something more simple like `looping`, `playing` is more in harmony with the Pd syntax.

4. For the moment I just implemented `getTailLengthSeconds()`. I think if you initialize with the biggest value it should work. In this case, the worst that can happen is to generate a few seconds of silence. I have to look further `set-getLatencySamples()` but you're right it's most a real time (even if JUCE say *The processor should call this as soon as it can during initialization*). Real time changing of this can be complicated to implement. For the moment I'll add an option `-latency`, and I'll try to find a good way to change this in real time.  

I'll also try to add an option that enable the fx or the instrument option. Normally it should be a different plugin but I think I can manage that with the same small hack that I use for the plugin name and the plugin ID.

To Do:
6. Latency
7. FX & Instrument

**Comment by alfonso73** [comment]
Hi Pierre, today i'm super busy...so i'll think a bit better tomorrow evening.
But as a quick thinking...
3. I'd divide things in pretty slow rate infos (isPlaying, isLooping, Time signature and the likes), medium rate infos as BPM (because with time automation in daw this can be pretty fast), fast and time critical things like (in order of increasing resolution) time in ppq, time in seconds, time in samples. But tomorrow evening i'll give you some more precise idea.

4. Latency is crucial for frequency domain things mostly so i guess it's a pretty advanced one. I'll think better about this to..

**Comment by pierreguillot** [comment]
I've changed a bit the syntax of the simplify the code (for example, now each option has its own line). 

The question is for the channels' configurations. It can be something like:
```
inputs 1 2 3 4;
outputs 1 2;
```
that define the number of inputs and outputs supported but it means that the plugin can have 4 inputs and 1 output. Another solution would be to define a set of buses. Something like:
```
buse mono mono
buse mono stereo
buse stereo stereo
buse 8 8
```
where the 1st value define the input configuration and the 2nd value the output configuration. In this example you can have a mono input with a stereo output but you can't have a stereo input with a mono output

**Comment by alfonso73** [comment]
Hi Pierre,
i think that this

inputs 1 2 3 4;
outputs 1 2;


is way better, more flexible.

I don't remember if a VST can inform the host about in/out names, in
case a thing like

inputs (1, name) (2, name) (3, name) (4, name);

outputs (1, name) (2, name);


would be perfect!




www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
The problem I have with distinct inputs and outputs is that the plugin can possibly have a 1-2 or 2-1 input-output configurations even if you only want 1-1 or 2-2. So I think the second option is more flexible because you can specify exactly the input-output configuration. 

The "name" syntax is another problem. I think the plugin can use both number and "name". For example, `buse 2 2` means that it accepts whatever configuration that has 2 inputs and 2 outputs but `buse stereo stereo` means that it accepts only stereo configuration (that's different). So you could have something like:
```
buse mono mono
buse mono stereo
buse 2 2
```

What's important is that the words mono/stereo/quadraphonics/ambisonic/etc. specify standard configurations of sets of channels. So for example, if the plugin accepts an ambisonic input other ambisonic plugins can be plugged with the plugin. 

A last, naming the channel can be an option but that increases the complexity. Most of the time, you don't need to specify the names of the inputs and the outputs (I rarely see specific names of inputs and outputs do you have example?). And in the case of standard configurations, the names are directly provided (like W, X, Y & Z for ambisonic).

**Comment by elsueno** [comment]
For ambisonics it's actually not that important because nowadays it's all ACN but it can be very useful for stuff like compressors with sidechain or plugins that morph two sounds or generally synthesizer patches with different audio and control inputs...

**Comment by alfonso73** [comment]
I still think that flexibility is the most important thing.
The internal plugin process is what decide how to treat inputs and outputs.
A drum synth/sampler could have i.e. 8 separate mono outputs for 8 separate
synth chains.
A vocoder could habe 2 stereo inputs for external carrier and modulator.
A compressor could have a stereo input and a mono one for sidechain.
An FFT morph thing can have 2 sets of stereo inputs...a monoizer plugin can
have a stereo in and a mono out..
And a lot of other interesting things.
Treating ambisonic stuff can simply be done with such a flexible routing.



www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
I'm agree. Ambisonics is just an example. There is a difference between mono and 1 channel or stereo and 2 channels (I would never use stereo inputs for carrier and modulator. Stereo is a loudspeakers/microphones arrangement). 

Anyway, with distinctive inputs and outputs, there's still the problem that I noticed (you can end up with an unwanted configuration). I think "buses" can be compatible with your approach. If I understand what you really want is to be able to name the channels. So what about something like that for example (I'm not sure):
```
buse stereo mono -> gives 2-1 with the standard names (stereo left/stereo right/mono).
```
otherwise you can do
```
buse 2 1 -> gives 2-1 with the default names (input l1/input 2/output 1).
```
or at last
```
buse 2 1 main/auxiliary/output -> gives 2-1 with the names (main/auxiliary/output).
```
and you'll be able to have several buses

**Comment by pierreguillot** [comment]
Play head information (state and question):

- level 1 (Slow rate infos)
  - playing
  - recording
  - timesig
    - numerator
    - denominator
  - looping
    - state
    - start (start position in ppq)
    - end (end position in ppq)
- Level 2 (Medium rate infos)
  - bpm
- Level 3 (Fast and time critical things like)
  - position
    - ppq
    - seconds
    - samples

where are editOriginTime, ppqPositionOfLastBarStart and videoframeRate ?

**Comment by alfonso73** [comment]
Great!
I'd move timesig to level 2 along the bpm. Just for consistency.
And all the new three to level 1.


Il 23 nov 2017 13:28, "Pierre Guillot" <notifications@github.com> ha
scritto:

Play head information (state and question):

   - level 1 (Slow rate infos)
      - playing
      - recording
      - timesig
         - numerator
         - denominator
      - looping
         - state
         - start (start position in ppq)
         - end (end position in ppq)
      - Level 2 (Medium rate infos)
      - bpm
   - Level 3 (Fast and time critical things like)
      - position
         - ppq
         - seconds
         - samples

where are editOriginTime, ppqPositionOfLastBarStart and videoframeRate ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pierreguillot/Camomile/issues/61#issuecomment-346605850>,
or mute the thread

**Comment by pierreguillot** [comment]
Here is what I've done for the moment:
- playhead
  - ---
  - playing *state*
  - recording *state*
  - looping *state start_in_ppq end_in_ppq*
  - framerate *value*
  - edittime *value*   
  - ---
  - bpm *value*
  - lastbar *time_in_ppq*
  - timesig *numerator denominator*
  - ---
  - position *time_in_ppq time_in_samples time_in_seconds*

If something isn't good, feel free to tell me. For the moment the playhead is a boolean (true/false) but we can use a level (0, 1, 2 or 3) that defines the degree of information to send. I just don't know if it's necessary to filter the message. I don't know for example if the position is useful without the bpm or the time signature...

**Comment by pierreguillot** [comment]
Generating new plugins

To generate a new plugin with Camomile, you need to create a folder with the name of the plugin that contains the patches and a small text file that describes the plugins functionalities and options (parameters, presets, MIDI support, etc.). Then you need to use a small script that automatically generates and install all versions of your plugins. It depends on the Camomile versions installed (on MacOS this can be VST, VST3 & AU, on Windows  VST & VST3 and on Linux VST only I guess). It also depends if your plugin is an Instrument or an Effect. And to generate the plugins the script will use the instrument or the effect versions of Camomile. So I propose that the names of the plugins should be followed by Fx if the plugin is an effect to distinguish between them. So if your plugin is named MyPlugin it will be an instrument and if the plugin is name MyPluginFx it will be an effect. Does it sound good to you? Otherwise do you have a better idea. Note that it can't be a dynamic option of the plugin. I need to generate the two kinds of plugin with two different binaries.

**Comment by alfonso73** [comment]
Hi Pierre,
could'nt be better to set an "FX" flag in the text file?
I guess is better be free to name the plugin as the author wants.
I'd leave out the installing part in the exporting process. Is better to
give the users to place the genetated plugin where they want/need in their
dir structure.


www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
> I'd leave out the installing part in the exporting process. Is better to
give the users to place the genetated plugin where they want/need in their
dir structure.

Ok

> could'nt be better to set an "FX" flag in the text file? I guess is better be free to name the plugin as the author wants.

The problem I see is once you have "generated" your plugin, you still can edit the text file. And when the plugin is reloaded, if the text file has been modified the plugin will change except for this option. It can be confusing. But perhaps I could find another approach that doesn't imply to change the name of the plugin.

In fact the script is just a "smart installer" that copies the appropriate Camomile plugins,  rename them and include the plugin files in the packages. That's useful on MacOS because as the plugin is a package it can be pretty boring to regenerate a new plugin but I guess there is no package on Windows or Linux so you'll end up with something like:
MyPlugin.dll
Myplugin/MyPlugin.pd
Myplugin/MyPlugin.txt
Myplugin/other pd patches

**Comment by alfonso73** [comment]
So let's go for the FX suffix.
Can effects have MIDI in/out?

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
> So let's go for the FX suffix. 
No, I think you're right! I just need to find a better solution :)

> Can effects have MIDI in/out?
Yes of course. I just don't know how to are SysEx, MidiByte & SysRealTime in JUCE or how to translate the information from/to Pd (already in todo list #59). If you have an idea ;)

**Comment by pierreguillot** [comment]
A pre release is available for Linux and MacOS, I'll create a new issue after feedback

**Comment by alfonso73** [comment]
Thanks Pierre! But i'm on Win..so i can't test

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
I'm working on it :)

**Comment by alfonso73** [comment]
great!

Il 30 nov 2017 18:37, "Pierre Guillot" <notifications@github.com> ha
scritto:

**Comment by pierreguillot** [comment]
Linux/Windows/MacOS releases are available

**Comment by pierreguillot** [comment]
:)

**Comment by alfonso73** [comment]
That's great. When i try to open my DAW (Reaper) while the DAW is scanning
the new plugin i get an error about libpd not present in my system.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
Thanks I'm working on it




2017-12-03 19:22 GMT+01:00 Alfonso Santimone <notifications@github.com>:

**Comment by pierreguillot** [comment]
There are new binaries for Windows here #65.
