### ISSUE TITLE
Ms-Windows tests & fails

### ISSUE THREAD

**Issue by Lucarda** [pierreguillot/Camomile#65]
I'm trying v0.1.0-beta5 and finding lots of troubles. I never tried earlier versions.

Analysis with [http://www.dependencywalker.com/](http://www.dependencywalker.com/) shows that "Camomile.dll"
is calling "libpd.dll" which is not present anywhere on "CamomileWindows.zip". 

![cvst1](https://user-images.githubusercontent.com/25239522/33530689-763f5742-d862-11e7-95ba-7c7e2ff50676.jpg)

Windows expirience tells me that libpd.dll should be placed on the same dir as camomile.dll.

Apart from that it seems "Camomile.dll" is compiled for 64bit. My host
(ableton live 7) does not load 64bit VSTs. 

Can you provide 32bit builds?

I have some other 64bit vsts, I will try to get some host that loads them in the mean time, I'll post back if I can load 64bit vsts.

**Comment by Lucarda** [comment]
Ok I now have [http://www.hermannseib.com/english/vsthost.htm](http://www.hermannseib.com/english/vsthost.htm) which loads 32 or 64 bit VSTs with no problem.

Let me know when you have a "libpd.dll" 

: - )

**Comment by pierreguillot** [comment]
[CamomileWindows.zip](https://github.com/pierreguillot/Camomile/files/1526675/CamomileWindows.zip)
Here is a version that should be statically linked to libpd (I hope...) so you shouldn't need libpd.dll. I'll create a 32bits version soon.
Thx

**Comment by pierreguillot** [comment]
And here is a 32bit version 
[CamomileWindows32.zip](https://github.com/pierreguillot/Camomile/files/1526814/CamomileWindows32.zip)

**Comment by alfonso73** [comment]
Great! But i have the same problem about libpd.dll not being found

**Comment by alfonso73** [comment]
And i have the same dependencywalker results as @Lucarda

**Comment by Lucarda** [comment]
Yeah, same missing `libpd.dll` as @alfonso73  on both 32 & 64.

I'm also trying the .vst3's.

Testing on win8.1 64bit
Ableton Live 7 32bit
vsthost.exe (loads 64 or 32 vsts)

**Comment by alfonso73** [comment]
I'm testing on Windows 7 64bit with Reaper 64bit.
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
I'm still working on it. Thanks for the feedback

**Comment by pierreguillot** [comment]
Here it is with the dll (just to test...) I've no better solution for the moment
[CamomileWindows32.zip](https://github.com/pierreguillot/Camomile/files/1531066/CamomileWindows32.zip).
[CamomileWindows64.zip](https://github.com/pierreguillot/Camomile/files/1531085/CamomileWindows64.zip)

At least you can tell me if there are others problems...

**Comment by Lucarda** [comment]
Ok the 32bit is starting to live.

I filled the new dependencies:

LIBGCC_S_DW2-1.DLL
LIBWINPTHREAD-1.DLL

It loads on vsthost but not in abletonLive:

![c3](https://user-images.githubusercontent.com/25239522/33625297-e39ec862-d9d5-11e7-9015-d060818c7257.jpg)


but I'm unable to load any .pd.
Clicking on the flower does nothing.

///////////////////////////////////////////////////

The 64bit needs:

LIBGCC_S_SEH-1.DLL
LIBWINPTHREAD-1.DLL

but even if placing them the host refuses to open the vst.

**Comment by pierreguillot** [comment]
@Lucarda That's a start. Thanks! The lib for pthread is now included in the distribution (you can have a look at the last pre-release beta6). If the GCC lib is not included, it means that there is a really bad support of libpd for windows... :( I'll try to see how to manage that also...
Anyway, if you can't load a patch it's normal :), the behavior has changed since v0.0.7. In the **Effects** or **instruments** folders, you'll find patches. You can use them to generate real usable plugins. For example:
1. Copy and rename **CamomileFx.dll** to **Bulgroz.dll**
2. Put **Bulgroz.dll** in your plugin folder and add next to it the **Bulgroz** folder that is in the **Effects** folder of the distribution.
3. Open your DAW you should be able to see a new VST Fx plugin named **Bulgroz**.
You can do the same with **Castafiore** and with **MiniMock**, you have to instrument version **Camomile.dll** instead of the effect version ** CamomileFx.dll**.

It would be great, you can try 1st with VSTHost and thereafter with the other DAWs! 
When you click on the flower, you don't have any popup at all (you should have the console and the information)

Cheers

**Comment by alfonso73** [comment]
Hi @Lucarda can you share the .dll?
I still have libpd.dll not found....

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by Lucarda** [comment]
Ok, I'm trying v0.1.0-beta6 32bit from the git.

This one needs LIBGCC_S_DW2-1.DLL which is not shipped.

It works on VSThost.exe but not on abletonLive7:

I've all my files in the same dir as the dlls, there I've copied the MiniMock etc folders.
The 3 examples work:

![c4](https://user-images.githubusercontent.com/25239522/33634282-713bd31a-d9f2-11e7-8fa5-e6369d96440b.jpg)


/
/
/
/



It seems the audio volume is rather soft but there might be something I'm missing using Vsthost.exe

/
/

**Comment by Lucarda** [comment]
@alfonso73 

> I still have libpd.dll not found....

try the latests beta6  https://github.com/pierreguillot/Camomile/releases 

LIBGCC_S_SEH-1.DLL might be needed for the 64bit.

For the 32bit see above.

: - )

**Comment by alfonso73** [comment]
I still have the same error. Where can i find for win64?
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by alfonso73** [comment]
![depwalker](https://user-images.githubusercontent.com/3230434/33635667-23fb6422-da19-11e7-8100-fa92777e45ba.JPG)

this is my dependencywalker for the latest version

**Comment by Lucarda** [comment]
I think you are testing an 64bit dll on a 32bit dependencywalker.

**Comment by Lucarda** [comment]
Oops sorry I my be wrong!

**Comment by alfonso73** [comment]
i'm using dependencywalker 64bit version

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by Lucarda** [comment]
Your pic does not show all [?], scroll a bit up, you should find LIBGCC_S_SEH-1.DLL 

unfortunately not all [?] are true, you can have them on a complete and good working .dll

**Comment by Lucarda** [comment]
It can also be the case that LIBGCC_S_SEH-1.DLL is on your computer.
Same other program might have installed on your windows/system*whatever folder.

If this is the case you're ready to test, windows will auto-find it. (depwalker should also find that dep if it is in the correct system*whatever folder).

**Comment by alfonso73** [comment]
My pic shows all the question marks i get from the dependencywalker analysis

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by alfonso73** [comment]
![folder](https://user-images.githubusercontent.com/3230434/33636855-53cfa974-da1e-11e7-98bc-a87e0277b1dc.JPG)

and this is the content of my exported plugin folder

**Comment by Lucarda** [comment]
Ok,
You should't have the Minimoc folder contents around. You should have a copy of the folder. Just copy the folder there.

**Comment by alfonso73** [comment]
Sorry i don't understand you. The pic is the content of the copy of Minimock folder that i placed in my VST path where my DAW (Reaper) can scan the plugin. I changed the name to Minimock2 to force a rescan because if the name stays the same after a failed scan the plugin is not scanned again.

**Comment by alfonso73** [comment]
the path of the files you see in the pic is C.\VstPlugins 64x\Test\Minimock

**Comment by Lucarda** [comment]
Delete everything and start again.
Nothing will work if you change the names.

**Comment by Lucarda** [comment]
My 64bit thing is working.
see pic:

![c5](https://user-images.githubusercontent.com/25239522/33637338-3011a722-d9ff-11e7-89a6-8b527e5c2389.jpg)

**Comment by alfonso73** [comment]
What do you have in the Minimock subfolder? Maybe i'm doing something wrong folder-wise?
Anyhow this is my new try with Bulgroz
![bulgroz](https://user-images.githubusercontent.com/3230434/33637405-147e5c40-da21-11e7-8778-c77f05250211.JPG)

**Comment by alfonso73** [comment]
There's maybe something not so clear about how to build the directory structure.

**Comment by Lucarda** [comment]
The folder thing is incorrect.

you should do a **rock** folder.
there you copy all the camomile/camomile things (dlls vst3 lib def)

Now copy to your **rock** folder the Bulgroz folder.

do the copy and rename thing to CamomileFx.dll.

Tell reaper to scan your **rock** folder

**Comment by alfonso73** [comment]
What do you mean with "rock". For consistency I'd like to have my Plugin
in their own subfolder. So I'd call that folder with the plugin name.

Il 6 dic 2017 01:17, "Lucas Cordiviola" <notifications@github.com> ha
scritto:

**Comment by alfonso73** [comment]
But maybe Pierre planned to have a Camomile folder in the VST search path
and then a lot of generated dll inside...

Il 6 dic 2017 01:42, "alfonso santimone" <alfonso.santimone@gmail.com> ha
scritto:

**Comment by Lucarda** [comment]
Ok this is how your "C.\VstPlugins 64x\Camomile" should look like. It has the 3 example plugs.

see pic:

![c6](https://user-images.githubusercontent.com/25239522/33638766-830af490-da06-11e7-9915-069c322311a5.jpg)

**Comment by alfonso73** [comment]
Yeah. Got it. That's not so friendly for organizing Plugins folder by
Plugin type. But given that this is a so special project it can be fair :-)

Il 6 dic 2017 01:52, "Lucas Cordiviola" <notifications@github.com> ha
scritto:

**Comment by Lucarda** [comment]
Try it, reaper should only show you 3 plugs on the camomile folder.
They all share the same resources so this way you don't triplicate them.

**Comment by alfonso73** [comment]
Yes I understand the reason for Pierre's choice. I'll run a test tomorrow
morning. Thanks!

Il 6 dic 2017 01:58, "Lucas Cordiviola" <notifications@github.com> ha
scritto:

**Comment by Lucarda** [comment]
@pierreguillot 

I've tried with a more recent Ableton Live (9.1 32bit) but it refuses to load.

: - (

**Comment by Lucarda** [comment]
@pierreguillot 

I did some **hack** to have abletonlive7 opening the plugs.

![c7](https://user-images.githubusercontent.com/25239522/33645446-9f663988-da29-11e7-83f8-f943ead7b9e4.jpg)


I placed only the renamed CamomileFx.dlls and the plugs folders on my normal c:\vst folder, where the vsts.dll are normaly placed. The rest (all contents of camomile/camomile) I placed them on the same dir as Live 7.0.3.exe (C:\Program Files (x86)\Ableton\Live 7.0.3\Program).

The non midi fx work OK but the midi one seems to not be recognized as having midi input.

My be the **hack** is just an ableton issue, lets wait for @alfonso73  tests on Reaper.

**Comment by alfonso73** [comment]
Hi guys,
i decided to do step by step tests.
I've just placed the Camomil folder as it comes from the .zip distribution for Win64 in my VST folder (you can read the path in my screencap).
Then i just checked Camomile.dll with dependencychecker for 64bit.
Same results as you can see. So the problem is before plugin export. At least on my Win7 64bit system.
![test_stage_01](https://user-images.githubusercontent.com/3230434/33653084-13f36a72-da6c-11e7-8a99-a17bcebd479d.JPG)

**Comment by alfonso73** [comment]
I guess that is some dinamically linked library wich the original (maybe libpd) code expect to be somewhere in the system.
I can suggest for future plans to place in the exported plugin .txt file a string pointing to the Camomile resource path. So every plugin can be freely placed in custom directories inside the VST path of the DAW.

**Comment by pierreguillot** [comment]
Thank for all the feedback. The good news it that it seems to work (with some hacks). So to summarize:

1 - Folder organization:
---
I guess the folders structure is a bit complicated for in the current version. I didn't expect to have other dll than the vst. Normally it would have been the plugin dll and an folder associated. Something like this for example:
- MyPlugin.dll
- MyPlugin\
  - MyPlugin.pd
  - MyPlugin.txt
  - other stuff ...

But with the dll dependencies, it gives:
- MyPlugin.dll
- Winpthread.dll
- WinGCC.dll
- MyPlugin\
  - MyPlugin.pd
  - MyPlugin.txt
  - other stuff ...

Ad @Lucarda said, the advantage is that the dll dependencies are shared by all the plugins. But the VST folder become a mess. Perhaps it would be better to have something in a all-in-one folder:
- MyPlugin\
  - MyPlugin.dll
  - Winpthread.dll
  - WinGCC.dll
  - MyPlugin.pd
  - MyPlugin.txt
  - other stuff ...

What do you think of it? I assume that having duplicated dll for each plugin is not a problem for modern computers (except it you have 1 millions of Camomile plugins, you will have enough space on your machine). 

What is important is that the dll dependencies have to be placed next to the plugin dll or in the standard Windows library folder. This is where the executables look for dll, I can't change it. So defining a path in the text file would be useless. But another option is to ask the use to install the dll dependencies in its standard Windows library. There is a native application for that on Windows I think. The main problem, is if you want to share a plugin with someone that has never used Camomile, he has to install this dependencies.

**Comment by pierreguillot** [comment]
@alfonso73 
What I think you also need the dll of libgcc (if you look at the @Lucarda pictures, he uses the libgcc_s_dw2-1.dll for 64 bits version and the libgcc_s_seh-1.dll for the 32 bits version). I think I can remove this dependency (I hope). Perhaps @Lucarda can gives you a copy of this dll to test. Or directly the 64bits folder of one of the plugin for example?

**Comment by pierreguillot** [comment]
2 - The Ableton Issue
---
When the plugin is loaded is looks, next to it, for the folder named identically. For this I have to find where the plugin dll is located. So if it works when you place the plugins' folders in the Ableton path (*C:\Program Files (x86)\Ableton\Live 7.0.3\Program*), it means that there is a confusion and that I retrieve the path of the application instead of the path of the plugin.  I guess it depends on how the plugins are loaded by the DAW. I'll try to find a solution. Perhaps, first to help, if the folders are not found I can print in the console where the plugin has looked for it.

**Comment by pierreguillot** [comment]
Anyway, thanks a lot! It's really helpful!

**Comment by alfonso73** [comment]
@pierreguillot Even placing libgcc_s_dw2-1.dll in the suggested directory structure i still have libpd.dll not found when i scan the VST

**Comment by pierreguillot** [comment]
@alfonso73  That's strange. Are you sure, it's the 64bits libpd.dll from the 64bits Windows release? If @Lucarda gives one of his 64bits package to you, we'll be sure that a problem specific to your system.

**Comment by alfonso73** [comment]
The old Camomile used to work on my system.
Anyway the libpd.dll is the one included in the latest Camomile64 archive. And as you can see is a 64x architecture dll
![libpd](https://user-images.githubusercontent.com/3230434/33659741-9444e614-da81-11e7-9db1-527ff86bed65.JPG)
Hope we can find a way over this.

**Comment by alfonso73** [comment]
This is a dependency check of the libpd.dll itself. I guess there's something in the libpd.dll compilation that my system doesn't like :-D

**Comment by alfonso73** [comment]
...wait wait....i discovered a libpd.dll file in my C:\Windows\SysWOW64 folder. It's the common system folder where all system driver goes..i try to remove it

**Comment by alfonso73** [comment]
..nope..doesn't cure the problem. Still same results no libpd.dll found and same dependency check results

**Comment by pierreguillot** [comment]
> The old Camomile used to work on my system.

Yes but I used my own Pd wrapper for the old Camomile. Now I try to use libPd that doesn't support very Windows for the moment. I have to find a Windows machine and check on it, otherwise it will be a nightmare to debug

**Comment by alfonso73** [comment]
could be a matter for the general pd forum/github?

**Comment by Lucarda** [comment]
@pierreguillot 

I will try to clarify a couple of things:

## The ableton issue:


this is the folder structure (click on the pic to enlarge):

![ca8](https://user-images.githubusercontent.com/25239522/33676786-6d50d838-da95-11e7-8c45-1c1c67e82820.jpg)

it seems ableton dislikes non-vst dlls in its vst folder (c:\vst). Anyway I've never seen other types of dlls in a vst folder in all my windows life.

**Comment by Lucarda** [comment]
@pierreguillot 

As you can see in the picture above I have a pdvst folder. Pdvst~ gave me the inspiration to try putting the files on the same dir as live.exe.

This in turn makes me think that you can hardcore somewhere on the loading thing an “./camomile/”
If this is done it could possibly be the case that we put the non-vsts.dll in a “C:\vst\camomile” folder.
We should try that if posible.
Other solution is the one you gave about installing the nonvast.dll in a system folder.

**Comment by Lucarda** [comment]
@alfonso73 

Can you try downloading this:

[Camomile64test.zip](https://github.com/pierreguillot/Camomile/files/1536380/Camomile64test.zip)




Extract the folder and put it on your “C:\VstPlugins 64x\”

It could be the case that Reaper don't complain about non-vst.dlls

**Comment by alfonso73** [comment]
It works!!! But even Reaper doesn't like not VST stuff .dll so i moved the dll to the Reaper main application folder. i guess that the best thing would be to place the path to all needed resources in the plugins .txt file.

**Comment by Lucarda** [comment]
Ok, good.

My test also work if placing the nonvst.dlls on the system folder instead of the same as DawHost.exe.

Some important notes on this:

32bit Os – 32bit dll
C:\Windows\System32

64bit Os – 64bit dll
C:\Windows\System32

64bit Os – 32bit dll
C:\Windows\SysWOW64

You might think that I got it wrong but is not. See https://en.wikipedia.org/wiki/WoW64

**Comment by alfonso73** [comment]
Thanks Lucas. Funny naming at Microsoft :-D

Il 7 dic 2017 01:07, "Lucas Cordiviola" <notifications@github.com> ha
scritto:

**Comment by alfonso73** [comment]
Oh.. And today I'll go further with folder experiments. I guess that
camomile.dll etc are not necessary in the VST folder. And that the vst
subfolder can have huge same name as the generated Plugin. As far as I
understand the original camomile stuff is only necessary at the moment of
copying the dll and then renaming it to the patch and txt files

Il 7 dic 2017 08:37, "alfonso santimone" <alfonso.santimone@gmail.com> ha
scritto:

**Comment by pierreguillot** [comment]
Ok it means that the plugin achieves to localize its folder. That's a good news! If the dll dependencies can't be with the dll plugin, I think the best place for them is in the system folder. This way you'll be able to use the plugins with other DAW.
@alfonso73 Yes the original Camomile.dll is not necessary because it's the same dll as Bulgroz.dll for example.

**Comment by alfonso73** [comment]
yeah @pierreguillot ! i guess that a future windows installer should place all the system dll into C:\Windows\System32 for x64 and x32 systems and in C:\Windows\SysWOW64 for 32bit version installed on x64 system (this make sense if an user with 64bit OS still uses some 32bit only Hosts). Thanks @Lucarda for the naming convention explanations. Then i'd put the Camomile main folder in C:\Program Files and will be up to the user to create custom dirs in VST path for every created plugin.

**Comment by alfonso73** [comment]
Actually i did test Minimock.dll inside a C:\VstPlugins x64\Minimock\, all sys files in C:\Windows\System32 and all the Camomile dll and vst3 in C:\Program Files\Camomile. Everything works just fine.

**Comment by Lucarda** [comment]
>Actually i did test Minimock.dll inside a C:\VstPlugins x64\Minimock 

I will test that.

>and all the Camomile dll and vst3 in C:\Program Files\Camomile 

I believe that that "C:\Program Files\Camomile" does nothing. Your plugs will run without it.

Can you test moving that Camomile folder to your desktop.

**Comment by alfonso73** [comment]
Those files are actually not needed. I was trying to figure out an ideal
directories structure for the final release

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by Lucarda** [comment]
> >Actually i did test Minimock.dll inside a C:\VstPlugins x64\Minimock

>I will test that.

Placing Minimock.dll inside the Minimock folder **don't** work for me, I belive it shouldn't btw.

**Comment by alfonso73** [comment]
![minimockfolder](https://user-images.githubusercontent.com/3230434/33731974-2e11529c-db85-11e7-96a6-7dde9d807520.JPG)

this is my folder structure

**Comment by Lucarda** [comment]
Oh Ok. That should work.

: - )

**Comment by pierreguillot** [comment]
Thanks. When I'll get access to a Windows machine I'll test everything. One good thing would be to reduce the number of dlls to install. Then if there are still dlls, if I don't manage to link everything statically in Camomile.dll, I'll create a step-by-step tutorial to explain how to install the dlls and how it works. Or perhaps I could create a script to do install everything. The most important thing if the libpd.dll is still necessary is to rename it libpd-multi.dll. Otherwise I'm afraid to have conflicts with other libpd applications that don't need multi instance.

**Comment by alfonso73** [comment]
Nice plan!
a.

ps. would be great to have a short tutorial about the .txt file (may be the
"e" in "buse" is a typo?) and on how to expose parameters to VST/AU from
the .pd patch.



www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
I managed to include libgcc and pthread in libpd.dll so it's a good start. Now I'll try to include libpd.dll inside Camomile.dll.

**Comment by Lucarda** [comment]
Wow,

I'm not a Dev but I help a a few.
Where did you get the info to insert pthread and libgcc into your “single” dll.
I would like to spread it among Pd “externals” Devs, and also Pd Devs.
: )

I have clean machine ready to test the new Camomile! : - )

**Comment by pierreguillot** [comment]
I add the linker flags `-static` and `-static-libgcc` (that last one was already set for Java but not in C). I read a lot of documentation on internet and did a lot of tests to find it... I'm not familiar with Makefile and Windows. libpd uses MinGW on Windows (with a Makefile). I'll create an issue on the libpd repo.

**Comment by pierreguillot** [comment]
FYI, on [Appveyor](https://ci.appveyor.com/project/pierreguillot/camomile/history) you can download the compiled plugins of the last commits. Click on the commit you want (green one are compiled), click on the environment you want (mingw64 for 64bits or mingw32 for 32bits) and click on  "ARTIFACTS" to get acess to the zip file. 

Anyway, I will publish a new release soon.

**Comment by Lucarda** [comment]
I just test 0828fcc6.
The pthread and libgcc seems fine.
The plugs seems to not load the folder. I'm getting just the flower.

**Comment by pierreguillot** [comment]
Oops, sorry

Now the dll can be either 
- At the same level than the plugin folder
./Bulgroz.dll
./Bulgroz/Bulgroz.pd
./Bulgroz/etc.

- In the plugin folder 
./Bulgroz/Bulgroz.dll
./Bulgroz/Bulgroz.pd
./Bulgroz/etc.

But I broke the 1st option (just fix it right now) you can try the 2nd option (or wait for the last commit to compile)

**Comment by Lucarda** [comment]
Right.
Good Work!!!

If you can inject libpd into camomile/fx.dll it will be super cool, but is a great advance just to place libpd on a system folder. Easier to debugg/update. : - )

**Comment by Lucarda** [comment]
I just tested f520329a.

Seems to be only woking:

In the plugin folder
./Bulgroz/Bulgroz.dll
./Bulgroz/Bulgroz.pd
./Bulgroz/etc.

Anyway is good to order everything on folders.

**Comment by pierreguillot** [comment]
It's still a work in progress but you can have a look at this [tutorial](https://github.com/pierreguillot/Camomile/wiki/Generate) that explains how to generate plugins

**Comment by alfonso73** [comment]
Hi guys! I'm very busy until end of January but I'll be back testing right
away at the end of this month!  Best!

Il 7 gen 2018 15:48, "Pierre Guillot" <notifications@github.com> ha scritto:

**Comment by Lucarda** [comment]
>look at this tutorial that explains how to generate plugins

Fine, looks good.
Well explained.

We can leave this issue open for further testing if you want, but the Windows version is working fine.

If you are planning to join libpd to the plugs I gladly test.

I switched to “watch” Camomile, you can mention me for test future updates. : - )

**Comment by alfonso73** [comment]
We just need a tutorial for all the txt file options! Great work! best

Il 7 gen 2018 20:04, "Lucas Cordiviola" <notifications@github.com> ha
scritto:

**Comment by pierreguillot** [comment]
Thanks! @Lucarda a new beta release is available and @alfonso73 I'm working on this tutorial :)

**Comment by pierreguillot** [comment]
I close because I think can't improve the actual behavior but feel free to reopen it if needed

**Comment by Lucarda** [comment]
Ok, good.
I've just tried v0.1.0-beta7 and is working fine, both 32 & 64 versions.

The only thing didn't worked was the ”SnowyFirMeter”, it loads and everything but the bangs wont lit. 

: )
