### ISSUE TITLE
support open/save panel

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#71]
Add support for the openpanel/savepanel objects from x_gui.c in Pd sources. I explain the problem [here](https://lists.puredata.info/pipermail/pd-dev/2018-01/021416.html) in the pd-dev list and found a solution just after [here](https://lists.puredata.info/pipermail/pd-dev/2018-01/021417.html). 

In Camomile, the solution could be to send the messages **openpanel** and **savepanel** (with potentially a default path) to symbol **camomile** and the plugin would displays the panel and send back to the patch the result through the receive symbol  **gui** for example.

**Comment by pierreguillot** [comment]
should be fixed with the commits

**Comment by SeanArchibald** [comment]
Hi Pierre,

I ran into this issue today and I don't quite understand the solution. Would it be possible for you send a screenshot of a patch showing how openpanel should be set up?

Your project is amazing! I've only just started with Pd/Camomile today and I already know I'll be using it a lot.

**Comment by pierreguillot** [comment]
I just updated this issue #73.

**Comment by SeanArchibald** [comment]
I just had a thought - it would be nice to use two openpanel objects in the same project. E.g. one for loading a sample, one for loading a tuning. Is there a way to route the output of each openpanel to the correct place?

**Comment by pierreguillot** [comment]
@SeanArchibald I just add another example for this in #73.

**Comment by SeanArchibald** [comment]
Aha so it is possible already. Nice!
