### ISSUE TITLE
Plugin names in Ableton Live

### ISSUE THREAD

**Issue by jdreske** [pierreguillot/Camomile#75]
Hi,
I just tried camomile v0.1.0 on osx and created 2 vsts (Noise.vst and AlmondOrgan.vst from the examples).  I can use them at the same time in Ableton live, so multiple plugins running parallel are supported now i guess. -great!
but the name of the plugin is always Camomile- Is there a way to change that ? To Noise and AlmondOrgan in this example? I tried to replace all "camomile" to AlmondOrgan in the info.plist file but it did not make any difference.
best regards

**Comment by pierreguillot** [comment]
Hi,
> I can use them at the same time in Ableton live, so multiple plugins running parallel are supported now i guess. -great!

Multiple plugins was already supported since the 1st release. I tried it on osx and Ableton and it worked. Did you try the previous version?

> but the name of the plugin is always Camomile- Is there a way to change that ?

Normally, the names should already be Noise or AlmondOrgan. You mean in the plugin list, you now have 2 plugins named Camomile? Can you send pictures and/ot explain what is the content of the vst plugins? Is there any message in the console?  I don't have Ableton Live on my computer so I can't try for now.

Cheers

**Comment by jdreske** [comment]
> Multiple plugins was already supported since the 1st release

Great, I guess I didn't try before.

> You mean in the plugin list, you now have 2 plugins named Camomile?

Exactly:

<img width="422" alt="bildschirmfoto 2018-01-21 um 22 31 40" src="https://user-images.githubusercontent.com/22870457/35199198-3f2cc8d8-fefb-11e7-9664-b4b23780146a.png">

<img width="363" alt="bildschirmfoto 2018-01-21 um 22 30 14" src="https://user-images.githubusercontent.com/22870457/35199204-53f7cd08-fefb-11e7-9a6e-99550dba163d.png">

I created these 2 .vsts as described in the wiki. Well, sort of- I duplicated the camomile.vst file, opened the package and copied the contents of the example folder (AlmondOrgan) into the ressources folder. renamed it to AlmondOrgan.vst, moved to a custom vst folder, repeated everything for noise.vst and showed Ableton the vst folder.


<img width="1239" alt="bildschirmfoto 2018-01-21 um 22 41 13" src="https://user-images.githubusercontent.com/22870457/35199272-57211290-fefc-11e7-97c0-6dc9680beb0b.png">

The console does not show something special. 
Ableton live just gets the name of the plugin from somewhere inside the executable I guess.

**Comment by pierreguillot** [comment]
OK, can you try to rename the executable file in the VST bundle? 
- Show Package Content -> MacOS -> **Camomile** to **AlmondOrgan**
- Rename the **executable file** in Info.plist from **Camomile** to **AlmondOrgan**

Have you tried with VST3 and/or Audio Unit?

**Comment by jdreske** [comment]
> OK, can you try to rename the executable file in the VST bundle?

> Show Package Content -> MacOS -> Camomile to AlmondOrgan
> Rename the executable file in Info.plist from Camomile to AlmondOrgan

I already tried that:

<img width="807" alt="bildschirmfoto 2018-01-22 um 11 29 25" src="https://user-images.githubusercontent.com/22870457/35216433-dd07be7a-ff67-11e7-9ebd-b96f21970e04.png">

live still shows "Camomile"...

> Have you tried with VST3 and/or Audio Unit?

I just tried with Audio Unit. It looks similar at first:

<img width="290" alt="bildschirmfoto 2018-01-22 um 11 49 23" src="https://user-images.githubusercontent.com/22870457/35217360-4175441a-ff6b-11e7-9f0e-829ea49ae7f8.png">

But I changed the name string in info.plist and this is displayed by live:

<img width="385" alt="bildschirmfoto 2018-01-22 um 11 55 28" src="https://user-images.githubusercontent.com/22870457/35217384-680570b4-ff6b-11e7-8f53-e040863eb1ec.png">

<img width="291" alt="bildschirmfoto 2018-01-22 um 11 57 40" src="https://user-images.githubusercontent.com/22870457/35217415-84008420-ff6b-11e7-949e-fd5e259cd848.png">

**Comment by pierreguillot** [comment]
Ok, I'll try with Ableton Live and other DAWs this week. And I will add a sentence about the AU name in the document. Thanks

**Comment by pierreguillot** [comment]
I managed to solve the problem:

So, as you suggested, you have to change the **Bundle display name** (\<key>CFBundleDisplayName\</key>) and the **Bundle name** (\<key> CFBundleName\</key>) to the name of the plugin. See the [documentation](https://github.com/pierreguillot/Camomile/wiki/How-to-generate-plugins) (I just updated it). 

But If the plugin's name are not updated in **Ableton**, close and reopen the application, open the **Preferences** panel, go to the **file folder** section and click on **Rescan** with the **alt** key pressed (it will clear the previous scan results). 
<img width="612" alt="screen shot 2018-01-24 at 6 21 15 pm" src="https://user-images.githubusercontent.com/1409918/35346821-9a561176-0133-11e8-93db-3ec23052d41b.png">

And here are the results
<img width="136" alt="screen shot 2018-01-24 at 6 23 52 pm" src="https://user-images.githubusercontent.com/1409918/35346881-c8318422-0133-11e8-86bc-3e12edd201ae.png">

Tell me if you have any problem.
Cheers

**Comment by pierreguillot** [comment]
And feel free to close this issue if it works

**Comment by jdreske** [comment]
👍
Yes. option-click  on "rescan" updates the displayed plugin names. (on Mac)
