### ISSUE TITLE
sample rate at initialization

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#83]
The question was asked by @jdreske from #82. 
> By the way there are more objects that need a delay to wait for the plugin to initialize.
For example to get the samplerate i had to do this: [loadbang]->[delay 1000]->[samplerate~]->... (I didn't try how many milliseconds are necessary)

**Comment by pierreguillot** [comment]
The 1000ms (`[delay 1000]`) corresponds approximately to the time between the creation of the plugin and the starting of the DSP chain by the DAW. The sample rate is not defined at the startup because the DSP is not started in the DAW. But the most important is that the sample rate can change after the initialization so you should prefer to retrieve the sample rate when the DSP chain is compiled. What I use to do is to use a default sample rate at initialization (for example 44100hz) and to change the processing if the sample rate changes when the DSP chain is compiled. You can receive a notification that the DSP chain is compiled in Pd with
```
[receive pd]
|
[route dsp]
|
[sel 1]
|
[samplerate~]
```
If it's needed I can however compile the DSP chain of Pd with default values before the DAW start the DSP but I can't see the benefit as it will be re-compiled just after when the DAW starts the DSP.

**Comment by pierreguillot** [comment]
I guess it would be necessary to explain that in the documentation. And what are the other objects? Can you create other issues for them? Also if the explanation is good enough you can close this issue.

**Comment by jdreske** [comment]
I don't know any other objects that ask the plugin for something.
Thanks for the great hint.

**Comment by pierreguillot** [comment]
FYI, now the DSP is initialized before loading the patch (v1.0.2). But it doesn't really change the problem neither.
