### ISSUE TITLE
Manage additional audio buses

### ISSUE THREAD

**Issue by jesuzz** [pierreguillot/Camomile#87]
Hi, nice work on Camomile. I am having a problem when trying to create a VST plugin having more than two input channels in Ableton. Typically if you have a plugin with multiple inputs on a track you can choose which input to send to from other tracks.

This works for non-Camomile plugins (e.g. DDMF Metaplugin). If I load the Camomile plugin in DDMF Metaplugin or VSTHost (http://www.hermannseib.com/vsthost.htm) it shows the correct number of inputs. Seems to be a Camomile-Live issue. Any thoughts on this?

Keep up the good work ;)

[VST plugin.zip](https://github.com/pierreguillot/Camomile/files/1707230/VST.plugin.zip)

**Comment by pierreguillot** [comment]
Hi, 

Have you try to add another bus instead of 4 input channels? I never tried but I think that's the good approach. For example:
```
param -name Amplitude Balance -default 0.5;
param -name Phase Balance -default 0.5;
bus 2 2; // For the main process
bus 2 0; // For the side chain
type effect;
```

>Typically if you have a plugin with multiple inputs on a track you can choose which input to send to from other tracks.

In fact, I don't use Ableton except for testing Camomile on it. I've heard that the multichannel setup is bit complicated and tricky on Ableton but I've never tried. Can you explain me how to set up such configuration and with what plugin (free if possible I'm not going to buy one just for testing)? Or perhaps a tutorial if you have one.

**Comment by jesuzz** [comment]
Hi,
thanks for your reply. You are right, multiple busses (I was not aware that you can do this) are recognized by Ableton. However, as soon as more than one is defined, the sound is heavily distorted, not just in Live. So even this: 
![image](https://user-images.githubusercontent.com/12199562/35990668-0c64d298-0d05-11e8-8837-0c7647e0cb84.png)
with
`bus 2 2;
bus 2 0;`
does not work. I tried various combinations, but was not able to get it to work.

Mutlichannel audio in Live is not bad, I think: You need to switch on the IO options (under View for example) and can then select for each track where it sends its audio to. Select a track with a multichannel plugin in it and you can send it to any of its busses. You might need to set the monitoring to "In" for the receiving track if you use the first bus. The DDMF Metaplugin (https://ddmf.eu/metaplugin-chainer-vst-au-rtas-aax-wrapper/) has a demo which I think you could use for testing.

![image](https://user-images.githubusercontent.com/12199562/35991285-019ff606-0d07-11e8-8e6e-366d160d110f.png)

Source 1 and Source 2 play audio. Multi VST holds an instance of Metaplugin. Source 1 sends to this track (i.e. the plugin's first bus) and Source 2 to the second bus. Getting sound out of the plugin works the same: Multi Outs gets its audio from the second bus' out.

**Comment by pierreguillot** [comment]
Ooops, I forgot to retrieves the signal from the additional audio buses. I will correct it for v1.0.3.

**Comment by jesuzz** [comment]
Nice, thank you for your effort.

**Comment by pierreguillot** [comment]
I will close the issue when it will be fixed ;)

**Comment by pierreguillot** [comment]
I managed to create a plugin with side chain. It will be available with the next release but still a bit experimental. I think the syntax to create buses can be confused for side chain. The syntax works good for mutlichannel plugin and several configuration. Perhaps I should use an argument that could define the accpeted side-chain configurations for each bus layout. For example:
bus 2 2 -extra 0 1 
The fact is that JUCE allows to configure several side-chains (with inputs and outputs) for each bus layout so it's a bit confusing and I'd like to keep something pretty generic.
