### ISSUE TITLE
Implement sidechain capability

### ISSUE THREAD

**Issue by Sebyvivi** [pierreguillot/Camomile#88]
Hi, I'm developing a stereo live convolver and I'm stuck with the matrix managing. I can do it in mono using a single adc with L - R decoding method, but that is 2 mono signals (1 as modulator, the other as carrier); I'd be great to enable sidechain button compatibility to that I just press the sidechain button on the Camomille interface and my daw lists an available stereo input to be used as I want (this case, as an external stereo modulator). 

Thanks for what you're doing.

**Comment by pierreguillot** [comment]
Hi,
Did you look at these issues: #87 and #73? And I think that the side chain can only be given by the DAW. The plugin can't ask for it. I think to add notifications about the audio buses connected that could be received in the patch when the DSP starts so you could adapt the DSP depending on what is connected.
Cheers
