### ISSUE TITLE
Manage externals

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#9]
Try to manage dynamic externals

**Comment by pierreguillot** [comment]
Solution here: https://lists.puredata.info/pipermail/pd-dev/2016-03/020591.html

**Comment by XRoemer** [comment]
Hi,
first of all thanks for this great plugin!

I tried to load py/pyext with your plugin by using [declare -lib C:/<my-path>/py-master/scripts/py] and [declare -path C:/<my path>/py-master/scripts], which works in pd. But camomile failed to load py.dll

I've read the linked solution from your comment above but didn't understand, in which way it gives a solution. Can you explain it more detailed?

Regards,
Xaver

**Comment by pierreguillot** [comment]
Hi,
In fact, the link explains how to solve the problem but I still have to implement the solution. That's why the externals are still not available for the moment. I will close this issue when it will be done.
All the best

**Comment by XRoemer** [comment]
Thanks for the fast reply.

That would be an outstanding feature for me, as I organize presets in pd via python, which is quite comfortable.

**Comment by elsueno** [comment]
hi pierre,

thanks for this great project. i've just stumbled over it and gave it a try and it works! i started patching right away and than had to realize that externals are not supported yet (and found this issue). bummer! are you still working on it? i'd love to use camomille for a project where i'd need certain externals (netsend~, pyext and hoa library).

cheers!

**Comment by pierreguillot** [comment]
Yes, I'm just too overworked to continue this development for the moment but I hope I'll be able to continue soon...

**Comment by pierreguillot** [comment]
Moved to todo list v0.1.1

**Comment by elsueno** [comment]
thank  you!
great to see you working on camomile again!
