### ISSUE TITLE
Glitches/crashes with Roland UA-25EX sound card - ASIO protocol (Windows)

### ISSUE THREAD

**Issue by RichardJECooke** [pierreguillot/Camomile#97]
Firstly, thanks so much for this VST wrapper!  So useful.

I made a simple bandpass plugin in PurrData to test it:

![pd](https://user-images.githubusercontent.com/5468805/36936461-8bec4fc6-1f0e-11e8-9766-e3f4b489f9de.png)

And it displays fine in a DAW, here in Reaper:

![reaper](https://user-images.githubusercontent.com/5468805/36936478-c0536a74-1f0e-11e8-90ea-f35549fb809f.png)

But the sound is bad. Phasing and crackling.

Windows 10, Reaper 64 bit.

Please would you spare a minute to take a look and see what I've done wrong?  
I've attached a .zip file of the patch and the Reaper sample project.

[camomile.zip](https://github.com/pierreguillot/Camomile/files/1777650/camomile.zip)

**Comment by RichardJECooke** [comment]
Yes, something is definitely wrong with Camomile.

Here's an even simpler patch. Just a volume control.  When volume is full (i.e. 100%, doing nothing) it sounds fine, but as soon as it tries to change the sound it's wrong - almost like a sample rate problem.

![untitled](https://user-images.githubusercontent.com/5468805/36997392-2c27b458-20c2-11e8-8b11-61fdc75a0688.png)

[volume_vst.zip](https://github.com/pierreguillot/Camomile/files/1782448/volume_vst.zip)

**Comment by pierreguillot** [comment]
Hi,

You don't use any line~ object so the patch generates audio glitches even in Pd when moving the sliders.
For example:
```
|   [r vl]
|    |
|   [$1 20(
|    |
|   [line~]
|    |
[*~  ]
|
````
You should try to use a different synthesizer because than ReaSyn that already sounds "distorted". Are you sure this is the plugin and not ReaSyn that generates a distorted sound? Why not using a simple sinusoidal oscillator? Because, I don't ear any strange artifact on my MacOS machine. 

Something like that for example:
``` 
[osc~ 220]
|   \
[dac~]
```

Also what is the sample rate? Is it Reaper 5.76?

**Comment by RichardJECooke** [comment]
Thanks for your reply.

- My soundcard (UA-25EX) sample rate (and in Reaper and FL Studio): 44.1 kHz
- Reaper v 5.76 / x64.
- FL v 12.5.1 64bit
- I copied the libpd.dll to c:/windows/system32 and c:/windows/syswow64.
- I copied the VST3 and patch folder to c:/Program Files/Steinberg/VstPlugins.

- FL Studio is worse than Reaper. The Castafiore plugin crashed the DAW immediately. The Bulgroz plugin loaded but the volume jumps to full even when not playing, and when playing it just crackles continuously.

- Just checked on my little Windows 10 laptop and Camomile sound works fine on Reaper, using ASIO4ALL v2, 512 samples, 44.1 kHz.

Can you think of anything I can change or check related to my soundcard settings on my main machine? I've never had a problem with any plugins, DAWs, or PureData patches using this driver before.

**Comment by pierreguillot** [comment]
Yep, that's strange... 
What is the number of samples per block with the external sound card? 
Do you have any improvement if you change it to 64/128/256 or 512 samples?
Do you have a crash report on FL Studio? 
This could drive me to an explanation.

**Comment by RichardJECooke** [comment]
![untitled](https://user-images.githubusercontent.com/5468805/37020018-0651fa7a-2123-11e8-823a-77a16b3236db.png)

Apparently FL doesn't have crash logs: https://forum.image-line.com/viewtopic.php?t=74027

**Comment by RichardJECooke** [comment]
I'm afraid changing the request block size to 32 or 64 makes no difference to the problem.

I also can't change the buffer size to a specific number, none of the options offered by the soundcard driver options screen shown above is a power of 2.

Also, the FL Studio ASIO driver works fine even if I change its request block size to 100 (from 256).

**Comment by pierreguillot** [comment]
Sorry, I'm a bit lost. At last, the plugin doesn't work with the Roland UA-25EX sound card using the UA-25EX driver v1.0.0 and the ASIO protocol (audio system) on Windows 10, isn't it? 

So I have several questions:
- Is the UA-25EX driver v1.0.0 the only driver compatible with this sound card? 
- Can you update this driver? 
- Can you use another driver? 
- Can you use the sound card with another protocol? 

And do you have any difference/improvement if you don't use any graphical interface? 
1- Can you try this?
<img width="60" alt="screen shot 2018-03-07 at 9 59 43 am" src="https://user-images.githubusercontent.com/1409918/37083000-63cb0e28-21ee-11e8-9f01-1bc48a711e69.png">
2- and/or this?
<img width="65" alt="screen shot 2018-03-07 at 9 59 30 am" src="https://user-images.githubusercontent.com/1409918/37083026-81b9fad4-21ee-11e8-9c6b-ab9f7b231af7.png">

Thanks

**Comment by RichardJECooke** [comment]
- The plugin doesn't work with the Roland UA-25EX sound card using the UA-25EX driver v1.0.0 and the ASIO protocol (audio system) on Windows 10, isn't it? **Correct**

- Is the UA-25EX driver v1.0.0 the only driver compatible with this sound card? **As far as I know, yes**
- Can you update this driver? **I have the latest driver**
- Can you use another driver? **When I use the FL Studio ASIO driver in Reaper the sound plays correctly through my external soundcard out to my speakers. So I think this might be using another driver, or it might just be using the FL driver internally and sending sound out through the cable  - I don't really understand how that works in Windows**
- Can you use the sound card with another protocol? **As above, I think**

And do you have any difference/improvement if you don't use any graphical interface?
1- Can you try this?  **Same result. Pure tone when using FL driver. Gravelly, distorted tone when using UA-25ex driver.**

**Comment by pierreguillot** [comment]
It's really specific and I'm sorry but I don't have the material to test and debug. I guess, we'll have to wait for a kind soul that could help to solve the problem...

**Comment by pierreguillot** [comment]
Perhaps this is related to this [thread](https://forum.pdpatchrepo.info/topic/11285/crackling-asio-on-pd-vanilla-0-48-test-2-on-64-bit-windows/2)?

Can you try with the 32bit version of the plugin?

**Comment by alfonso73** [comment]
Hi Pierre and Richard,
i tested Richard's file and i have no audio issues.
I have another little thing.
I installed Richard's vst3 and loaded his reaper project and Reaper can't find the vst3. Then i substitute that missing vst3 in the Reaper track with...that very vst3 and everything worked...
strange little issue.

**Comment by pierreguillot** [comment]
Hi,
@alfonso73 

> I have another little thing.

I think the problems is related to the VST ID (see this [thread](https://www.soundonsound.com/sound-advice/resolving-vst-plug-conflicts)). Perhaps the plugin doesn't give the good ID... I'll check that!

@RichardJECooke 
Perhaps your problem is related to this issue #100. Here is new version: 
[CamomileWindows64.zip](https://github.com/pierreguillot/Camomile/files/1821925/CamomileWindows64.zip). Can you try it and tell if there is any improvement? 

Thank you both!

**Comment by RichardJECooke** [comment]
Tried the new version of Camomile you linked to. No difference, still my Roland soundcard driver sounds wrong, my other ASIO driver sounds fine.

**Comment by alfonso73** [comment]
Hi,
@pierreguillot yeah can it reasonably be that thing.

**Comment by pierreguillot** [comment]
I guess the audio driver can force a DAW to use different audio block sizes that weren't managed by the plugin

**Comment by pierreguillot** [comment]
Can you tell me if you have better results with the last release?

**Comment by korakios** [comment]
@RichardJECooke could try ticking the “Use smaller Asio buffer size” box in preferences and see if there is any difference?

**Comment by pierreguillot** [comment]
Any news?

**Comment by pierreguillot** [comment]
I close this due to lack of activity, feel free to reopen if needed.
