### ISSUE TITLE
dynamic patching

### ISSUE THREAD

**Issue by Reinissance** [pierreguillot/Camomile#99]
By now I can add and move GUIs around or change the size of the patch with messages to pd like "donecanvasdialog" etc., but the changes only take effect after closing and reopening the plugin (AU-effect on OSX High Sierra, testing with GarbageBand)
Would love to have the possibility to force redraw of the opened plugin...
Regards Reini

**Comment by pierreguillot** [comment]
I have to see how other applications (like PdParty and PdDroidParty) manage this. Perhaps a solution could be to send a message like `[redraw(` to the plugin via the object `[send camomile]` and it would redraw all the GUI? 
Do you have a concret example to use this feature? 
I'd like to know if you need to redraw frequently - in this case this approach would be too heavy - or just once from time to time - in this case I guess that redrawing everything wouldn't be a problem.

**Comment by Reinissance** [comment]
As far as I made my experiments (about a year ago...) PdParty does not support it either. But I think as you proposed redrawing should be called from inside the patch, after a certain button is pushed for example, like in the example-patch attached.
[dynPatch.zip](https://github.com/pierreguillot/Camomile/files/1808198/dynPatch.zip)

**Comment by pierreguillot** [comment]
Great! Thanks! I think it could be totally feasible using the redraw message. 

There are only two things I need to warn you about (and that I need to write to remember):
1 - For the moment, the GOP abstraction are not supported so you'll have to use a slightly different approach for the bang (but using the send and receive message, it should not be too difficult). I guess we should wreate another issue/feature request for this.
2 - As far I remember, the resizing of the plugin interface is not well supported by all the DAW. I'll try to find a trick

**Comment by pierreguillot** [comment]
See the [issue](https://github.com/pierreguillot/Camomile/issues/73#issuecomment-373757803). Does it seems good to you?

**Comment by Reinissance** [comment]
This is perfect, thank You so much!
